woocommerce/woocommerce-ios

- Podfile
- Podfile.lock
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
Fixes #601. Requires changes made in https://github.com/Automattic/Gridicons-iOS/pull/36.
This PR updates the right nav bar button icon from .menu to .filter in the Order List. 
**Note:** this PR will not be merged until it is approved AND Gridicons 0.18 pod is published.
cc: @danielebogo
> Change right nav bar button from .menu to .filter grid icon.

- WooCommerce/Resources/AppStoreStrings.pot
This PR adds the `app_store_promo_text ` field to the set of strings that are sent for translations as it is now used in the App Store listing.
> Add the Promotional Text field to AppStoreStrings.pot

- WooCommerce/Resources/Info.plist
Copied from the WPiOS app:
https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Info.plist#L63-L64
> Mark the app as only using exempt encryption

- WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/HelpAndSupportViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/Privacy/PrivacySettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
Fixes #598. 
In this PR the row titles change to consistent Title Casing for all Settings screens, and the version number is removed from the bottom of the Help screen.
@bummytime when you get time
| Before | After |
| ------ | ------ |
| ![settings-before](https://user-images.githubusercontent.com/1062444/51277149-69ac4180-199c-11e9-9d22-d49eeb49356b.png) | ![settings-after](https://user-images.githubusercontent.com/1062444/51277164-716be600-199c-11e9-826b-54797b517ea8.png) |
| ![privacy-before](https://user-images.githubusercontent.com/1062444/51277181-7a5cb780-199c-11e9-92ac-dbd494d6b9e0.png) | ![privacy-after](https://user-images.githubusercontent.com/1062444/51277195-80eb2f00-199c-11e9-8bf7-35f18e28a3f9.png) |
| ![help-before](https://user-images.githubusercontent.com/1062444/51277209 …
> Settings > Help: row titles and version number alignment

- Scripts/build-phases/generate-credentials.sh
- WooCommerce/Credentials/Templates/ApiCredentials-Template.swift
- WooCommerce/Credentials/Templates/InfoPlist-Template.h
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Tools/ZendeskManagerTests.swift
Ensures that users configure secrets before compiling.
**To Test:**
- Check out the branch
- Go to `~/.mobile-secrets`, rename `iOS` to `_iOS` (don't forget to change it back after testing!)
- Clean the build folder
- Delete `$SRCROOT/DerivedSources`
- Build the `WooCommerce` target.
**Before:**
- Build would fail across multiple targets without helpful error messaging.
**After:**
- Build will fail with actionable steps to define secrets. Once secrets are defined by hand, the build will complete and the app will run.
- Running tests fail on `ZendeskManagerTests::testZendeskUrl`. It looks like we've hardcoded the secret in that file. We'll likely need to clean that up before publishing the repo?
**Next Steps:**
Once this PR is merged, I propose adding another with a build script for the …
> Add a secrets Swift Template

- WooCommerce/Resources/AppStoreStrings.pot
- WooCommerce/Resources/release_notes.txt
- fastlane/Fastfile
- fastlane/actions/ios_update_metadata_source.rb
- fastlane/appstoreres/metadata/source/app_store_promo_text.txt
- fastlane/appstoreres/metadata/source/description.txt
- fastlane/appstoreres/metadata/source/keywords.txt
- fastlane/appstoreres/metadata/source/subtitle.txt
This PR adds the source files for the App Store metadata and a Fastlane lane to automatically update the related .pot files.
To Test:
1. Run `bundle exec fastlane update_appstore_strings version:1.0` and verify that nothing changes in the .pot file.
2. Check out a new branch from this one.
3. Make some changes to one of the .txt files and commit them.
4. Run `bundle exec fastlane update_appstore_strings version:1.0` and verify that the .pot file has been correctly updated. (Note that the lane may fail on the last `git push` command if the branch you are using doesn't have an upstream set).
> Add source files for app store metadata and related lane

- RELEASE-NOTES.txt
- WooCommerce/Classes/Extensions/DateFormatter+Helpers.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
- WooCommerce/WooCommerce.xcodeproj/xcshareddata/xcschemes/WooCommerce.xcscheme
This PR fixes #621 by localizing the chart axis labels:
As well as the chart markers on the chart bars:
* Build and run the app — verify the unit tests are ✅ and the code deltas look 👍 
* Build and run the app using different device languages in the simulator. You can do this by changing the schema settings in Xcode:
Verify the chart markers and axis labels look like they are localized.
@mindgraffiti would you mind taking a peek at this?
----
> Dashboard: localize chart axis and chart markers

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewModels/OrderDetailsViewModel.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/PaymentTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/PaymentTableViewCell.xib
- WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
Fixes #603.
This applies to **all** orders that do not have a defined payment method, but the easiest orders to spot this change is on orders with the "On Hold" or "Scheduled Payment" status.
cc: @astralbodies who wrote the bug ;)
| Before | After |
|------- | -----|
| <img src="https://user-images.githubusercontent.com/373903/51138145-f07ae600-1805-11e9-8923-8c0816aec587.png" width="300" /> | <img src="https://user-images.githubusercontent.com/1062444/51633757-08deb500-1f18-11e9-849b-aff24dac2cad.png" width="300" /> |
> When no payment method exists, hide payment summary from payment section

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Notifications/NotificationsViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
This PR cleans up some of the localization issues found in #631 (see the issue for specifics). In short, I added more detailed translator comments, made sure we are calling `String.localizedStringWithFormat` for the navbar titles when filters are used, and made sure we set each VC's tabbar title in `init()` and not `viewDidLoad()`.
Fixes: #631 
This might be a little difficult to test since we don't have the i18n strings files in place yet for some of these words.....but in general, make sure the logic makes sense and try launching the sim using different default languages to make sure nothing breaks. 😃 
----
> Fixes some localization issues on the Order List and Notification screens

- WooCommerce/Resources/AppStoreStrings.pot
- fastlane/Fastfile
- fastlane/appstoreres/metadata/source/promo_screenshot_1.txt
- fastlane/appstoreres/metadata/source/promo_screenshot_1_b.txt
- fastlane/appstoreres/metadata/source/promo_screenshot_2.txt
- fastlane/appstoreres/metadata/source/promo_screenshot_3.txt
- fastlane/appstoreres/metadata/source/promo_screenshot_4.txt
- fastlane/appstoreres/metadata/source/promo_screenshot_5.txt
- fastlane/appstoreres/metadata/source/promo_screenshot_6.txt
- fastlane/appstoreres/metadata/source/promo_screenshot_7.txt
- fastlane/appstoreres/metadata/source/promo_screenshot_8.txt
This PR adds the strings used as promotional messages in the screenshots to the set of strings to send to translators.
> Add promo strings for screenshots

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewModels/OrderDetailsViewModel.swift
- WooCommerce/Classes/ViewModels/OrderItemViewModel.swift
Fixes #633.
- navigate to an order detail view (Orders > an Order > scroll to payment section) and check the payment section
- navigate to a product details view (Orders > Order No. 1939 > Details) and check for the Taxes line
> Restore displaying taxes, even when amounts are zero.

- RELEASE-NOTES.txt
- WooCommerce/Classes/Authentication/Epilogue/AccountHeaderView.swift
- WooCommerce/Classes/Authentication/Epilogue/AccountHeaderView.xib
- WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
This PR adds the ability to access help from the store picker screen:
Fixes: #619 
**Test this flow on various devices including iPads**
1. Log into the app and get to the store picker screen
2. Tap the help button in the upper right-hand corner of the screen
3. Verify the support screen appears and works as expected
4. Rotate the device to landscape and attempt steps 1-3 again. 😃 
@mindgraffiti Could you take a quick look at this for me?
----
> Login: Add help button to store picker screen

- RELEASE-NOTES.txt
- WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
This PR disables cell selection if a user only has 1 store available on the store picker screen:
Fixes: #599 
/cc @astralbodies 
0.  Build and run the app (log out if needed)
1. Log into the app and stop on the store picker screen
2. Attempt to select the (only) store tableview cell
0.  Build and run the app (log out if needed)
1. Log into the app and stop on the store picker screen
2. Attempt to select all of the store tableview cells
@mindgraffiti would you mind 👀 at this one?
----
> Store picker: don't allow cell selection for a single store

- RELEASE-NOTES.txt
- WooCommerce/Classes/Extensions/Date+Woo.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Extensions/DateWooTests.swift
This PR fixes the recency message on the dashboard:
_(See the issue #600 for the design requirements)_
To accomplish this, a new extension var was added to `Date` — `relativelyFormattedUpdateString`.  This computed var takes the reciever's date value and re-formats as a localized "update" string.
Additionally, because of the insights provided by @naokomc in #620, all of the "Update" strings are exposed to the translators (including the "Updated moments ago" phrase). Prior to this PR we were using `TTTTimeIntervalFormatter` which was only localized in ~20 languages without much in terms of customization. Now these strings can be fully localized such that they make sense natively. 
Fixes: #600 
* Make sure code makes sense
* Unit tests are ✅ 
* Build and run the app, verify the stats last …
> Dashboard: Update recency message to match designs

- RELEASE-NOTES.txt
- WooCommerce/Classes/Tools/SharingHelper.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Dashboard.storyboard
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/ApplicationLogDetailViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/ApplicationLogViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/HelpAndSupportViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Closes #618.
This PR adds the ability to view, share, and send application logs. 
1. Log in and navigate to My store > Settings > Help & Support > View Application Log.
2. Select any log available and view it.
3. Select the share button and send it, save it, or share it. Verify it arrived at the expected place.
4. When ready, select the "Clear old activity logs" button. Verify only the "Current" row and application log remains.
cc: @bummytime or @astralbodies first review wins 😀
> Help & Support: Add the app log feature

- WooCommerce/Classes/Model/OrderStats+Woo.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
**Note: This is targeting the 1.1 release.**
This PR fixes #653:
In short, from the order stats response JSON, we are now using:
1.  `grossSales` instead of ~~`totalSales`~~ for each bar item in the chart
2. `totalGrossSales` in the response JSON instead of calculating this value "manually" (via `OrderStats+Woo.swift`) for the "Revenue" field under each tab
* Make sure the unit tests are ✅ 
* Build and run the app
@astralbodies could you take a look at this?
/cc @loremattei
> Dashboard: total sales fixes

- WooCommerce/Resources/en.lproj/Localizable.strings
This PR updates the comments in `localizable.strings` in order to shrink all of them down to a maximum of 2 lines. 
For some reasons, the file is not properly loaded by GlotPress if comments are longer. 
This PR fixes only the effect as we need to upload the fixed file asap, but I'm going to open a new one with some tooling to automatically check for this issue.
> Update comments into Localizable.strings

- Scripts/localize.py
This PR fixes an issue with comments in GlotPress where the upload of source files fails when they contain comments that span more than two lines. 
In order to fix it, the script now shrinks the comments to two lines, by concatenating multiple lines.
1. Run the previous version of `Scripts/localize.py`  and save the updated `en.lproj/Localizable.strings`.
2. Run the `Scripts/localize.py` contained in this PR and save the updated `en.lproj/Localizable.strings`.
3. Compare the two versions of `en.lproj/Localizable.strings` and make sure that both files contain the same strings and that comments have been shrunk to 2 lines in the second one. 
> Update localize.py script to handle multiple comments

- WooCommerce/Resources/Info.plist
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- config/Version.Public.xcconfig
- config/WooCommerce.debug.xcconfig
- config/WooCommerce.release.xcconfig
This PR moves the management of the version of the app from the project file to `.xcconfig` files, following what we already do in the WordPress apps. This will help to sharing some of the release tools with the WordPress app itself.
1. Clean your build folder and build the app
2. Locate `Products` > `WooCommerce.app` within Xcode.
3. Right click on it and select "Show in finder"
4. Right click on the app icon and select "Show Contents"
5. Locate the "Info.plist" file, open it, and make sure the version number is correct.
6. Run the app and verify that everything is working and that the version is correctly picked in the about screen.
> Move app version handling to xcconfig files

- WooCommerce/Credentials/Templates/ApiCredentials-Template.swift
- WooCommerce/Credentials/Templates/InfoPlist-Template.h
Currently, if you check out this repo and try to build, it immediately fails. This means that even unit tests can't be run without the secrets being set up.
This is a very small change to the template files so that tests can be run without the full secret set up. This will be useful for CI.
Here is an example failing on CircleCI without this change: https://circleci.com/gh/woocommerce/woocommerce-ios/59
And here is one passing with this change: https://circleci.com/gh/woocommerce/woocommerce-ios/66
> Update secrets placeholders so that build & tests can pass without credentials

- WooCommerce/Classes/ViewRelated/Notifications/NotificationsViewController.swift
Title has it.
Fixes #667 
Build and run the app. Verify the notification filter icon is correct.
@mindgraffiti would you mind taking a 👀?
> Notifications: Gridicon update .menus to .filter

- WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
Originally the event discussed was to be named `settings_selected_store_tapped`. Per the [spreadsheet](https://docs.google.com/spreadsheets/d/17cKoFpHQpUMNo-stHSIyEyHbOZ30AIikTHWf9GKVwI0/edit#gid=86001244), Android is reporting `settings_selected_site_tapped`. This PR fixes the event that is reported, so that it matches the spreadsheet.
> Tracks event name changed from `store` to `site`

- README.md
BuddyBuild will be turned off soon so this replaces the badge in the README.
> Replace BuddyBuild status badge with CircleCI badge

- WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
Fix #699 
I haven't been able to reproduce the issue consistently, I have only been able to replicate it twice. I presume that would be because my dataset is not large enough yet, and therefore the migration happens too fast.
The solution I submit here is a bit of a shot in the dark.
- Default to "My store" as title if by the time the view appears on screen the `sessionManager` does not have a `defaultSite` yet.
- Assign the title again after data load (i.e. stats and orders) is completed. Not ideal, but it does not seem like a huge waste of resources. I assume there might be a more elegant way to be notified when the reload is going to begin, but I could not find it.
- Assign the title as well when the `defaultAccountWasUpdated` notification is received.
Worst case scenario, the title …
> Default Dashboard title to "My Store" when the view controller is loaded without an available store

- WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/ApplicationLogViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrderLoaderViewController.swift
It turns out lint isn't running properly right now. To fix that I'm going to add Hound as we use on WPiOS. But first, this fixes the few lint errors that we have right now 😄 
There is already a `.hound.yml` file so its ready to turn on.
To test:
- Run `rake lint`
> Fix lint errors

- .swiftlint.yml
We have an informal vertical whitespace standard that is causing linting to fail on Hound. Specifically:
* [2](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/Model/Age.swift#L2-L3) or [3](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/Notifications/PushNotificationsManager.swift#L6-L8) lines after import statements
* [2 lines](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/Notifications/PushNotificationsManager.swift#L54-L55) before an extension (or its `MARK` comment)
The [`vertical_whitespace` rule in swiftlint is enabled by default](https://github.com/realm/SwiftLint/blob/master/Rules.md#vertical-whitespace) and limits vertical whitespace to a single empty line. This PR updates that …
> Lint config updated for vertical_whitespace

- .swiftlint.yml
Configuration via [Swiftlint configuration docs](https://github.com/realm/SwiftLint#configuration)
First reviewer wins 😀 
> Update hound to allow 160 characters for a line length, instead of 120.

- WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
Fixes #729 
Present a Notice after users switch a store, with a message informing that only notifications from the newly selected stores will be received.
- Checkout the branch
- Switch stores. The Notice should be visible.
@kyleaparker I am not sure about the wording. Space in the Notice is limited, so I tried to make it as short as possible, leaving the store name at the end of it.
> Present a Notice after switching a store, informing users that they will only receive notifications from the active store

- WooCommerce/Classes/ViewRelated/Orders/NewNoteViewController.swift
Fix #728
The keyboard was covering the Notice being presented when there is an error submitting a new note to the backend.
The fix:
- The keyboard is dismissed as soon as users tap the Add button, by making the text view resign its focus.
A short gif, when there is no connection at all:
- Checkout the branch
- Follow the reproduction steps in the original issue #728 
- The Keyboards should be dismissed when tapping "Add", and in case of an error, the Notice should be visible.
> Hide the keyboard when attempting to commit a note to the backend.

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/NewOrdersViewController.swift
> Set the chevron image to flip upon changing to a RTL language

- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTrackingTableViewCell.xib
Fix #745 
Update top and bottom margins of the `OrderTrackingTableViewCell` to match the blueprints.
Before and after:
- Checkout the branch, navigate to the Order Details view
- Check the layout of the tracing cells.
>  Shipment Tracking UI. Enhanced layout of tracking cell

- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/SummaryTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
- WooCommerce/WooCommerceTests/Views/SummaryTableViewCellTests.swift
Unsupported order statuses come from other order status extensions.
No bug fix ticket. Not adding bug fix details to release notes because bug was created, caught, and fixed in the same release.
> Create a temporary fix: display slugs for unsupported order statuses

- Networking/Networking.xcodeproj/project.pbxproj
- Networking/Networking/Network/Tools/Loader.swift
- Networking/Networking/Remote/Remote.swift
- Podfile
- Podfile.lock
- Storage/Storage.xcodeproj/project.pbxproj
- Storage/Storage/CoreData/CoreDataManager.swift
- Storage/Storage/Extensions/NSManagedObjectContext+Storage.swift
- WooCommerce/Classes/Analytics/TracksProvider.swift
- WooCommerce/Classes/Notifications/PushNotificationsManager.swift
- WooCommerce/Classes/Tools/Fabric/FabricManager.swift
- WooCommerce/Classes/Tools/ResultsController+UIKit.swift
- WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/NewOrdersViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/StoreStatsViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformersViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/FulfillViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/NewNoteViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- Yosemite/Yosemite.xcodeproj/project.pbxproj
- Yosemite/Yosemite/Stores/OrderNoteStore.swift
- Yosemite/Yosemite/Stores/OrderStatusStore.swift
- Yosemite/Yosemite/Stores/SettingStore.swift
- Yosemite/Yosemite/Stores/ShipmentStore.swift
- Yosemite/Yosemite/Tools/ResultsController.swift
Closes #765 
This PR fixes a problem with not being able to produce an archive because of an error with CocoaLumberjack. This resolves that problem by also specifying CoocaLumberjack as a dependency, not just CocoaLumberjack/Swift. CocoaPods was creating a second target with a slightly different name but the same artifact name. Eventually the right solution is to remove CocoaLumberjack as a dependency entirely from all of our Podspecs and conditionally support a custom logging solution if the consuming target has it (like a weak linking).
> Fixed CocoaLumberjack preventing an archive from being created

- Rakefile
Hound uses SwiftLint 0.27.0 so this makes our Rakefile use that version. It also simplifies the logic for downloading SwiftLint to use the portable zip file rather than attempting to extract the `.pkg`.
Test:
- `rake lint` should work correctly.
> Update SwiftLint to 0.27.0

- Networking/Networking/Remote/OrdersRemote.swift
- Networking/NetworkingTests/Responses/order.json
- Networking/NetworkingTests/Responses/orders-load-all.json
- WooCommerce.xcworkspace/contents.xcworkspacedata
This PR adds the `_fields` request param to the orders API calls (ref: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1157). Doing so reduces the average response body size **by ~50%** (e.g. 120kB to 60kb). 🎉 
Fixes: #757 
1. Make sure the unit tests are all ✅ (I updated the testing response JSON as well)
2. Run the app...in multiple stores, verify all screens related to orders (Order List, Order Detail, Order Searching) load without any issues (look for errors in the console). Be sure to attempt loading a variety of order types → orders with notes, coupons, line items, etc.
@ctarda would you mind taking a quick peek at this? Thank you!
>  Networking: Added the _fields param to orders

- Networking/Networking/Model/NoteBlock.swift
- WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
- WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
- WooCommerce/Classes/Extensions/Date+Woo.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/Privacy/PrivacySettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Fancy Alerts/FancyAlertViewController+Upgrade.swift
- WooCommerce/Classes/ViewRelated/Notifications/NotificationsViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
- WooCommerce/WooCommerceTests/Tools/StringFormatterTests.swift
- Yosemite/Yosemite/Stores/ShipmentStore.swift
- Yosemite/Yosemite/Stores/StatsStore.swift
This PR addresses the ~26 linter errors we had thanks to #769 😉 . Every single one was a line length violation (> 160chars). I resolved these issues by using swift's multiline string literal syntax for the most part.
* Review the glorious multi-line syntax 🤣 
* run `rake lint` and make sure no errors appear
* Make sure the unit tests are still ✅ 
* Build and run the app, give a quick once-over to the login prologue, store picker, order detail, settings, and status screens — verify nothing looks out of wack.
@mindgraffiti or @ctarda → first :shipit: wins!
> Lint fixes (primarily line length violations)

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/Cells/ProductTableViewCell.swift
Fixes #709.
Per the i7 designs, the top performers list should say "Total orders" rather than "Total product order."
**Before:**
**After**
> Change text from "Total Product Order" to "Total orders"

- RELEASE-NOTES.txt
- WooCommerce/Classes/Extensions/UILabel+OrderStatus.swift
> Bugfix: background color appears outside of payment status labels

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
Fixes #790 
May also fix the pull-to-refresh broken UI layout (Ref. #789)
> OrderStatus refresh not implemented on pull-to-refresh

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/ReusableViews/BasicTableViewCell.swift
Fixes #785.
This bug was happening because the BasicTableViewCell is used for normal Settings cells and then customized for destructive Settings cells, such as "Log Out". When the cell was reused, there was no "prepareForReuse" method to override and reset the destructive styles.
It takes quite a while to reproduce the bug because a destructive-styled cell has to get re-used. 
1. On the My store tab, tap the gear icon to open Settings.
2. Scroll down on the settings screen.
3. Open the Privacy Settings section repeatedly (Settings > Privacy Settings > Back to Settings > Privacy Settings, etc.).
(Eventually, some or all of the cells would pick up the wrong formatting.)
**Before**
> Add prepareForReuse to Basic cell

- Networking/Networking/Extensions/DateFormatter+Woo.swift
- RELEASE-NOTES.txt
This PR fixes an issue where the shipment tracking dates on order details was incorrect. In short, I fat-fingered the `dateFormat` string 🙄 .
Fixes: #784 
1.  Build and run the app
2. Select a few orders that have shipment tracking information where the ship date is **not** in January
3.  Verify the correct date appears in the UI
> Shipment tracking: dateFormat fix

- Networking/Networking/Extensions/DateFormatter+Woo.swift
- RELEASE-NOTES.txt
This PR introduces a `DateFormatter`[ patch from `develop`](https://github.com/woocommerce/woocommerce-ios/pull/794) into `release/1.4`. 
> ... fixes an issue where the shipment tracking dates on order details was incorrect. 
> Fixed DateFormatter dateFormat string typo.

- Networking/Networking/Settings/Credentials.swift
- Podfile
- Podfile.lock
- WooCommerce/Classes/Authentication/AuthenticationManager.swift
- WooCommerce/Classes/System/SessionManager.swift
- WooCommerce/Classes/Yosemite/StoresManager.swift
This PR is an update to support the latest version of WordPressAuthenticator-iOS. 
The credentials returned from the authenticator pod no longer include a username, just an auth token.  Its the responsibility of the client to fetch the user name for the auth token.  To accommodate the change I've modified `sync(credentials:, onCompletion:)` to use a temporary username (a uuid) to fetch account information, and then proceed with the rest of the login flow.  I'm not too sure what to do about failures to fetch account information and error handling in this PR is rudimentary.  I'd appreciate suggestions.
@bummytime @mindgraffiti what do y'all think?
> Changes to support the latest authenticator pod version.

- WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
- WooCommerce/Classes/Extensions/Date+Woo.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/Privacy/PrivacySettingsViewController.swift
This PR fixes some strings that break genstrings.
1. Run `./Script/localize.py` and verify that it doesn't fail and that `en.lporj/Localizable.strings` is updated.
> Fix some strings that break genstrings

- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
Just a quick PR to address the deprecation warnings that popped up from a recent update to the Charts lib:
@mindgraffiti would you mind giving this a quick 👀 ?
> Fixed deprecation warnings in PeriodDataVC

- WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
- WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
- WooCommerce/Classes/Extensions/Date+Woo.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Notifications/NotificationsViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
This PR reverts some multi line comments to single line. Hound won't be happy at all, but `genstrings` will :-)  
I looked for some updates/replacements to `genstrings`, but I couldn't find anything official, and the two projects that claimed to be drop-in replacement failed to work with various errors. 
I think it's worth to start to look for an updated toolchain, but the lack of good drop-in replacement mean that we'll need to do some migration and validation work.
> Fix genstrings issues

- WooCommerce/Classes/Analytics/TracksProvider.swift
Fixes #567 
This is a stab in the dark to eliminate the crash we're seeing once in a while. By making the Tracks service properties lazy it prevents Swift from initializing them during the implied dispatch once call from the `static let` initialization of `WooAnalytics` shared instance. I'm not entirely sure this will fix anything; we don't really know the reason the persistent store coordinator isn't able to be brought up.
If the crash persists after this fix then my next suggestion is to move as much as possible in the `AppDelegate` into `application(_:didFinishLaunchingWithOptions:)` that doesn't need to be there. Technically willFinish is reserved for state restoration and a few other things. There could be some strange lifecycle problem with the file system.
Testing? Just make sure …
> Make Tracks a lazy init rather than an implied dispatch once

- Networking/Networking.xcodeproj/project.pbxproj
- Networking/Networking/Extensions/CodingUserInfoKey+Woo.swift
- Networking/Networking/Mapper/SiteSettingsMapper.swift
- Networking/Networking/Model/SiteSetting.swift
- Networking/Networking/Model/SiteSettingGroup.swift
- Networking/Networking/Remote/SiteSettingsRemote.swift
- Networking/NetworkingTests/Mapper/SiteSettingsMapperTests.swift
- Networking/NetworkingTests/Remote/SiteSettingsRemoteTests.swift
- Networking/NetworkingTests/Responses/settings-general-alt.json
- Networking/NetworkingTests/Responses/settings-product-alt.json
- Networking/NetworkingTests/Responses/settings-product.json
- Storage/Storage.xcodeproj/project.pbxproj
- Storage/Storage/Model/MIGRATIONS.md
- Storage/Storage/Model/SiteSetting+CoreDataProperties.swift
- Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 13.xcdatamodel/contents
- Storage/Storage/Tools/StorageType+Extensions.swift
- WooCommerce/Classes/Tools/Currency/CurrencySettings.swift
- WooCommerce/Classes/Yosemite/StoresManager.swift
- WooCommerce/WooCommerceTests/Tools/CurrencySettingsTests.swift
- Yosemite/Yosemite/Actions/SettingAction.swift
- Yosemite/Yosemite/Model/Model.swift
- Yosemite/Yosemite/Model/ReadOnly/SiteSetting+ReadOnlyType.swift
- Yosemite/Yosemite/Model/Storage/SiteSetting+ReadOnlyConvertible.swift
- Yosemite/Yosemite/Stores/SettingStore.swift
- Yosemite/YosemiteTests/Stores/SettingStoreTests.swift
This PR updates the `SiteSettings` logic to now also download + cache the **product** settings values from the API. We were previously only fetching general settings, but now need the product settings so we can display the appropriate weight and length labels on the Product Details screen.
First off, please don't be scared by the diff size here 😄 The bulk of the changes (~1778 lines of 2,062) are the result of new test JSON files, XCode-generated updates to `WooCommerce.xcdatamodeld`, and boilerplate tests. Additionally, this is basically an all-or-nothing kind of change. Let me walk you through everything going on here:
* A new `SiteSettingGroup` enum was added to the models
* `SiteSetting` has a new prop → `SiteSettingGroup` (used to classify a setting...right now it's just product and …
> Product settings fetch

- WooCommerce/Classes/Tools/RequirementsChecker.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/StoreStatsViewController.swift
Just a tiny PR to clean up tracking for stats data loads. In short, if the user is not auth'ed, don't send the tracks events.
Events fired on a clean install, now look like this:
Fixes: #822 
1. In the dev console, filter log activity to 🔵 Tracked
2. Launch a fresh install
3. Verify you don't see anything like this in the console:
```
2019-03-28 14:29:46.365205-0500 WooCommerce[35547:37317216] 🔵 Tracked dashboard_main_stats_loaded, properties: [AnyHashable("granularity"): "day"]
2019-03-28 14:29:46.366467-0500 WooCommerce[35547:37317215] 🔵 Tracked dashboard_main_stats_loaded, properties: [AnyHashable("granularity"): "week"]
2019-03-28 14:29:46.367760-0500 WooCommerce[35547:37317190] 🔵 Tracked dashboard_main_stats_loaded, properties: [AnyHashable("granularity"): "month"]
2019-03-28 …
```
> Don't track stats loaded events if user is not authed

- Storage/Storage.xcodeproj/project.pbxproj
- Storage/Storage/Model/MIGRATIONS.md
- Storage/Storage/Model/ProductVariation+CoreDataClass.swift
- Storage/Storage/Model/ProductVariation+CoreDataProperties.swift
- Storage/Storage/Model/ProductVariationAttribute+CoreDataClass.swift
- Storage/Storage/Model/ProductVariationAttribute+CoreDataProperties.swift
- Storage/Storage/Model/ProductVariationDimensions+CoreDataClass.swift
- Storage/Storage/Model/ProductVariationDimensions+CoreDataProperties.swift
- Storage/Storage/Model/ProductVariationImage+CoreDataClass.swift
- Storage/Storage/Model/ProductVariationImage+CoreDataProperties.swift
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 13.xcdatamodel/contents
- Storage/Storage/Tools/StorageType+Extensions.swift
In this PR, `Storage` support for product variations is added:
Updates here specifically include:
* **updating (the unreleased) Core Data model v13**
* Adding the `ProductVariation`, `ProductVariationAttribute`, `ProductVariationDimensions`, and `ProductVariationImage` `NSMO` subclasses
* Implementing some helper lookup functions in `StorageType+Extensions.swift`
It should be mentioned that I did consider reusing the existing `Product*` entities. However variations & products are different enough that attempting to use a single set of models/entities/etc would most likely cause subtle bugs. So just like our Android brethren, I separated variations out into their own entities.
Partially addresses: #818 
**Note:** If you already have model v13 installed, be sure to completely reset your …
> Product Variations Mark1: Storage Fun!

- Storage/Storage/Tools/StorageType+Extensions.swift
- WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift
- Yosemite/Yosemite/Stores/ProductStore.swift
- Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
This is a quick fix for a situation I overlooked in my last Product Details PR — we need to take into account the `siteID` when upserting/pruning `ProductAttribute`, `ProductDefaultAttribute`, `ProductImage`, `ProductCategory`, and `ProductTag` entities. To do that, this PR updates the `StorageType+Extensions.swift` loaders and `ProductStore`'s `handleProduct*()` funcs accordingly.
Ref: #279 
* Review the updated code
* Verify the unit tests are ✅ 
@mindgraffiti or @ctarda 1st :shipit: wins! 😄
> Product Details: Update ProductStore to handle multiple sites better

- RELEASE-NOTES.txt
- WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
- WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
Just a quick PR to allow tracking numbers to be copied to the pasteboard via long press or right swipe:
1. Build and run the app
2. Tap the Orders tab and open the details for an order that already has shipment tracking data
**Note:** You will not be able to copy the cells ☝️ if the address or tracking number is empty. 😄 
**Extra credit:** Change the current scheme's app language to RTL and test all of that ☝️ again (the swiping directions will be reversed)
/cc @AmandaRiu @kyleaparker 
> Order details: Tracking numbers can now be copied to the pasteboard

- Podfile
- Podfile.lock
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Update WordPressKit and WordPressAuthenticator to release versions ahead of todays release.
Related to https://github.com/wordpress-mobile/WordPress-iOS/pull/11416.
> Update WordPressKit and WordPressAuthenticator to release versions

- Networking/Networking.xcodeproj/project.pbxproj
- Networking/Networking/Model/Product/Product.swift
- Networking/Networking/Model/Product/ProductAttribute.swift
- Networking/Networking/Model/Product/ProductType.swift
- Networking/NetworkingTests/Mapper/ProductMapperTests.swift
- Networking/NetworkingTests/Responses/variation-as-product.json
- Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
This PR allows us to use the product endpoint (aka `ProductRemote.loadProduct()`) to fetch product variations. Without the updates contained in this PR, `ProductMapper` would blow chunks parsing the response JSON due to changes with the `total_sales` type as well as the structure of `ProductAttribute`. 
Please see [the original issue](https://github.com/woocommerce/woocommerce-ios/issues/859) for more details on all this.
Fixes: #859 
For now, just review the code and make sure the unit tests pass. 
😄 
/cc @nbradbury just in case you are interested...
> Fixes ProductMapper errors for variation type products

- WooCommerce/Classes/System/FeatureFlag.swift
- WooCommerce/Classes/ViewRelated/Orders/FulfillViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/ProductListViewController.swift
- WooCommerce/Classes/ViewRelated/Products/ProductDetailsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/ProductDetailsViewController.xib
- WooCommerce/Classes/ViewRelated/Products/ProductLoaderViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
This PR adds the ability to launch the product details modal from either the `FulfillViewController` or `ProductListViewController`:
**Note:** everything in this PR has been feature flagged as `.localDeveloper`!
Fixes: #855 
The new `ProductLoaderViewController` (which is similar to our much-beloved `OrderLoaderViewController`) decouples the Product Detail VC from any specific navigation flow. ProductLoader does the following when launched:
**1.** Displays a fullscreen spinner and temp `Loading Product` nav bar title:
**2.** Asynchronously fetches a `Product` given the passed-in `productID` + `siteID`
**3.** When the product is retrieved, the (new) `ProductDetailsViewController` is instantiated and rendered in place
**4.** If an error occurs while loading the product, an error overlay is …
> Product Details UI Mark1: Adds ProductLoaderVC + ProductDetailsVC

- WooCommerce/Classes/ViewRelated/Orders/OrderStatusListViewController.swift
Fixes #881. Sorry I didn't catch this during the initial review. After taking the data workshop, I'm a bit better at understanding what should be reported and where.
The problem with using the event `.orderDetailOrderStatusEditButtonTapped` is that it should be reserved for that button's action only. What should be reported here is an order status change. Notice that we also needed to report the order status change back to the original settings if the user taps the "Undo" button in the snack bar.
1. Navigate to an Order > Order detail screen. 
2. Tap on the pencil icon in the order status card, so that the order status list will appear.
3. Choose a new order status and save it.
4. In Tracks > Live view, the expected behavior is to report 1 event for …
> Change the type of event firing and the data reported in the OrderStatusListViewController

- WooCommerce/Classes/ViewRelated/Orders/FulfillViewController.swift
Fixes #852 
As discussed in [this comment](https://github.com/woocommerce/woocommerce-ios/issues/852#issuecomment-482308373), the `Add Tracking` button is hidden until we have confirmation that the remote service exists and returns data.
- Added a property to the `FulFillViewController`, initialised to false, that will be reset to true when data sync succeeds.
- Present button only when said property is true
- Navigate to Orders > Select one Order > Order Details
- Kill the network connection
- Tap "Fulfill order"
This should be the result:
As soon as the network returns, the button should be active again:
- Navigate to orders > Select an order > Order details
The button should not be visible:
> Order fulfillment: Hide the `Add Tracking` button until the request to sync tracking succeeds

- .circleci/config.yml
- Networking/Networking.xcodeproj/project.pbxproj
- Networking/Networking/Remote/OrdersRemote.swift
- Networking/Networking/Remote/ProductsRemote.swift
- Networking/Networking/Remote/Remote.swift
- Podfile
- Podfile.lock
- Storage/Storage.xcodeproj/project.pbxproj
- Storage/Storage/Protocols/StorageManagerType.swift
- Storage/Storage/Tools/StorageType+Extensions.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- Yosemite/Yosemite.xcodeproj/project.pbxproj
- Yosemite/Yosemite/Tools/ResultsController.swift
This fixes compatibility with Xcode 10.2 by updating Zendesk and fixing the new Xcode warnings/errors.
Related pull requests and issues:
- CocoaPods update: #867.
- WordPressAutenticator: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/67, https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/68, https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/70
- WordPressKit: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/140
- CircleCI Orb: https://github.com/wordpress-mobile/circleci-orbs/pull/21
- Zendesk SDK: https://github.com/zendesk/zendesk_sdk_ios/issues/480.
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/11381
**Note:** Due to the Zendesk SDK update this breaks compatibility with Xcode 10.1. We should merge this …
> Xcode 10.2 compatibility

- Networking/Networking.xcodeproj/project.pbxproj
- Networking/Networking/Extensions/CodingUserInfoKey+Woo.swift
- Networking/Networking/Mapper/AccountSettingsMapper.swift
- Networking/Networking/Model/AccountSettings.swift
- Networking/Networking/Remote/AccountRemote.swift
- Networking/NetworkingTests/Mapper/AccountSettingsMapperTests.swift
- Networking/NetworkingTests/Remote/AccountSettingsRemoteTests.swift
- Networking/NetworkingTests/Responses/me-settings.json
- Storage/Storage.xcodeproj/project.pbxproj
- Storage/Storage/Model/Account+CoreDataProperties.swift
- Storage/Storage/Model/AccountSettings+CoreDataClass.swift
- Storage/Storage/Model/AccountSettings+CoreDataProperties.swift
- Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 14.xcdatamodel/contents
- Storage/Storage/Tools/StorageType+Extensions.swift
- Yosemite/Yosemite.xcodeproj/project.pbxproj
- Yosemite/Yosemite/Actions/AccountAction.swift
- Yosemite/Yosemite/Model/Model.swift
- Yosemite/Yosemite/Model/Storage/AccountSettings+ReadOnlyConvertible.swift
- Yosemite/Yosemite/Stores/AccountStore.swift
- Yosemite/YosemiteTests/Stores/AccountStoreTests.swift
Closes #574 
Adds Storage, Networking, and basic Yosemite components to support the Tracks opt-out setting to be synced to the app. 
* The `/me/settings` endpoint does contain a few things that `/me` has but the field names aren't identical. I opted for a new data model for the endpoint in case we need to add additional items down the road.
* I've created a new data model to accommodate the new `AccountSettings` entity and decided to not use a relationship to `Account` for now. 
* User ID isn't returned by the `/me/settings` endpoint so I'm stuffing it into the mapper as a parameter like we've done elsewhere.
1. Make sure unit tests run.
2. Make sure upgrading from a previous version succeeds.
> Use and recognize WordPress.com opt out of analytics setting

- Networking/Networking.xcodeproj/xcshareddata/xcschemes/Networking.xcscheme
- Podfile
- Podfile.lock
- Storage/Storage.xcodeproj/xcshareddata/xcschemes/Storage.xcscheme
- WooCommerce/WooCommerce.xcodeproj/xcshareddata/xcschemes/GenerateCredentials.xcscheme
- WooCommerce/WooCommerce.xcodeproj/xcshareddata/xcschemes/WooCommerce.xcscheme
- Yosemite/Yosemite.xcodeproj/xcshareddata/xcschemes/Yosemite.xcscheme
This PR temporarily points to the new WordPressShared pod changes. It will point to the new pod version after it is released. This is Step 1 in updating the main WCiOS project to support Swift 5.
Ref. #819 and Ref. https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/201
- run `bundle exec pod install`
- check project for warnings (Swift 5 notice is expected to be there, no others)
- run unit tests and ensure they pass
- run the app
> Update the WordPress Shared pod

- Networking/Networking/Remote/OrdersRemote.swift
- RELEASE-NOTES.txt
Fixes #916.
_fields must be ordered in the exact manner they appear in a response or the entire API request will fail. 
Follow the Site URL login flow. See 1987084-zen for login details.
> Bugfix: Some users can't load orders

- Networking/Networking/Remote/OrdersRemote.swift
- RELEASE-NOTES.txt
Fixes #916. Original PR: #940.
This PR fixes the issue where some users cannot load orders.
> Patch 1.7.1: Bugfix #916, some users can't load orders

- Networking/Networking/Model/Stats/TopEarnerStatsItem.swift
- RELEASE-NOTES.txt
Fixes #949. Original PR #954.
This PR fixes the bug in Top Performers, where the mapping error causes "Unable to load content" error message.
cc: @astralbodies 
> Patch 1.8.1: Bugfix #949. Top Performers: mapping error causes "Unable to load content" error message 

- Networking/Networking/Requests/JetpackRequest.swift
- RELEASE-NOTES.txt
Fixes #951.
Store Picker: some users are unable to continue after logging in. (They log in successfully, they have a Store, but the continue button is disabled and an error displays to the user.) Some users are able to get logged in and continue, but are unable to load orders.
Occasionally we come across users who have WC 3.5+, Jetpack properly connected, and know their WordPress.com logins. I would look into the issue, find nothing, and mark it as an edge case. Until I encountered the third user this was happening to, and realized their Jetpack version was old.
Some sites were unable to log in because the `SiteAPIRemote` request was malformed and returning a cryptic error response. 
Example of the malformed API request: 
```
https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/{{site_ …
```
> Bug Fix: malformed Jetpack API request URLs.

- WooCommerce/Classes/ViewModels/ManualTrackingViewModel.swift
- WooCommerce/Classes/ViewRelated/Orders/ShipmentProvidersViewController.swift
- WooCommerce/WooCommerceTests/Model/AddManualCustomTrackingViewModelTests.swift
Implements #890 
When users select a custom shipment provider in the list of providers, we'd pre-populate the provider name with the search term introduced by users when filtering the list (if the list was filtered)
- Added an optional parameter to the view model backing the "add tracking" screen (`AddCustomTrackingViewModel`) to provide an initial value to the provider name
- Run the tests
- Navigate to the fulfill order screen
- Tap Add tracking
- Tap the provider name, select Custom Provider in the list of providers
- Tap the provider name, filter the list of providers. Tap Custom Provider, notice the name is pre-populated with the search term.
> Order fulfillment: Pre-populate custom provider name with search term

- WooCommerce/Classes/ViewRelated/Orders/ShipmentProvidersViewController.swift
Fixes #963 
Pop the navigation controller when users select a tracking provider, as mentioned in [this Android issue](https://github.com/woocommerce/woocommerce-android/pull/1054#issuecomment-492285336) 
- Pop the navigation controller on selection
- Navigate to an order > Fulfill order > Add tracking
- Tap the "Shipping Provider" cell in the "add tracking form"
- Select a provider. The UI should navigate back to the "add tracking form"
> Order fulfillment: Pop the list of shipment providers when selecting one

- RELEASE-NOTES.txt
- WooCommerce/Classes/Yosemite/StoresManager.swift
Fixes #878 
I grabbed this ticket because it seems to be [appearing in the logs](https://github.com/woocommerce/woocommerce-ios/issues/878#issuecomment-492248040)
The crash happens at `StoresManager.needsDefaultStore`, with this message:
`Thread 1: Simultaneous accesses to <MEMORY_ADDRESS>, but modification requires exclusive access`
Digging in the Debug navigator, I can see that happening because `OrdersViewController.defaultAccountWasUpdated` starts a read right after `StoresManager.synchronizeAccount` starts a modification triggered by `AccountStore.synchronizeAccount`
- Lock read/write access to sessionManager via a DispatchQueue.
- Which requires adding a property to actually retain he reference to `SessionManager` and turn the old `sessionManager` property into a calculated one.
- …
> Fix Crash on StoresManager.needsDefaultStore

- WooCommerce/Classes/ViewRelated/Orders/ManualTrackingViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/ManualTrackingViewController.xib
- WooCommerce/Classes/ViewRelated/ReusableViews/DatePickerTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/DatePickerTableViewCell.xib
Fixes #965 
Fix issues with the UI to add shipment trackings [mentioned during the review](https://github.com/woocommerce/woocommerce-ios/pull/964#pullrequestreview-237555521) of PR #964 
Before and after:
<image src="https://user-images.githubusercontent.com/2722505/57755945-b9213500-7724-11e9-8c15-571dfc7c2f96.jpg" width = "800"/>
When the date picker is visible:
<image src="https://user-images.githubusercontent.com/2722505/57756000-e2da5c00-7724-11e9-854f-0c28e187f816.png" width = "600"/>
- Set the table style as plain instead of grouped.
- Manually set the cell inset to .zero for the date cell. Add a bottom border to the picker cell
- Select an Order > Fulfill > Add Tracking
- Notice the bottom cell.
> Add Tracking view: UI fixes

- WooCommerce/Classes/Extensions/UIImage+Woo.swift
- WooCommerce/Classes/ViewModels/OrderDetailsViewModel.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTrackingTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTrackingTableViewCell.xib
- WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
- WooCommerce/WooCommerceTests/ViewRelated/OrderTrackingTableViewCellTests.swift
Fixes #876 
- Updated `OrderTrackingTableViewCell` to remove the "track" button and a separator
- Updated `OrderDetailsViewController` to present an alert sheet and to add the delete action
- Checkout the branch, run the tests
- Navigate to an order with shipment trackings (`OrderDetailsViewController`)
- Tap one of the trackings. Tap the Delete Tracking and Track Shipment buttons and check that they work as expected
**Note**: When presenting the sheet in the simulator, on iPhone, there will be an Autolayout error:
```
2019-05-14 09:14:16.959312+0800 WooCommerce[12158:259530] [LayoutConstraints] Unable to simultaneously satisfy constraints.
Probably at least one of the constraints in the following list is one you don't want. 
Try this: 
(1) look at each constraint and try to figure out …
```
> Order details screen: add option to delete shipment tracking

- WooCommerce/Classes/ViewRelated/Orders/FulfillViewController.swift
Fixes #922 
- Trigger the sync of trackings on `viewDidAppear` instead of `viewWillAppear`
- Build and run on the simulator. 
- Navigate to an order in Processing status
- Activate the slow animations in the simulator (Command+T)
- Tap the Fulfill Order button
- Check that the Add Tracking button is not displayed until after the transition animation has been completed
>  Fulfillment: Add Tracking row appears during view transition animation

- WooCommerce/Classes/ViewRelated/Orders/FulfillViewController.swift
Fixes #926 
Adjust the space between the cells containing shipment trackings and the "Add Tracking" button.
Before and after:
- Pass a `nil` instead of an empty string as title of the section containing the "Add Tracking" button when there are more than zero shipment trackings
- Return a nil header when the section does have a nil or an empty title.
> Adjust space between trackings and "add tracking" button

- WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
- WooCommerce/Classes/ViewRelated/Orders/FulfillViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/ManualTrackingViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/ShipmentProvidersViewController.swift
Closes #967 
This PR renames some Tracks events, and adds a few.
Events renamed:
| Old event name | New event name |
| -------------- | -------------- |
| *_order_fulfillment_tracking_carrier_selected | *_order_shipment_tracking_carrier_selected |
| *_order_tracking_failed | *_order_tracking_add_failed |
| *_order_tracking_success | *_order_tracking_add_success |
New events added:
```
*_order_tracking_delete
*_order_tracking_delete_failed
*_order_tracking_delete_success
*_order_shipment_tracking_add_button_tapped
*_order_shipment_tracking_custom_provider_selected
```
- Updated `WooAnanlyticsStat`
- Added events to `FullfillViewController`, `OrderDetailsViewController`,  `ManualTrackingViewController` and `ShipmentProvidersViewController`
1. Run the branch and navigate to an order > …
> Order fulfillment: rename Tracks events for manual tracking

- RELEASE-NOTES.txt
- WooCommerce/Classes/System/FeatureFlag.swift
- WooCommerce/Classes/ViewRelated/Orders/FulfillViewController.swift
Fixes #862 
This PR might be a bit premature, but as far as I know there is no new work left for manual shipment tracking, and this PR could be merged at any time whenever we decide this feature is ready for release, so here it is! 
I am opening this PR as a draft, will upgrade it to a full PR when PRs #959 and #960 are merged.
- Removed the feature flag
- Updated the release notes
- Checkout the branch, make sure it builds, tests pass and the feature is available on the simulator
- Build on a device, and check that the feature is available
To check that the feature is available, log in to a store that has the [Shipment Tracking Extension](http://woocommerce.com/products/shipment-tracking/?_ga=2.213023133.823373140.1557804345-403441387.1556787590) installed, navigate to an order in …
>  Order fulfillment: remove feature flag for manual shipment tracking

- Networking/Networking.xcodeproj/project.pbxproj
- Networking/Networking/Extensions/KeyedDecodingContainer+Woo.swift
- Networking/Networking/Model/Product/Product.swift
- Networking/Networking/Model/Product/ProductStatus.swift
- WooCommerce/Classes/Extensions/UILabel+Helpers.swift
- WooCommerce/Classes/Styles/Style.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/Privacy/PrivacySettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Cells/ProductReviewsTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Products/Cells/ProductReviewsTableViewCell.xib
- WooCommerce/Classes/ViewRelated/Products/ProductDetailsViewController.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/LargeImageTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/LargeImageTableViewCell.xib
- WooCommerce/Classes/ViewRelated/ReusableViews/TwoColumnTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/TwoColumnTableViewCell.xib
- WooCommerce/Classes/ViewRelated/ReusableViews/WooBasicTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/WooBasicTableViewCell.xib
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Closes #856.
This PR displays basic information in the first section of the Product Details screen. Depending on if the product type is Grouped, Affiliate, Variable, or Basic, it will display an image, a title, total orders, review stats, and external link(s).
Since affiliate products aren't purchased directly through a user's store, I can't currently show a screenshot of this type of product in the app. It can be tested by overriding the code.
Hi-res still image:
Animated gif:
Example of what the Status Badge will look like. (Ignore that it says "Publish" and imagine it says "Private" or "Draft".)
- navigate to an order 
- fulfill the order
- select the product row
- wait for the product details view controller to load
- observe new rows (varies based on product type)
@kyleaparker some …
> Product Details: Basic information

- WooCommerce/Classes/ViewModels/ShippingProvidersViewModel.swift
- WooCommerce/Classes/ViewRelated/Orders/ShipmentProvidersViewController.swift
Fixes #984 
This PR is against `release/1.9`, not `develop`, as it was raised as part of [the call for testing for 1.9](https://wp.me/p5T066-RX-p2).
As reported in issue #984 , text typed in the search field of the list of shipment tracking providers was not filtering the providers in the section for the country associated to the store.
- Filter the section associated to the store country by the text entered in the search field
- For extra credit, fix the table view offset when the keyboard is dismissed.
- Navigate to the list of providers, enter text in the search field, notice it filters also the providers associated to the store country, if available.
- For stores associated to countries that do not have shipment providers, filters should work on all countries.
> Fix filters for list of shipment tracking providers

- WooCommerce/Classes/ViewRelated/Orders/FulfillViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
Closes #982 
Add a `source` entry to the dictionary submitted to Tracks along with the tracking deletion events, as discussed in [this thread](https://wp.me/p99K0U-1eo-p2)
- Checkout the branch. 
- Delete a shipment tracking from the Order Details screen. Check that the Tracks event `order_tracking_delete` contains a property `source` with value `order_detail`
- Delete a shipment tracking from the Fulfill Order screen. Check that the Tracks event `order_tracking_delete` contains a property `source` with value `order_fulfill`
The spreadsheet is updated.
> Add source to event sent when deleting shipment trackings

- WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
Fixes #990 
As pointed out in #990, the Tracking section was shown right after Products, when it should be displayed right after Payments.
This PR is against the `release/1.9` branch
Before and after:
- Update the order of the table view sections. The new order is, from top to bottom: `summary, products, customerNote, customerInformation, payment, tracking, notes`
- Checkout the branch, navigate to an order that contains shipment trackings. Note the placement of the "Trackings" section
- Move the Tracking section in the Order Details screen below the Payment section
> Change order of sections in Order Details screen

- WooCommerce/Classes/ViewModels/ShippingProvidersViewModel.swift
Fix #991 
The "Custom" section should be second in the list, after the "store country" section.
This PR is against the `release/1.9` branch
Before and after for a store in the United States:
- Updated the view model to change the index of the custom and store country sections
- Updated some more methods in the view model to account for the fact that now the first section can be either the store country or the custom provider
- Fix a bug in the ordering of the list of shipment tracking providers
> Switch order of custom provider and store country sections in list of tracking providers

- Storage/Storage/Model/PreselectedProvider.swift
- WooCommerce/Classes/ViewModels/ManualTrackingViewModel.swift
- Yosemite/Yosemite.xcodeproj/project.pbxproj
- Yosemite/Yosemite/Actions/AppSettingsAction.swift
- Yosemite/Yosemite/Stores/AppSettingsStore.swift
- Yosemite/YosemiteTests/Mockups/custom-shipment-provider.plist
- Yosemite/YosemiteTests/Stores/AppSettingsStoreTests.swift
Fixes #945 
This PR is against the `release/1.9` branch
We are pre-populating the name o the provider for "regular" providers already, so this PR adds the same functionality to custom providers (also, for consistency with Android)
- Added domain methods to the `AppSettingsStore`
- Added tests to cover the new methods
- Save and read from `AddCustomTrackingViewModel`
- Add regular and custom trackings to an order. 
- Check that the name is pre-populated with the last choice for both regular and custom tracking providers
- The plist files should be cleared on log out
- The name of the shipment tracking provider is pre-populated with the latest name used also for custom providers
> Order Fulfillment: pre-populate custom tracking provider name with last name entered by the user

- Networking/NetworkingTests/Extensions/DateFormatterWooTests.swift
- Networking/NetworkingTests/Mapper/NoteListMapperTests.swift
- Networking/NetworkingTests/Responses/notifications-load-all.json
Fixes #1001 
I am sorry PR 1000 is so mundane (and hacky) but this is a little annoyance that I have been wanting to look into for a few weeks. Also, I labelled it as Tooling for lack of a better tag.
Three tests are failing for me when running them in my machine in the afternoon of the HK timezone.
- Modified the string representation of two mocked strings in the tests to make the tests pass on my machine.
- Checkout the branch and run the tests. Hopefully they will pass for you as well.
- Check that the PR builds on CI.
> Make three tests failing in HK pass

- WooCommerce/WooCommerceTests/Tools/AppRatingManagerTests.swift
Closes #939 
This one took me forever to figure out. It turns out that the tests for the `AppRatingManager` where clearing the standard user defaults, which in turn, I presume, would make the next run of the app consider itself as logged out, because `SessionManager` would always return nil as defaultAccountID.
- Changed a little bit the way the AppRatingManagerTests are setup, passing an instance of UserDefaults that is not the standard, and making sure that defaults are cleared after each test in `tearDown`
- Checkout the branch, build the app in the simulator, log in and make sure to stay logged in.
- Stop the app, and run the tests (command + U)
- Nor build and run the app again (command + R). Notice if the app remains logged in.
> Prevent tests for AppRatingManager from logging out inadvertedly

- WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
- WooCommerce/Classes/ViewRelated/Orders/ShipmentProvidersViewController.swift
Closes #1013 
Submit the `order_tracking_providers_loaded` when loading the list of shipment providers from the API.
The PR is against `develop` as it does not seem like a blocker, but if we wanted to get this in the 2.0  release we could just change the base branch.
- Added the event to the `WooAnalyticsStat` enumeration
- Submitted the event in `ShipmentProvidersViewController`
- Navigate to an Order > Filfill > Add Tracking > Tap the tracking provider cell to navigate to the list of providers
- The following event should be logged in the console and submitted to Tracks:
```
2019-06-05 13:45:02.235586+0800 WooCommerce[19351:16168798] 🔵 Tracked order_tracking_providers_loaded, properties: [AnyHashable("is_wpcom_store"): true, AnyHashable("blog_id"): XXXXXXX]
```
> Submit tracks event when loading list of shipment providers from the API

- WooCommerce/Classes/Extensions/String+Helpers.swift
- WooCommerce/Classes/ViewModels/ProductDetailsViewModel.swift
- WooCommerce/Classes/ViewRelated/Fancy Alerts/FancyAlertController+PurchaseNote.swift
- WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/ProductDetailsViewController.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/ReadMoreTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/ReadMoreTableViewCell.xib
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Closes #858.
This PR adds the Purchase note to Purchase Details if it exists. Previous PR #1009 contains screenshots for shipping detail and download cells.
A short purchase note
A long purchase note
- Check out and build this branch
- Go to your testing store's website
- Navigate to a product and add a product note (it's in the "Advanced" tab on the left)
- Update the product
- Create an order with that product
- Go back to the app and navigate to the product details view: Orders > Order Number > Fulfill order > Product list 
- Select product in the list
- Scroll to the bottom to see the purchase details information
- Select the "read more" button
- a fancy alert with the full text should appear, with a "dismiss" button at the bottom of the alert
> Purchase Details Mark II: Purchase Note cell

- WooCommerce/Classes/ViewModels/ProductDetailsViewModel.swift
Fixes #1017.
Bug fix screenshot:
1. Check out this PR
2. On your test site, find a product that doesn't have an image and the status is "Published"
3. On your test site, order the product
4. On the app, navigate to the product by going to Orders > Order number > select the product in the details view.
5. The Product Details view should have no space between the navigation bar and the product Title cell.
> Product Details: bug fix for product image

- WooCommerce/Classes/ViewRelated/Orders/Views/ShowHideSectionFooter.swift
- WooCommerce/Classes/ViewRelated/Orders/Views/ShowHideSectionFooter.xib
Fixes #989 
Center the "Show Billing" button in the Order Details screen to the text + icon, instead of to the text only
Before and after
I have noticed that expanding and collapsing the billing section triggers an autolayout error in the section headers, independently of the changes in this pull request. I have logged an issue for it: #1021 
- In `ShowHideSectionFooter`, embed the label and icon  in a stack view
- Make the class final and extract a couple of methods (completely unnecessary, but 🤷‍♂ )
- Checkout the branch
- Navigate to an Order Details screen
- Notice the placement of the "Show billing" button
> Order details: Center “Show billing” and icon horizontally

- Podfile
- Podfile.lock
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
Fix #1026 
Bump Charts to 3.3.0. The bump brings a breaking change that requires an update to the name of a parameter in an initialiser.
- Update the pod version
- Update the name of a parameter
- Clear all the things, specially derived data
- run `bundle exec pod install`
- Build and run. Check that stats still render
> Bump Charts to 3.2.0

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/StoreStatsViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformersViewController.swift
Fixes #800 
The fix in Arabic (red rectangles added to emphasise the areas changed):
The fix in pseudo-rtf language:
The solution implemented, no matter how tacky it can be, follows [our own recommendations for WordPress iOS](https://github.com/wordpress-mobile/WordPress-iOS/wiki/Right-to-Left-layout-support-guideline#be-careful-with-horizontal-scroll-views). In a nutshell, we flip the view that renders the tabs, and then flip back the individual labels.
In this particular case, I don't think we can actually do much more than what we are doing here. The tabs are a collection view created by the third party library we are using to render the charts, so until we contribute a long term solution to that library, we might need to go with this.
- Updated `StoreStatsViewController`and …
> Stats: Tabs are ordered backwards in RTL languages

- WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift
- WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
Fixes #767 
Present the store switcher modally when initiated from the app settings.
- Modify StorePickerCoordinator to present modally instead of pushing into a navigation controller for the `.switchingStores` configuration
- Remove the disclose indicator from the cell in Settings
- Switch stores. Check that the store switcher can be dismissed and that it actually works
- Check other instances of the store switcher to make sure that nothing else is broken.
Note: I did not add any release notes as this seemed like something not worth mentioning, but I'll be happy to add a line if we think it's worth it.
> Settings: Update the store switcher presentation to be a modal overlay

- Networking/Networking/Remote/ProductsRemote.swift
- WooCommerce/Classes/Extensions/Array+Helpers.swift
- WooCommerce/Classes/ViewModels/OrderItemViewModel.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/ProductDetailsTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Fulfillment/Cells/PickListTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Fulfillment/FulfillViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrderLoaderViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/ProductListViewController.swift
- Yosemite/Yosemite.xcodeproj/project.pbxproj
- Yosemite/Yosemite/Actions/ProductAction.swift
- Yosemite/Yosemite/Internal/Array+Helpers.swift
- Yosemite/Yosemite/Stores/OrderStore.swift
- Yosemite/Yosemite/Stores/ProductStore.swift
Closes #747.
This PR displays product images if / when an imageURL is available.
When a user navigates to an Order Details screen:
1.  An array of productIDs is created by looking for Order.orderItem.productID
2. syncProducts checks for existing Products, looking them up by the productID in the array
3. If no product is found in ProductStore, the productID is placed in the missingIDs array
4. A remote request is made (a **single** API request for all products in that order) for the missing products
5. If the request was successful, the products are upserted on a background thread
6. the productFetchedResultsController listener is notified that changes have occurred
7. the productFetchedResultsController event handlers then trigger a reloadTableViewSectionsAndData
8. the tableview …
> Download product images and display them everywhere

- Podfile
- Podfile.lock
Fixes #1025 
Bumping the dependency to improve support for dynamic type in login flow. 
As mentioned in the comments to [this thread](https://wp.me/p5T066-S0-p2) there are parts of WordPressAuthenticator that were not providing great support for dynamic type. 
I've presumed it does not hurt to update our dependencies to the latest and greatest, specially if those dependencies are with libraries developed in house.
- Updated WordPressAuthenticator to 1.5.2, and the rest of the internal dependencies to match the required dependency graph.
- Pinned Charts to 3.2.0 (as 3.3.0 includes a breaking change). Follow up: #1026 
- Checkout branch
- Remove the contents of the Pod folder, and run `bundle exec pod install`
- Build the project and run the tests
- Log out and then back in. Make sure all …
> Bump WordPressAuthenticator to 1.5.2

- WooCommerce/Classes/Authentication/Epilogue/StoreTableViewCell.swift
- WooCommerce/Classes/Extensions/UIImage+Woo.swift
- WooCommerce/Classes/ViewModels/OrderDetailsViewModel.swift
- WooCommerce/Classes/ViewModels/ProductDetailsViewModel.swift
- WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/Privacy/PrivacySettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteDetailsCommentTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Notifications/NotificationDetailsViewController.swift
- WooCommerce/Classes/ViewRelated/Notifications/NotificationsViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/CustomerNoteTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderNoteTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/ProductDetailsTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Fulfillment/Cells/PickListTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/NewNoteViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Cells/ProductReviewsTableViewCell.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Fixes #746 
Encapsulate all access to GridIcons in the UIImage+Woo extension. Considering the announcements at WWDC, this seemed like the right moment to do this 😄 
- Added vars to the images extension, and reordered the existing ones in alphabetical order (sorry about that 😊 )
- Added tests to ensure the integrity of the dependency
- Checkout the branch, run the tests. The tests should pass
- Search the codebase for `Gridicon.iconOfType`. All occurrences should be only in `UIImage+Woo` (and a few results in Pods, out of the scope of this story)
- Navigate around, check that icons are still rendered and that I haven't messed up anything
> Gridicons: All gridicons should be stored in the `UIImage+Woo` extension

- RELEASE-NOTES.txt
- WooCommerce/Classes/System/FeatureFlag.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/ProductDetailsTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Fulfillment/Cells/PickListTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Fulfillment/FulfillViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/ProductListViewController.swift
Time to release Products to the public!
- Navigate to Orders > choose an order that's processing. (It's not perfect, but you should see some images download.)
- Refresh the Order details screen. A few more images should load.
- Choose a product that hasn't loaded the image yet.
- Tap on that product. Wait for the image to load. Dismiss the product details screen.
- Since the image downloaded from product details, it should appear in the Order details screen.
- Navigate to fulfill an order. Notice that this isn't a pull-to-refresh screen. It takes the data from Order details and repackages it.
- Back out of the processing order. Choose an order that's completed.
- Tap on a product to verify the product details screen is presented and loads well.
- Dismiss the product details screen. Tap on …
> Remove feature flag for products

- WooCommerce/Classes/Tools/Developer/DeveloperEmailChecker.swift
- WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/HelpAndSupportViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Tools/DeveloperEmailCheckerTests.swift
Fixes #921
Since developers cannot send support tickets in the app, there are two places in Help/Support where we want to show warning for developer with an @automattic.com or @a8c.com email address.
- When the Support view is initially shown (already implemented before this PR)
- When the user changes their email via Contact Email (implemented in this PR)
- Updated `getUserInformationAndShowPrompt` completion block to the new completion type: `UserInformationCompletion = (_ success: Bool, _ email: String?) -> Void` so that email is available for upstream completion handler (`HelpAndSupportViewController`) to show warning if the email is a developer email
- Created `DeveloperEmailChecker` to check if an email has @automattic.com or @a8c.com domain + basic tests
Prerequisites: if the …
> Zendesk: show alert if email is a8c.com/automattic.com

- WooCommerce/Classes/ViewRelated/ReusableViews/EmptyListMessageWithActionView.xib
Fixes #908 
- Removed constraint that sets 48px height to action button (setting constant height is discouraged as its content could have dynamic height)
- Set action message label's `verticalCompressionResistancePriority` to `default low` so that its content height is at a lower priority than others. Out of the two UI elements on this message+action view, I think it's more important to show the full text of the action button than that of the message label (but lemme know there is a better design like shrinking text down to a min font size)
- Set action button label to have any number of lines
- Miscellaneous IB diffs from previous updates
- Launch the app with a store that has at least one order
- Go to 'Orders' tab
- Click on an order
- Click on 'Fulfill Order'
- Scroll down to '+ Add …
> Custom shipping provider: fix clipped action button text when no shipping provider search results

- WooCommerce/Classes/Extensions/UIButton+Helpers.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/OverlayMessageView.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/OverlayMessageView.xib
Fixes #909 
- Added `UIButton` helper `enableMultipleLines` to support button title of multiple lines, either from explicit line breaks (like `\n`) or longer text than allocated width. Applied this helper to action button in `OverlayMessageView`
- Center aligned action button title in `OverlayMessageView`
- Added an AutoLayout constraint for action button to have <= 90% width of `OverlayMessageView` (lemme know if there's a padding style convention that we use) 
Prerequisites: log in to a store without notifications.
- Go to Notifications tab
- Turn on dynamic type (device Settings > General > Accessibility > Larger Text > turn it on) and adjust the device to different font sizes via the slider, and observe "Share your Store" button on Notifications tab --> The button should not be …
> Notifications: support multiple lines of Share Store button in case of large text

- WooCommerce/Classes/Extensions/UITableView+FooterHelpers.swift
- WooCommerce/Classes/Extensions/UIViewController+TableViewHelpers.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/TableFooterView.xib
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Fixes #910 
- Added a `UIViewController` extension to update height for table footer view. With a frame-based container view as `tableView.tableFooterView`, an Auto Layout based subview does not trigger its parent frame based view to update its height. From my experiments, it is necessary to calculate the table footer view height in view controller's `viewDidLayoutSubviews`, update the height and reassign the footer view if the new height is different
- Added an Auto Layout constraint to pin the footnote label's bottom to the footer view's bottom safe area with 20 spacing. Without this constraint, the calculated height for the footer view would be 0 as there is no constraint at the bottom
- Launch the app with a store
- On "My store" tab, tap the Settings icon on the top right
- Scroll to …
> Settings: fix footer covered for larger font sizes

- WooCommerce/Classes/ViewRelated/Orders/Cells/EditableOrderTrackingTableViewCell.swift
Fixes #905 
- Enabled any number of lines for the bottom line label to show full shipment date
- Launch the app with a store that has at least one order with shipment tracking
- On "Orders" tab, tap on an Order with shipment tracking
- On the Order page, tap "Fulfill order" button
- Scroll to the section with shipment information
- Turn on dynamic type (device Settings > General > Accessibility > Larger Text > turn it on) and adjust the device to different font sizes via the slider, and observe the shipment date --> The date should not be truncated at any font size
before | after
--- | ---
> Fulfill Order: fix shipment date clipped for larger font sizes

- WooCommerce/Classes/Extensions/UIButton+Helpers.swift
- WooCommerce/Classes/ViewRelated/Orders/Fulfillment/FulfillViewController.swift
Fixes #907  
- Enabled any number of lines for primary button style
- Added frame based container view for Auto Layout based action view as table footer view, and updated table footer height in view controller's `viewDidLayoutSubviews`
- Launch the app with a store that has at least one order not fulfilled yet
- On "Orders" tab, tap on an open Order
- On the Order page, tap "Fulfill order" button
- Scroll to the bottom where the footer is with `Mark as complete`
- Turn on dynamic type (device Settings > General > Accessibility > Larger Text > turn it on) and adjust the device to different font sizes via the slider, and observe the footer view --> The button should have 64px margin to the bottom with full title shown
before | after
--- | ---
> Fulfill Order: fix "Mark as complete" button title truncated for larger font sizes

- WooCommerce/Classes/ViewRelated/Orders/Cells/EditableOrderTrackingTableViewCell.swift
Fixes #1058  
- Enabled any number of lines for the top line label to show the full shipping provider
- Enabled any number of lines for the middle line label to show the full shipment tracking number
- Launch the app with a store that has at least one order with shipment tracking
- On "Orders" tab, tap on an Order with shipment tracking
- On the Order page, tap "Fulfill order" button
- Scroll to the section with shipment information
- Turn on dynamic type (device Settings > General > Accessibility > Larger Text > turn it on) and adjust the device to different font sizes via the slider, and observe the shipping provider and shipment tracking number --> Both labels should not be truncated at any font size
before | after
--- | ---
> Fulfill order: allow any number of lines for shipping provider and tracking number

- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTrackingTableViewCell.swift
Fixes #1072 
- Allowed any number of lines for the top (shipping provider) and bottom (shipment date) labels in `OrderTrackingTableViewCell`.
- Launch the app with a store that has at least one order with shipment tracking information
- On "Orders" tab, tap on an Order
- On the Order details page, scroll to "TRACKING" section
- Turn on dynamic type (device Settings > General > Accessibility > Larger Text > turn it on) and adjust the device to different font sizes via the slider, and observe the shipping provider and shipment date --> both labels should not be truncated
before | after
--- | ---
> Order Details > Shipment Tracking: fix provider name and shipment date truncated when using larger font sizes

- WooCommerce/Classes/Styles/PaddedLabel.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.xib
Fixes #900 
Fixes #901 
- Allowed any number of lines for payment status label
- After a few trials and errors, this [SO answer](https://stackoverflow.com/a/21267507) fixed the issue. First, with just `label.numberOfLines = 0` more of the text is shown but still truncated at the end. When I updated the `textInsets` to all 0s, the text is fully shown without insets as expected. Reading some other similar SO posts, I think the issue is that with `intrinsicContentSize` it doesn't know where to draw the text. [`textRect(forBounds bounds: CGRect, limitedToNumberOfLines numberOfLines: Int)`](https://developer.apple.com/documentation/uikit/uilabel/1620545-textrect) seems to be the method for that
- Since the fix in pass 1 is quite hacky and no official backup, and after checking Apple Wallet and …
> Order list: fix truncated payment status label for large font sizes

- Storage/Storage.xcodeproj/project.pbxproj
- Storage/Storage/Model/MIGRATIONS.md
- Storage/Storage/Model/OrderStatsV4+CoreDataClass.swift
- Storage/Storage/Model/OrderStatsV4+CoreDataProperties.swift
- Storage/Storage/Model/OrderStatsV4Interval+CoreDataClass.swift
- Storage/Storage/Model/OrderStatsV4Interval+CoreDataProperties.swift
- Storage/Storage/Model/OrderStatsV4Totals+CoreDataClass.swift
- Storage/Storage/Model/OrderStatsV4Totals+CoreDataProperties.swift
- Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 17.xcdatamodel/contents
- Storage/Storage/Tools/StorageType+Extensions.swift
- WooCommerce.xcworkspace/contents.xcworkspacedata
Fixes #1065 
Submitting as a draft PR, as it depends on PR #1082 to be reviewed and merged.
This PR adds stats V4 support to model v 17:
- New model version, with new entities.
- Generated subclasses
- Added a convenience method to the core data extensions
- Checkout the branch, build and run the app, verify there are no coredata migration errors
- Run the test, verify they are ✅
> Stats: add to the Storage layer for new stats

- WooCommerce/Classes/ViewRelated/Orders/OrderSearchViewController.swift
Fixes #1062 
- Enabled any number of lines for the order list search empty state label. Also, allowed the label to adjust font size with Dynamic Type.
- Launch the app with a store that has at least one order
- On "Orders" tab, tap on the search icon in the navigation bar
- In the search bar, type some query that has no search results
- Turn on dynamic type (device Settings > General > Accessibility > Larger Text > turn it on) and adjust the device to different font sizes via the slider, and observe the no results text as in the screenshot below
before | after
--- | ---
> Order list search: fix no results text clipped with larger font sizes

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Orders/OrderDetailsViewController.swift
Fixes #1073 
- Added "Copy Tracking Number" to shipment tracking action sheet, and send the tracking number to pasteboard on tap.
- Launch the app with a store that has at least one order with shipment tracking information
- On "Orders" tab, tap on an Order with shipment tracking
- On the Order details page, scroll to "TRACKING" section
- Tap on "..."
- Tap "Copy Tracking Number" --> the tracking number should be copied to the pasteboard
(I wish iOS has some feedback on text copied - like "Copied!" flash message)
> Order Details > Shipment Tracking: add "Copy Tracking Number" to "more" action menu

- Gemfile.lock
- fastlane/Fastfile
- fastlane/Pluginfile
- fastlane/env.example
This PR replaces Fabric with Sentry in `Fastfile`.
1. Run `bundle install`.
2. Add the `SENTRY_AUTH_TOKEN=` entry to your `~/.wcios-env-default`.
2. Update the version name in `Version.Public.xcconfig` to something not used in production (change the last number, or add another .0, or something like that).
3. Run `bundle exec fastlane build_and_upload_itc` and verify that the dSYM is uploaded to Sentry.
> Automatic dSYM upload to Sentry

- RELEASE-NOTES.txt
Fixes #1073 
Since https://github.com/woocommerce/woocommerce-ios/pull/1086 was originally intended for 2.3 but later merged to sprint 2.4, this PR moved the feature from 2.3 to 2.4 in release notes.
> Release notes: move "copy tracking number" feature from release 2.3 to 2.4

- docs/STORAGE.md
- docs/YOSEMITE.md
Fixes #1111 
Now that the documentation has been moved to the docs folder, it is time to give it some more love. Starting with...
- Update Storage.md to mention the preferred way to handle local files via the `FileStorage` protocol
- Update Yosemite.md to reference the `AppSettingsStore`
> Update Storage.md and Yosemite.md

- WooCommerce/Classes/ViewModels/OrderDetailsViewModel/OrderDetailsDataSource.swift
- WooCommerce/Classes/ViewModels/OrderDetailsViewModel/OrderPaymentDetailsViewModel.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/PaymentTableViewCell.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/OrderPaymentDetailsViewModelTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/PaymentTableViewCellTests.swift
Fixes #1116 
As [mentioned in the review](https://github.com/woocommerce/woocommerce-ios/pull/1077#discussion_r304399578) of PR #1077, there is a significant amount of code in OrderDetailsDataSource that configures and populates cells, in particular `PaymentTableViewCell`
Before:
And after:
- Add a `OrderPaymentDetailsViewModel` that encapsulates the data that is necessary to render the `PaymentTableViewCell`
- Unit tests
- Run the tests, check that they are ✅ 
- Check that there are no changes to the way payment details are rendered.
>  Extract viewmodel to configure PaymentTableViewCell

- RELEASE-NOTES.txt
- WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
- WooCommerce/Classes/Extensions/UIButton+Helpers.swift
- WooCommerce/Classes/Styles/Style.swift
- WooCommerce/Classes/Tools/WebviewHelper.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/About/AboutViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/TableFooterView.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/TableFooterView.xib
Closes #1083. 
In this PR we're promoting hiring within the apps! 
- Check out the PR branch
- Run the app
- Tap the My store "gear" icon to find the Settings page.
- Scroll to the bottom. Ensure the footer looks like the design mock.
- Tap the "We're hiring!" link. Expected behavior: a Safari web viewer is presented as a modal view in the app, with a "done" button to dismiss it. If it pops out of the app, that's a bug.
> Update the Settings footer to promote hiring

- WooCommerce/Classes/Analytics/MockupAnalyticsProvider.swift
- WooCommerce/Classes/Analytics/WooAnalytics.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/OrderDetailsViewModelTests.swift
Fixes #1135 
Initialise the WooAnalytics singleton injecting a mock implementation of AnalyticsProvider when running as a unit test.
- Update to the `shared` method in WooAnalytics
- Added one unit test to prove that the system works.
- Checkout the branch, run the tests
> Inject mock AnalyticsProvider for unit tests

- RELEASE-NOTES.txt
- WooCommerce/Classes/Extensions/UIImage+Woo.swift
- WooCommerce/Classes/ViewRelated/MainTabBarController.swift
- WooCommerce/Classes/ViewRelated/Notifications/NotificationsViewController.swift
- WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Fixes #1151 
Change the Notifications Tab to Reviews.
In action:
*Note* To keep the diff as small as possible, I have not renamed the NotificationsViewController. If / when we get this PR to a point where is mergeable, I would rename it too ReviewsViewController.
- Renamed Notifications tab to Reviews.
- Removed dynamic filters from the view controller, including the right toolbar button
- Check that the name of the Notifications tab item has changed to Reviews. 
- Check that the title of Reviews tab has changed to Reviews
- Leave a review in the store. Check that it is presented in the Reviews tab
- Check that the Reviews tab contains only reviews
- Try to display the empty state placeholder. Check that there are no other references to Notifications
> Rename Notifications to Reviews

- Storage/Storage.xcodeproj/project.pbxproj
- Storage/Storage/Model/MIGRATIONS.md
- Storage/Storage/Model/OrderStatsV4+CoreDataProperties.swift
- Storage/Storage/Model/OrderStatsV4Totals+CoreDataProperties.swift
- Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 19.xcdatamodel/contents
- Storage/Storage/Tools/StorageType+Extensions.swift
- Yosemite/Yosemite.xcodeproj/project.pbxproj
- Yosemite/Yosemite/Actions/StatsActionV4.swift
- Yosemite/Yosemite/Model/Enums/StatsTimeRangeV4.swift
- Yosemite/Yosemite/Model/Storage/OrderStatsV4Totals+ReadOnlyConvertible.swift
- Yosemite/Yosemite/Stores/StatsStoreV4.swift
- Yosemite/YosemiteTests/Stores/StatsStoreV4Tests.swift
Fixes #1162 
- Schema update: added `timeRange` to `OrderStatsV4`
- Created `StatsTimeRangeV4` enum for time range of `OrderStatsV4`
- Updated `StatsStoreV4` and `StatsActionV4` to use time range instead of stats granularity which is not unique in the V4 UI anymore
- Updated `Decimal` properties in `OrderStatsV4Totals` to `NSDecimalNumber`
- this is what Core Data editor generates in code, and if not using this type the app terminates on setting such property
- Updated unit tests to reflect the subtotals data in json response
CI as there are no direct app-level changes
> Stats/Storage/Yosemite: add `timeRange` to `OrderStatsV4` and update decimal properties in `OrderStatsV4Interval`

- Yosemite/Yosemite/Actions/StatsActionV4.swift
- Yosemite/Yosemite/Model/Enums/StatsTimeRangeV4.swift
- Yosemite/Yosemite/Stores/StatsStore.swift
- Yosemite/Yosemite/Stores/StatsStoreV4.swift
- Yosemite/YosemiteTests/Stores/StatsStoreV4Tests.swift
Fixes #1165
Based on https://github.com/woocommerce/woocommerce-ios/pull/1163
- Added a case in `StatsActionV4` to fetch site visit stats for Stats v4 UI use cases with time range
- Added the same implementation in `StatsStoreV4` and in tests for site visit stats as in v3 (current prod)
CI, as there are no direct app-level changes
> Stats/Yosemite: fetch site visit stats for Stats v4 time ranges

- Networking/Networking/Model/Site.swift
- Networking/Networking/Remote/AccountRemote.swift
- Storage/Storage/Model/MIGRATIONS.md
- Storage/Storage/Model/Site+CoreDataProperties.swift
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 19.xcdatamodel/contents
- Yosemite/Yosemite/Model/Storage/Site+ReadOnlyConvertible.swift
- Yosemite/YosemiteTests/Stores/AccountStoreTests.swift
Part 1 for #1173 
- Core Data schema update:
- Added `timezone: String` attribute to `Site` entity
- Networking layer:
- Specified `options` param to fetch 3 options that we need based on [API documentation](https://developer.wordpress.com/docs/api/1.1/get/me/sites/) and decoded accordingly
- Yosemite layer:
- Updated setter and getter for `Site`
Log out and log in to verify that site information are still fetched properly (like name, tagline, url)
> Core Data/Networking/Yosemite: fetch and persist `timezone` of `Site`

- WooCommerce/Classes/ViewModels/ManualTrackingViewModel.swift
Fixes #1115 
A unit test was failing, testInitialisingWithProviderNameReturnsName(). It would return "A name" instead of expected "Hogsmeade". This was happening because in the initializer, the param name was assigned to the property, but then the next step is attempting to load a previous shipping provider name and the previous tracking link. Because the other unit tests have already run, a previous shipping provider does exist, with the name "A name". So the new provider name is overwritten with the old one.
**To Test**
Steps to reproduce the behavior:
1. Clean the project. Switch to a different branch, any PR review branch (that's not this one) should do
2. Run the unit tests
3. During this first run, the unit test fails
4. Run that unit test a second time. The unit test passes
To see …
> A unit test fails on first run

- WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/OrderStatsV4Interval+Chart.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsV4PeriodViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsV4PeriodViewController.xib
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Fixes #1154 
- Added a view and a label subview to `StoreStatsV4PeriodViewController.xib` for UI shown when there is no revenue for the time range
- Configured the no revenue container view and label, and updated their visibility and chart axis UI when no revenue for the time range
- Unified the interval revenue value with `revenueValue: Decimal` that is drawn on the chart
- I accidentally used `subtotals.netRevenue` for one of the revenue values, so I thought this might help
Prerequisite: the site/store has WC admin extension activated, and has no revenue for today and some revenue for the rest of the week or month or year
- Build from Xcode with a store that has WC admin
- In "My store", check the chart in "today" tab --> there should be a "No revenue this period" message and the chart …
> Stats v4 UI: show no revenue message for the time range

- RELEASE-NOTES.txt
- WooCommerce/Classes/Authentication/AuthenticationManager.swift
Fixes #1123 
First, the issue: on iOS 13 it is possible to dismiss the LoginPrologueViewController by swiping down.
**The issue**
**Before and after on iOS 12**
**Before and after on iOS 13**
As suggested by @jaclync , updating the modal presentation style to fullscreen seems to be enough.
Testing is a bit tricky. We'd need to run the code on iOS 13, so I'd suggest:
- Installing Xcode 11 beta 5
- Checking out the branch `try/xcode11-login`
- Build and run with Xcode 11
- Log out and check that it is not possible to dismiss the LoginPrologue
- Another build and run with Xcode 10 wouldn't hurt.
I cherry-picked the commit `e66ef8c` in `try/Xcode-login` to the current PR
If you know of a simpler way to run the code on iOS, please let me know!
> Set LoginPrologue's presentation style to fullscreen to prevent it from being dismissed

- WooCommerce/Classes/ViewRelated/Orders/Cells/ProductDetailsTableViewCell.xib
Fixes #1125 
I am not sure why this bug is not visible when running on iOS 12, but it only manifests itself on iOS 13
This is how the Order Details screen looks after applying the fix. To the left, iOS 12, to the right, iOS 13
- Set the background colour of the view that groups title and price to `.clear`
- Build and run. 
- Check that the selected state of the Products section in the Order Details screen looks like it should.
- Ideally, test on iOS 13 as well.
> Clear background color of view grouping product name and price

- RELEASE-NOTES.txt
Fixes #828. 
Jetpack pushed a fix that affects our users during the sign-in flow. This is the attempt to explain that fix to our users.
> Explain a Jetpack fix that affected our login flow

- Networking/Networking.xcodeproj/project.pbxproj
- Networking/Networking/Mapper/ProductReviewListMapper.swift
- Networking/Networking/Mapper/ProductReviewMapper.swift
- Networking/Networking/Model/Product/ProductReview.swift
- Networking/Networking/Model/Product/ProductReviewStatus.swift
- Networking/Networking/Remote/ProductReviewsRemote.swift
- Networking/NetworkingTests/Mapper/ProductReviewListMapperTests.swift
- Networking/NetworkingTests/Remote/ProductReviewsRemoteTests.swift
- Networking/NetworkingTests/Responses/reviews-all.json
- Networking/NetworkingTests/Responses/reviews-single.json
Fixes #1202 
I have implemented support for loading all reviews, a single review, and for updating the status of a single review
- Added a new remote (`ProductReviewsRemote`)
- Added model objects (`ProductReview` and `ProductReviewStatus`)
- Added new mappers (`ProductReviewMapper` and `ProductReviewListMapper`)
- Added tests for all of them 😄 (including mocks)
- 👀  on the code
- ✅  unit tests
> Reviews tab mark I: Networking

- WooCommerce/Classes/ViewModels/OrderDetailsViewModel/OrderDetailsDataSource.swift
- WooCommerce/Classes/ViewModels/OrderDetailsViewModel/OrderPaymentDetailsViewModel.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/PaymentTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/PaymentTableViewCell.xib
- WooCommerce/WooCommerceTests/ViewRelated/OrderPaymentDetailsViewModelTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/PaymentTableViewCellTests.swift
This PR is related to this issue: https://github.com/woocommerce/woocommerce-ios/issues/1090
- Changed buttons and labels as specified
- Edited `PaymentTableViewCell` to match the new design
- `OrderPaymentDetailsViewModel` now support the new logic for the "Paid By Customer" section
- Implemented new tests for `PaymentTableViewCell` and `OrderPaymentDetailsViewModel`
- Run the app, and open two different order details: the first one with an awaiting payment, the second one with a payment sent
- Run WooCommerceTests
| Awaiting payment             |  Payment sent |
> Order Detail: Updated Payment section

- RELEASE-NOTES.txt
- Yosemite/Yosemite/Stores/ProductStore.swift
Fixes #1149 
This PR is a bug fix for product images in the Order Details page. They were no longer downloading, no matter how long you waited on them. The only way to force a product image to display on the Order Details screen was to tap on the product row, wait for the image to download, then dismiss the product details page.
1. Find an order number that has a photo for the product. Example: I used Order No. 3059 in Julia's store.
2. Navigate to Order List and choose the order.
3. If you are on a fast internet connection, do not wait more than 30 seconds for the image to load. (Slow connections are estimated to time out within 2 minutes).
4. See the image appear in place.
> Products no longer load images, no matter how long you wait

- Podfile
- Podfile.lock
- WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
This is Zendesk update part 1 of 2. I propose merging Part 1 into develop, [just like WordPress did](https://github.com/wordpress-mobile/WordPress-iOS/pull/12264). Part 2 ([Zendesk SDK v 3.0.1 Swift 5.1 beta 5 compatible build](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/release_notes#3.0.1-swift-5.1-beta-5-compatible-build)) would live in a feature branch and have a Draft PR.
This PR updates Zendesk to the latest stable version, 3.0.1, and migrates the code. The new CommonUISDK is used for setting our purple nav bar color in the Create Ticket view controller and a class name changed (from Support to SupportUI). 
I updated the pod file to point to any 3.x updates
Should we only allow it to make updates on 3.0.x? (I have trust issues with Zendesk)
Zendesk UI code …
> Update Zendesk SDK to version 3.0.1

- Storage/Storage.xcodeproj/project.pbxproj
- Storage/Storage/Model/MIGRATIONS.md
- Storage/Storage/Model/ProductReview+CoreDataClass.swift
- Storage/Storage/Model/ProductReview+CoreDataProperties.swift
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 19.xcdatamodel/contents
- Storage/Storage/Tools/StorageType+Extensions.swift
- WooCommerce.xcworkspace/contents.xcworkspacedata
Fixes #1203 
I didn't add a new model version and added the new entity to model 19, as 2.5 is running model 18. I am not sure that's the right thing to do, though, so I'm happy to add a new model version if that's better.
- Added the ProductReview entity to the Model 19
- Generated coredata extensions 
- Added convenience methods to fetch `ProductReview` from coredata store
Because I didn't add a new model version, it might be necessary to checkout and run first a version of the app with Model 18. I tested with release/2.5
- Checkout and run release/2.5
- Checkout, build and run this branch. 👀  at the code.
- Check that there are no migration warnings or errors in the console
- Check that I didn't introduce any warnings (apparently I tend to do that when generating coredata extensions) …
> Reviews tab mark II: Storage

- Networking/Networking/Model/Product/ProductReview.swift
- Storage/Storage/Tools/StorageType+Extensions.swift
- Yosemite/Yosemite.xcodeproj/project.pbxproj
- Yosemite/Yosemite/Actions/ProductReviewAction.swift
- Yosemite/Yosemite/Model/Model.swift
- Yosemite/Yosemite/Model/Storage/ProductReview+ReadOnlyConvertible.swift
- Yosemite/Yosemite/Stores/ProductReviewStore.swift
- Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift
Fixes #1204 
⚠️ The base branch needs to be changed to develop before merging ⚠️ 
This PR adds support for Product Reviews to Yosemite
- Add `ProductReviewAction` and `ProductReviewStore` with unit tests
- Small updates to model objects in the Storage and Networking layer.
- 👀  at the code
- check tests are ✅ 
> Reviews tab mark III: Yosemite

- WooCommerce/Classes/AppDelegate.swift
- WooCommerce/Classes/ServiceLocator/PushNotesManager.swift
Fix #1228 
@jaclync  noticed that due to the conditional compilation of a reference to the pushNotesManager in the AppDelegate, the code would not compile to run on device, and would potentially crash
- Added two methods to the PushNotesManager protocol
- Consume the instance of PushNotesManager returned from the ServiceLocator when `targetEnvironment(simulator)` is false
- Build directly on device. Make sure the codebase builds
- Run the tests
- [x ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
> Fix build when running on devices

- WooCommerce/Classes/ViewModels/OrderDetailsViewModel/OrderPaymentDetailsViewModel.swift
Since Interpolated strings are harder to understand by translators and they may end up translating/changing the variable name, causing a crash, I modified an `NSLocalizedString` which were using interpolated strings, introduced in this PR https://github.com/woocommerce/woocommerce-ios/pull/1211.
> Order Detail: Fix interpolated strings in NSLocalizedString

- WooCommerce/Classes/ViewModels/OrderDetailsViewModel/OrderDetailsDataSource.swift
- WooCommerce/Classes/ViewModels/OrderDetailsViewModel/OrderDetailsViewModel.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderNoteHeaderTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderNoteHeaderTableViewCell.xib
- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderNoteTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderNoteTableViewCell.xib
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
This PR is related to this issue: Closes https://github.com/woocommerce/woocommerce-ios/issues/1092
Implemented the new design for order notes in Order Details, following the Refunds i3 designs.
- Edited `OrderDetailsDataSource` to manage the new Order Note Section which contains all the notes grouped under a certain date (day granularity).
- Edited `OrderDetailsViewModel` to register the new cell `OrderNoteHeaderTableViewCell`
- New `OrderNoteHeaderTableViewCell` for showing the date section of Order Notes.
- Edited `OrderNoteTableViewCell` to match the new design.
- Run the app, and open an order detail which contains order notes.
- Run WooCommerceTests
| Order 165             |  Order 215 |
> Order Details: Updated Order Notes

- docs/ARCHITECTURE.md
- docs/YOSEMITE.md
Fixes #1212 
Add a mention to the ServiceLocator. I think we are starting to reach the point where we can spin off a new document for the `WooCommerce` target, so maybe in the next update?
- Added mentions to the ServiceLocator in Yosemite.md and Architecture.md
- 👀  📖 
- [x ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
> Documentation: Add mentions to the ServiceLocator

- WooCommerce/WooCommerceTests/Tools/ServiceLocatorTests.swift
Fixes #1237 
Remove a warning in a unit test 
- Downcast the subject to Any so that the `is` check does not throw a warning
- Run the tests, check that we only have the usual two warnings about Swift 5 conversion and the Pods project
> Fix warning in unit tests for ServiceLocator

- WooCommerce/Classes/ServiceLocator/FeatureFlagService.swift
- WooCommerce/Classes/ServiceLocator/ServiceLocator.swift
- WooCommerce/Classes/System/DefaultFeatureFlagService.swift
- WooCommerce/Classes/System/FeatureFlag.swift
- WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Fixes #1268 
- Motivation: there are critical app changes (like the tab bar tabs) when I add a new feature flag for product list. I'd like to test the tab bar behavior when the feature is on and off. Right now, there is no easy way to mock a feature flag value for a view controller instantiated from the Storyboard. So I thought we could add a feature flag service dependency to `ServiceLocator` to allow mocking in tests. Please comment with any thoughts/concerns!
- Created `FeatureFlagService` protocol with a function to return whether a feature flag is enabled or not
- Moved the default implementation from `FeatureFlag.enabled` variable to `DefaultFeatureFlagService` that implements `FeatureFlagService`
- Added `FeatureFlagService` dependency to `ServiceLocator` …
> Add `FeatureFlagService` dependency to `ServiceLocator`

- Networking/Networking/Remote/NotificationsRemote.swift
- RELEASE-NOTES.txt
Fixes #1164.
The string "left a review on" wasn't localizing for review notifications.
Fixed:
- in the simulator, setting the language to English
- check out the branch and run
- use a store that has reviews
- navigate to the reviews tab  
- return to the Settings app and change the language to Italian
- "left a review on" partial string translate into Italian 
> Fix bug where notifications were not localized

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewModels/OrderDetailsViewModel/OrderDetailsViewModel.swift
- WooCommerce/Classes/ViewModels/ProductDetailsViewModel.swift
- WooCommerce/Classes/ViewRelated/Orders/Fulfillment/FulfillViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/ProductListViewController.swift
- WooCommerce/Classes/ViewRelated/Products/ProductLoaderViewController.swift
Fixes #1258 
This PR properly formats the currency for the "Price" cell in the ProductDetails page.
|<img src="https://user-images.githubusercontent.com/1062444/64435316-e30db700-d087-11e9-92f1-3e6929a7b27c.png" width="300" /> | <img src="https://user-images.githubusercontent.com/1062444/64435334-f15bd300-d087-11e9-8667-f6845f5a3ec5.png" width="300" /> |
1. Set the currency in the store website to something other than USD, OR have a previous order that was paid for in a different currency than USD.
2. On the app, navigate to Orders > Order Details > tap on a product
3. On the Product Details page, scroll down to the "Pricing and Inventory" section. A "Price" or "Regular Price" / "Sale Price" title should appear in the cell. The product's price should have the correct formatting for the …
> Pass the Order's currency symbol down to the ProductDetailsViewModel

- Networking/Networking/Remote/OrdersRemote.swift
- WooCommerce/Classes/Authentication/AuthenticationManager.swift
- WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift
- WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
- WooCommerce/Classes/Extensions/Date+Woo.swift
- WooCommerce/Classes/ViewModels/ProductDetailsViewModel.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/Privacy/PrivacySettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Notifications/NotificationsViewController.swift
Fixes #1222 
Since we run `rake lint` locally quite often from missing 🐕, I thought it'd be nice to clear all existing lint warnings so that we don't have to search for the files we changed.
- Separated long localized string into multiple lines by concatenating shorter strings with `+`
- Verified with `./Scripts/localize.py` that these changes did not create diffs on `WooCommerce/Resources/en.lproj/Localizable.strings` compared to `develop`
- I've also tried multi-line literals but would create empty space in `Localizable.strings`
- Lemme know if there are other ways to do this!
- Removed empty enum parameter
- In `OrdersRemote`'s `fieldValues`, Separated multiline literal string to two lines without line break
Hound 🐕
> Fix all lint warnings

- Storage/Storage/Tools/StorageType+Extensions.swift
- Yosemite/Yosemite/Actions/ProductAction.swift
- Yosemite/Yosemite/Stores/ProductStore.swift
- Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Yosemite layer for #1264 
- Added `searchProducts` to `ProductAction` and implemented it in `ProductStore` with basic unit tests
CI, since the new search action is not used yet
> Product List: search - Yosemite layer

- WooCommerce/Classes/Tools/Currency/CurrencySettings.swift
Fixes #1319 
- Updated currency options with fetched site settings from storage (`try? resultsController.performFetch()`) - according to the [official doc](https://developer.apple.com/documentation/coredata/nsfetchedresultscontroller/1622305-performfetch):
> After executing this method, you can access the receiver’s the fetched objects with the property fetchedObjects.
- Why this wasn't an issue for Stats v3? For Stats v3, we use the [`OrderStats`'s currency code](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/Model/OrderStats+Woo.swift#L11-L17) for stats revenue (code [here](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift#L73)).
Note: we only …
> Stats v4: fix currency stuck in USD

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewModels/OrderDetailsViewModel/OrderDetailsDataSource.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/WooBasicTableViewCell.swift
Fixes #1328 
- Set table view cell's `accessoryImage` to nil before setting `accessoryType` to disclosure for Order Details details cell
- Reset `accessoryView` in `accessoryImage` nil case
1. Go to the Orders tab.
2. Open an order with a "Processing" status and customer billing info (including customer email).
3. On the Order Details screen, scroll down to the customer information and tap "Show billing" to expand the information section.
4. Scroll back up and select "Fulfill order."
5. On the order fulfillment screen, mark the order complete.
6. When it goes back to the Order Details --> the "Details" cell should keep showing the disclosure indicator (>)
> Order Details: Icon on "Details" cell for fulfilled order can be wrong

- WooCommerce/Classes/ViewRelated/Notifications/ReviewViewModel.swift
- WooCommerce/WooCommerceTests/Reviews/ReviewViewModelTests.swift
Fixes #1276 
Some low hanging fruit, but I need a quick win for morale. 
- When a review has an empty reviewer name, rename the review author to Someone instead of Anonymous, to match the payload of the good old notifications, and what Android is doing.
- Updated the unit test that covers that case.
- I have never been able to reproduce this case (a review without author name) so I can not add screenshots, but there is a test that covers it and has been updated to match the desired behaviour
> Update anonymous author name to “Someone”

- WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteTableViewCell.xib
Fix #1322
Notice this review is against the `release/2.7` branch
I would bet some serious money on this not being a problem when building with versions of Xcode 11 previous to the release version. Who knows.
When building with the release version of Xcode 11, the Reviews tab looks like this:
- Remove the background color of the stars view, that was set in IB.
- Set the background color of the cell to `StyleManager.mooWhite`. Eventually, when implementing proper support for dark mode, the colors in Style manager would have to be renamed, so this is fairly safe.
After those changes, the Reviews tab looks like it used to look. Like this:
- Checkout the branch, build and run, navigate to the reviews tab on a device/simulator configured in dark mode
> Set background colour of notifications/review cells.

- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift
Fix #1324 
Notice this PR is against the `release/2.7` branch.
I am almost positive this was not being a problem when building with versions of Xcode 11 previous to the release version. Who knows.
When building with the release version of Xcode 11, the Orders tab looks like this:
- Set the background color of the OrderTableViewCell to `StyleManager.mooWhite`. Eventually, when implementing proper support for dark mode, the colors in Style manager would have to be renamed, so this is fairly safe.
- Checkout the branch, build and run, navigate to the Orders tab on a device/simulator configured in dark mode. It should look like this:
> Set a background color to OrderTableViewCell

- WooCommerce/Classes/Authentication/AuthenticationManager.swift
Temporary change for #1335 
- Set `LoginNavigationController`'s `overrideUserInterfaceStyle` to light mode, so that it always shows light mode UI regardless of the device preference. A proper fix would be in the `WordPressAuthenticator` pod, which might not fit in release 2.7 (but I'd defer the decision to code reviewers)
Prerequisite: device is in Dark mode
- Log out from the app
- Log in to the app --> the text in the input fields should be legible
before | after
-- | --
> Xcode 11 + Dark mode: temporarily disable Dark mode for login UI

- WooCommerce/Classes/Extensions/UITableViewCell+Helpers.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/CustomerInfoTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/CustomerNoteTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/FulfillButtonTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderNoteTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTrackingTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/PaymentTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/ProductDetailsTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/SummaryTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/LeftImageTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/WooBasicTableViewCell.swift
Fixes #1325 
The scope of the PR is limited to just making the OrderDetails screen usable in Dark mode when building the codebase with the release version of Xcode 11.
Before:
After:
- Set the background color of the cells involved in the rendering of the Order Details screen
- Set a device to dark mode.
- Checkout the branch, build the project, navigate to a single order. 
> Update background colors of all cells in OrderDetails screen

- WooCommerce/Classes/Authentication/Epilogue/EmptyStoresTableViewCell.swift
- WooCommerce/Classes/Authentication/Epilogue/StoreTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/BasicTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/HeadlineLabelTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/SwitchTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/TopLeftImageTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/ValueOneTableViewCell.swift
Fixes #1332 
The scope of the PR is limited to just making the Settings screen usable in Dark mode when building the codebase with the release version of Xcode 11.
Before:
After:
This PR touches several cells. Those used in the SettingsViewController and those used also in other view controllers that can be reached from Settings. It has the nice side effect that it will solve another bunch of issues that we have not logged yet. 🤷‍♂ 
- Set a device to dark mode. 
- Checkout the branch, build and navigate to Settings. Tap buttons all around!
> Set background colour of cells used in Settings

- WooCommerce/Classes/ViewRelated/ReusableViews/StatusListTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/TitleAndEditableValueTableViewCell.swift
Fixes #1338 
The scope of the PR is limited to just making the screen to Add a Shipment Tracking usable in Dark mode when building the codebase with the release version of Xcode 11.
Before:
After:
- Update cells used for the Add Shipment Tracking feature
- Setup a device on dark mode
- build the branch, navigate to an order in Pending status, and Add a shipment tracking
> Set background colour of cells when adding shipment tracking

- WooCommerce/Classes/ViewRelated/ReusableViews/TextViewTableViewCell.swift
Fixes #1340 
The scope of the PR is limited to just making the screen to Add a Note usable in Dark mode when building the codebase with the release version of Xcode 11.
Before: 
After:
Note that the cell view marked with an arrow is fixed in PR #1337 
- Update the background of TextViewTableViewCell
- Override dark mode for the text view embedded in it. It seemed to be a simpler solution, and simpler to revert, that preparing its background and font colors to support dark mode later on.
- Set a device in dark mode
- Build the branch, navigate to an order in Processing status, and Add a Note.
- If PR #1337 has already been merged, the view should look ok. If it hasn't, the view should only look fine, except for the section corresponding to "Email note to customer:
> Configure backgrounds for add note view

- WooCommerce/Classes/ViewRelated/Orders/Cells/ProductDetailsTableViewCell.swift
Fixes #1342 
- Called `configureSKULabel` to configure SKU label :) somehow it wasn't called before
Prerequisite: Dark mode on
- Go to Orders tab
- Tap on an Order --> the SKU text on the Product cell should be visible
before | after
-- | --
> Xcode 11 + Dark mode: fix Order Details product SKU label

- WooCommerce/Classes/ViewRelated/Products/Cells/ProductReviewsTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Products/Cells/TitleBodyTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/TwoColumnTableViewCell.swift
Fixes #1344 
- Configured background color for the following table view cells used in Order details > Product 
details
- `ProductReviewsTableViewCell`
- `TitleBodyTableViewCell`
- `TwoColumnTableViewCell`
Prerequisite: Dark mode enabled
- Go to Orders tab
- Tap on an Order
- Tap on a Product on the Order details page --> all the cells should look as in Light mode
before | after
-- | --
> Xcode 11 + Dark mode: Order details > Product details

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
Fixes #1218 
In `OrdersViewController`, we refresh data from the server in `viewWillAppear`, and on completion we reset the status filter if needed (`resetStatusFilterIfNeeded`). There are 2 conditions where we reset the status filter if it was previously set:
1. The site no longer has any Order statuses
2. The site's Order statuses do not contain the previously set status
Condition 2 always becomes true after changing an Order status, because it's using the [Equatable implementation](https://github.com/woocommerce/woocommerce-ios/blob/develop/Networking/Networking/Model/OrderStatus.swift#L57-L61) to compare two Order statuses with `name`, `slug` and `total`. Since a status' `total` changes after an Order status update, the status filter is always considered not …
> Orders: fix status filter being reset after changing the status of an Order

- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
I missed a few places when updating the credentials paths in https://github.com/woocommerce/woocommerce-ios/pull/1374. This changes the remaining paths to refer to the in-repo file.
To test:
- Build & run and verify you can still login.
> Update remaining paths to woo_app_credentials.json

- WooCommerce/Classes/ViewRelated/OrdersBadgeController.swift
Fixes #1391 
- Increased the Orders badge width for 9+ case
Prerequisites:
1. On an iOS 12 device, or on an iOS 13 simulator with larger font size (so that max 12pt font is shown) and Bold Text on
2. The store has more than 9 processing orders
- Launch the app --> the badge on the Orders tab shouldn't be truncated
device | before | after
-- | -- | --
iPhone SE iOS 13 + Bold Text on | ![Simulator Screen Shot - iPhone SE - 2019-10-23 at 15 02 32](https://user-images.githubusercontent.com/1945542/67367176-8e76ba80-f5a7-11e9-8ed3-c639293db0a2.png) | ![Simulator Screen Shot - iPhone SE - 2019-10-23 at 15 03 15](https://user-images.githubusercontent.com/1945542/67367178-8e76ba80-f5a7-11e9-8fae-fbfafae171ab.png)
iPhone 6s Plus iOS 12 + Bold Text on | …
> Orders Badge: fix truncated "9+" label with bold text or on iOS 12

- WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
- WooCommerce/Classes/ViewRelated/MainTabBarController.swift
- WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
- WooCommerce/Classes/ViewRelated/Search/Product/ProductSearchUICommand.swift
- WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift
Fixes #1263 
- Added Tracks events for Product list & search (details in #1263)
- Launch the app from a debug build
- Go to "Products" tab --> should see `🔵 Tracked main_tab_products_selected` followed by `🔵 Tracked product_list_loaded` after the products are synced
- Tap on the "Products" tab again --> should see `🔵 Tracked main_tab_products_reselected`
- Tap on a Product --> should see `🔵 Tracked product_list_product_tapped`
- Go back to the Products tab, then pull down to refresh --> should see `🔵 Tracked product_list_pulled_to_refresh`
- Tap on the search icon on the navigation bar --> should see `🔵 Tracked product_list_menu_search_tapped`
- Enter some search query --> should see `🔵 Tracked product_list_searched` while search results come in
> Product list & search: analytics

- README.md
Closes #1220 
Since it's not so easy for external contributors to understand all the steps for login into the app with a Wordpress.com account, this doc improvement explains all the steps for configuring credentials inside the app.
> Updated the README with steps for configuring app with API credentials

- RELEASE-NOTES.txt
- WooCommerce/Classes/Extensions/UINavigationBar+Appearance.swift
Fixes #1124 
Since iOS 13, the default modal presentation style became page sheet instead of fullscreen. When the user tries sending an email to the customer from the Order Details screen, the email composer modal navigation bar doesn't look like in other Apple apps. So in this PR I fixed the appearance of the navigation bar of MFMailComposeViewController on iOS 13.
1) Configure a mail on your device
2) Navigate to Order Detail > Billing
3) Tap user's email
4) Everything should look like the screenshot.
| iOS 13                               |  iOS 13 with dark mode     |                       iOS 12        |
:-------------------------:|:-------------------------:|:-------------------------:
> Fixed navigation bar appearance of MFMailComposeViewController on iOS 13

- WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteDetailsCommentTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteDetailsCommentTableViewCell.xib
- WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteDetailsHeaderPlainTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteDetailsHeaderPlainTableViewCell.xib
- WooCommerce/Classes/ViewRelated/Notifications/ReviewDetailsViewController.swift
Fixes #1303 
Before|After
-|-
- Updated height of `NoteDetailsHeaderPlainTableViewCell`
- Add implementation of `estimatedHeightForRowAt` to `ReviewDetailsViewController`
- Update top and both margins of `NoteDetailsCommentTableViewCell`
- As with other PRs related to Reviews, testing is a bit cubmersome (courtesy of some of the storyboards):
- Checkout the branch, run the tests
- Undo the feature flag. Because the NotificationsViewController is instantiated in a Storyboard, it will be necessary to touch `FeatureFlag.swift` to:
```
case .reviews:
return BuildConfiguration.current == .localDeveloper
```
and it will also be necessary to change the class of the first view controller in the Notifications.storyboard from NotificationsViewController to ReviewsViewController
- Navigate to the …
> UI fixes to review details screen.

- WooCommerce/Classes/Analytics/WooAnalytics.swift
- WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
- WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
- WooCommerce/Classes/ViewRelated/Notifications/NotificationsViewController.swift
- WooCommerce/Classes/ViewRelated/Notifications/ReviewsViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/Add Tracking/ShipmentProvidersViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
- WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
- WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift
- Yosemite/Yosemite/Tools/EntityListener.swift
- Yosemite/Yosemite/Tools/ResultsController.swift
Closes #1410 
Since our app targets iOS 12.0, we don't need to unregister an observer in its *dealloc method*.
Doc: https://developer.apple.com/documentation/foundation/notificationcenter/1413994-removeobserver
> NotificationCenter : cleaned some removeObserver() since they are no more needed after iOS 9

- WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/Add Tracking/ManualTrackingViewController.swift
Fixes #1057 
1) Launch the app with a store that has at least one order.
2) Go to "Orders" tab, tap on an order
3) Tap "Fulfill order"
4) Tap "Add Tracking"
5) Tap "Shipping provider"
6) Tap "Custom Provider" row in "CUSTOM" section
7) Enter some text in any field like tracking number
8) Tap on date in "Date shipped" field --> now the date picker will be visible also with the keyboard opened.
| Before             |  Now |
> Shipment tracking: fix picker covered by keyboard

- Yosemite/YosemiteTests/Model/Extensions/OrderStatsV4Interval+DateTests.swift
Fixes #1427 
- The test failure is reproducible after changing the computer time zone to "Los Angeles/America".
- Why it failed: in `testDateStartAndDateEnd` test case, we're trying to verify that the `interval.dateStart()` and `interval.dateEnd()` would be `Date` of the same day and time in device time zone as in the date string ("2019-08-08 10:45:00"). Before this PR, we created a GMT date then offset by the timezone's GMT offset, but we didn't specify the date of the GMT offset (`TimeZone.current.secondsFromGMT()`). By default, the GMT offset is calculated with the current date, which is 1 hour off from the GMT offset on the **test date** (August 8) due to daily saving time. If we call `TimeZone.current.secondsFromGMT(for: expectedDateInGMT)`, the GMT offset would …
> Fix `testDateStartAndDateEnd` test failures due to GMT offset of the current date

- fastlane/Pluginfile
Update wpmrelease toolkit to `0.8.1` for skipping strings update in code freeze
> bump wpmreleasetoolkit to 0.8.1

- WooCommerce/Classes/ViewRelated/Keyboard/KeyboardFrameObserver.swift
- WooCommerce/Classes/ViewRelated/Keyboard/KeyboardScrollable.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/Add Tracking/ManualTrackingViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/Add Tracking/ShipmentProvidersViewController.swift
- WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/Keyboard/KeyboardFrameObserverTests.swift
Part of #1421 
- Created `KeyboardFrameObserver` helper with a keyboard frame update handler, and a function to start observing
- Plus unit tests
- I'm open to suggestions for its interface
- Replaced the `NSNotificationCenter` implementation with `KeyboardFrameObserver` in the following view controllers:
- `ManualTrackingViewController`
- `ShipmentProvidersViewController`
- `SearchViewController`
To make sure the keyboard behavior remains the same in the affected view controllers:
Prerequisite: the site has shipping extension activated so that shipment tracking feature is enabled
- Go to "Orders" tab
- Tap on a processing Order
- Tap "Begin fulfillment"
- Tap "Add Tracking"
- Tap "Shipping provider" row --> should be able to scroll to the bottom whether the keyboard is …
> Create keyboard frame observer

- Podfile
- Podfile.lock
- WooCommerce/Classes/ViewRelated/Editor/AztecEditorViewController.swift
- WooCommerce/Classes/ViewRelated/Editor/AztecTextViewAttachmentHandler.swift
- WooCommerce/Classes/ViewRelated/Editor/AztecUIConfigurator.swift
- WooCommerce/Classes/ViewRelated/Editor/EditorFactory.swift
- WooCommerce/Classes/ViewRelated/Editor/EditorViewProperties.swift
- WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Aztec view controller - part 1 - without format bar for #1421 
- Added Aztec editor pod `WordPress-Editor-iOS`
- Created `AztecEditorViewController` that contains the Aztec editor views (HTML/Rich Text views) and a placeholder without any formatting support yet (#1421 subtask: Aztec view controller - part 2 - format bar support)
- Moved some configurable editor UI properties to `EditorViewProperties` (lemme know if there is a better naming!)
- Extracted UI configurations to `AztecUIConfigurator`
- Extracted `TextViewAttachmentDelegate` implementation to `AztecTextViewAttachmentHandler` without media support yet (a separate subtask in #1421)
- Created `EditorFactory` to instantiate a `Editor & UIViewController` for Product description
- In `ProductsViewController`, temporarily navigated to …
> Aztec editor for Product description: part 1 - no format toolbar

- WooCommerce/Classes/ViewRelated/Products/Cells/ProductsTabProductTableViewCell.swift
Fixes #1453 
The scope of the PR is limited to just making the Product List screen usable in Dark mode when building the codebase with the release version of Xcode 11.
1) Activate dark mode
2) Navigate to Product List
3) Check that everything is visually ok (readable, and without dark background)
| Before             |  After |  With the cell selected |
:-------------------------:|:-------------------------:|:-------------------------:
> Product List: fixed dark mode appearance

- WooCommerce/Classes/System/DefaultFeatureFlagService.swift
- WooCommerce/Classes/System/FeatureFlag.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.xib
- WooCommerce/Classes/ViewRelated/Products/ProductDetailsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Fixes #1418 
- Added a new feature flag for editing Products `editProducts` and turned it on for debug builds
- Created `ProductFormDataSource` as a data source protocol for Product form
- Implemented in `DefaultProductFormDataSource` with 3 sections: images, primary fields, and details (inventory/price/shipping settings)
- Created `ProductFormViewController` as the entry screen for adding/editing Product, right now it just has one table view and `DefaultProductFormDataSource` as the table view's data source
- Go to Products tab
- Tap on a Product --> should see an "Edit" button on the navigation bar on the Product Details screen
- Tap "Edit" --> should see an empty table view modal
- In code: `DefaultFeatureFlagService`, return false for `editProducts` feature flag
- Go to Products tab
- …
> Add/Edit Products: main screen - blank screen

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Customer Section/Billing Information/Cells/BillingAddressTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/Fulfillment/Cells/PickListTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/Fulfillment/Cells/PickListTableViewCell.xib
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/ProductDetailsTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/LeftImageTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/StatusListTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/WooBasicTableViewCell.swift
Fixes #1447 
I fixed all the issues on Order Detail and Order Fulfillment when dark mode is enabled (also some cell selection styles not mentioned on issue #1447). 
1) Enable dark mode from device settings.
2) Navigate to an order detail.
3) Tap on every cell and check that every selection style it's ok.
4) Navigate on every sub-flow, and check that appearance of these sections it's ok. 
> Order detail flow: fixed UI appearance with Dark mode enabled

- WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/Fulfillment/FulfillViewController.swift
There seems to be a warning on develop, on a variable that is initialised but never used.
- Remove the warning by removing the initialisation of the unused variable
- Build the branch, check if the warning is gone.
> Remove a warning

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
Fixes #1455 
1) Navigate to an order detail
2) Check that the first section on the Order Screen with the customer name and status doesn't have any space above it
3) Check that the spacing between sections looks like in Fulfill order screen.
> Order Detail: fixed wrong spacing between sections

- Gemfile.lock
- fastlane/Fastfile
- fastlane/Pluginfile
This PR updates the Installable builds lane in order to make it work with AppCenter. 
Currently AppCenter doesn't support release URLs (related issue and discussion here: https://github.com/Microsoft/fastlane-plugin-appcenter/issues/49), so it's not possible to link to the version to download, but only to the general download page. 
I updated the message to make it show a link to the general download page and the build number (which is unique because it's the CircleCI build number) related to this PR. Users have to look for the right build on the page. 
I also added the direct link to the .ipa file, but it's only useful if you have XCode to install it. 
I'll monitor the AppCenter issue and update our tooling as soon as it's solved and, in the meantime, I'll post an update on the relevant …
> Update Installable builds for AppCenter

- WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
- WooCommerce/Classes/ViewRelated/Search/Product/ProductSearchUICommand.swift
Fixes #1415 
Now the product list is sorted Alphabetically by product title, like in Android.
1) Go to Product List
2) Check that product are sorted alphabetically
3) Check that product in search are sorted alphabetically
> Updated sorting in Product List

- WooCommerce/Classes/ViewRelated/Orders/Order Details/Customer Section/CustomerNoteTableViewCell.swift
Fixes #1479 
1) Enable dark mode
2) Navigate to an order which contains shipping details
3) Check that everything is ok like in the screenshot
| Before            |  After |
> Fixed Shipping Method cell on Order Details with dark mode enabled

- Storage/Storage.xcodeproj/project.pbxproj
- Storage/Storage/Model/Attribute+CoreDataClass.swift
- Storage/Storage/Model/Attribute+CoreDataProperties.swift
- Storage/Storage/Model/MIGRATIONS.md
- Storage/Storage/Model/Product+CoreDataProperties.swift
- Storage/Storage/Model/ProductDimensions+CoreDataProperties.swift
- Storage/Storage/Model/ProductDownload+CoreDataProperties.swift
- Storage/Storage/Model/ProductVariation+CoreDataClass.swift
- Storage/Storage/Model/ProductVariation+CoreDataProperties.swift
- Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 22.xcdatamodel/contents
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 23.xcdatamodel/contents
- Storage/Storage/Tools/StorageType+Extensions.swift
Fixes #1467 
- Discussion: p99K0U-1Za-p2
- 530 diffs are on the Core Data model
- Added the following entities to a new model version 23:
- `Attribute`: meant to be a generic attribute with 3 core properties: `id`, `key`, `value`
- `ProductVariation`: following the attributes as defined on the WC API doc in the table below
- READ-ONLY attributes are non-optional
- Plus `productID` and `siteID` attributes so that we can look up the variations given a site ID and product ID later
- Launch the app from `develop`, logged in
- Launch the app from the PR branch --> the app should run normally and not crash
API attribute | type | description
-- | -- | --
id | integer | Unique identifier for the resource.READ-ONLY
date_created | date-time | The date the variation was created, in the site's …
> Readonly Product Variations: Storage layer schema update

- Networking/Networking.xcodeproj/project.pbxproj
- Networking/Networking/Remote/ProductsRemote.swift
- Networking/NetworkingTests/Remote/ProductsRemoteTests.swift
- Networking/NetworkingTests/Responses/product-update-name.json
- Yosemite/Yosemite/Actions/ProductAction.swift
- Yosemite/Yosemite/Stores/ProductStore.swift
- Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Backend tasks for #1419 
- Added updateProductName to both ProductsRemote and ProductStore/ProductAction
- Plus unit tests
- CI
> Networking & Yosemite layers: update Product name

- Networking/Networking.xcodeproj/project.pbxproj
- Networking/Networking/Mapper/ProductVariationListMapper.swift
- Networking/Networking/Model/Product/ProductVariation.swift
- Networking/Networking/Model/Product/ProductVariationAttribute.swift
- Networking/Networking/Remote/ProductVariationsRemote.swift
- Networking/NetworkingTests/Remote/ProductVariationsRemoteTests.swift
- Networking/NetworkingTests/Responses/product-variations-load-all.json
Networking layer for #1468 
- Note: 748 diffs are on the JSON response for unit test, and many lines are on the ~35 properties of `ProductVariation` & equatable conformance 😛 
- Created `ProductVariation` and `ProductVariationAttribute` that represent the immutable entities in Networking layer
- Created `ProductVariationListMapper` that maps the API response (in the form of `{"data": { actual response }}` to an array of `ProductVariation`
- Created `ProductVariationsRemote` with a function `loadAllProductVariations` to retrieve all of the `ProductVariation`s available on the server
CI!
> Readonly Product Variations: Networking layer changes

- Storage/Storage/Tools/StorageType+Extensions.swift
- Yosemite/Yosemite.xcodeproj/project.pbxproj
- Yosemite/Yosemite/Actions/ProductVariationAction.swift
- Yosemite/Yosemite/Model/Model.swift
- Yosemite/Yosemite/Model/Storage/ProductVariation+ReadOnlyConvertible.swift
- Yosemite/Yosemite/Model/Storage/ProductVariationAttribute+ReadOnlyConvertible.swift
- Yosemite/Yosemite/Stores/ProductVariationStore.swift
- Yosemite/YosemiteTests/Stores/ProductVariationStoreTests.swift
Fixes #1468 
- Added an extension to convert `Storage.ProductVariation` <--> readonly `Networking.ProductVariation`
- Added an extension to `Storage.ProductVariation` to convert its attributes property (`NSOrderedSet` type in Core Data) to an array of `Storage.Attribute`s
- Added an extension to convert `Storage.Attribute` <--> readonly `Networking.ProductVariationAttribute` (`Storage.Attribute` is a generic attribute)
- Created `ProductVariationAction` and `ProductVariationStore` to retrieve Product Variations from the server + tests
- Because `Storage.Attribute` is a generic entity that can be used for different purposes (p99K0U-1Za-p2), the ID might not be unique. For this reason, a Product Variation's attributes are always replaced instead of checking if any of the attributes already …
> Readonly Product Variations: Yosemite changes

- WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
Fixes partially #1466
Fixes #1480 
Tapping on a store, change the store selected inside the app (also without touching continue or dismiss button). It seems the right behavior. So this PR fixes only the refresh of the settings screen.
1) Go to settings
2) Tap switch store
3) Switch to a different store
4) Check that the settings screen now shows the correct store.
> Settings: switching store now update correctly the screen

- WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
- WooCommerce/Classes/ViewModels/ProductDetailsViewModel.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/Beta features/BetaFeaturesViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
Fixes #1464 
Based on the events in #1464 :
- Added new events
- Recorded the new events
- Tap Settings > Experimental Features
- Switch on Products feature on and off --> every time it's toggled, should see `🔵 Tracked settings_beta_features_products_toggled` in the console
- Make sure the Products switch is on --> should see the Products tab
- Tap on a Variable Product with variations --> should see the variants info on the Product page
- Tap on the variants info row --> should see `🔵 Tracked product_detail_view_product_variants_tapped` in the console
- When the variations are loaded --> should see `🔵 Tracked product_variants_loaded` in the console
- Turn off the internet or some other way to generate an error, then pull down to refresh --> …
> Readonly Product Variations: analytics

- WooCommerce/Classes/Extensions/UIImage+Woo.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Cells/ImageAndTitleAndTextTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormSection+ReusableTableRow.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/UIImage+ProductForm.swift
- WooCommerce/Classes/ViewRelated/Products/ProductDetailsViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Fixes #1506 
- Added 3 icons from `Gridicons`: `inventoryImage`, `priceImage, `shippingImage` as icons for each Product settings on the Product form screen
- Updated `ImageAndTitleAndTextTableViewCell` for more style configurations and UI states base on title/description empty states
- In `ProductFormSection`, renamed the details section to settings section. Added a `SettingsRow`
- In `DefaultProductFormTableViewModel`, added 3 rows under the settings section: 
- price
- inventory
- shipping
- In `ProductFormTableViewDataSource`, implemented the cell configuration for the Settings row
- Added a private extension to convert `ProductFormSection.SettingsRow.ViewModel` to `ImageAndTitleAndTextTableViewCell.ViewModel`
- In `ProductFormViewController`, added a clear view of 16px height as the …
> Add/Edit Product main screen: show price/inventory/shipping settings rows

- fastlane/Fastfile
This PR updates Fastlane to the new organization name used in AppCenter.
- Run the installable build and verify it finishes without errors.
- Verify that the download link is correct.
> Update Fastlane to the new org name in AppCenter

- WooCommerce/Classes/ViewModels/ProductDetailsViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
- WooCommerce/Classes/ViewRelated/Top Banner/TopBannerView.swift
- WooCommerce/Classes/ViewRelated/Top Banner/TopBannerViewModel.swift
Fixes #1529 
- Updated the variants info row title on Product Details screen from "Variants" to "Variations"
- Reverted new semantic colors to `StyleManager` colors before Dark Mode is released
- Made `TopBannerView` expandable when it is not actionable
- Go to Products tab --> the WIP banner should be expandable as in the screenshots
Notes: the stats banner still has the dismiss button since it is actionable
expanded | collapsed | Product Details > Variations
-- | -- | --
> Design updates for the Products teaser release

- WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/ProductImagesHeaderTableViewCell.swift
Fixes #1531 
Initially, when you rotate the screen, the cell inside the collection view of product images would not resize after frame changes or rotation.
This PR fixes this issue.
> Product Details: handled support rotation on product images collection view

- WooCommerce/Classes/Extensions/UINavigationController+Woo.swift
- WooCommerce/Classes/ViewRelated/MainTabBarController.swift
[Public crash report](https://sentry.io/share/issue/24814f8f61b941f7926d360eba018e0c/). Please log into Sentry to see full details.
Receive a new product review on your store when the app is closed. When you try to open it, the app crash.
This PR fixes a crash into frozen release 3.1. 
The crash was generated from `SyncingCoordinator` since `ReviewsViewController` was not initialized before being shown.
There was a problem of priority, as it was assumed that the view controller was immediately visible on the screen, instead, we have to consider the animations during the `popToRootViewController()`.
I implemented a completion handler on some methods, and the `popToRootViewController()` method now returns when the animation has actually been completed.
Receive a new product review on your …
> Hotfix: crash when you try to open a push notification for a product review with app inactive

- WooCommerce/Classes/System/FeatureFlag.swift
Fixes #1515 
This PR removes the `enabled` property found in the Feature Flag enum. This isn't the correct code for flagging a feature and caused enough confusion that I updated this property instead of the `isFeatureFlagEnabled` method. If it had not been caught during code review, the Refunds feature would have been prematurely exposed to users.
> Feature Flag: delete dead code

- Storage/Storage.xcodeproj/project.pbxproj
- Storage/Storage/Model/MIGRATIONS.md
- Storage/Storage/Model/Product+CoreDataProperties.swift
- Storage/Storage/Model/ProductShippingClass+CoreDataClass.swift
- Storage/Storage/Model/ProductShippingClass+CoreDataProperties.swift
- Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 24.xcdatamodel/contents
Storage layer for #1422 
- Created a new model version 24 based on 23 plus:
- A new entity `ProductShippingClass` in https://github.com/woocommerce/woocommerce-ios/commit/ef999c70a4a372ae59a0ab3d598ce9d19854305a
- Added generated `ProductShippingClass` class
No user-facing changes, just CI!
> Storage layer: add `ProductShippingClass` entity

- RELEASE-NOTES.txt
- WooCommerce/Classes/System/DefaultFeatureFlagService.swift
Fixes #1558 
- Turned on these two feature flags:
- `productList`
- `readonlyProductVariants`
- In Xcode, edit WooCommerce scheme > update Build configuration to a non-debug one
- Build the app --> should see the Experimental Features in Settings, and on Products tab > Variable Product can see the variants info
> Turn on feature flags for teaser release

- WooCommerce/Classes/Extensions/Ghost+Woo.swift
- WooCommerce/Classes/Styles/UIColor+SemanticColors.swift
Fixes #1541 
As in the screenshot in #1541, the Ghost cells show the placeholder text from the xib after we updated the colors with Dark Mode support. Before the Dark Mode support, the ghost layer used to cover any placeholder text with a color animation between two opaque colors specified in https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/Extensions/Ghost+Woo.swift#L8-L9. Since the animation end color became transparent with the Dark Mode color update (`quaternaryLabel` has 0.18 alpha in both Light and Dark modes), the placeholder text was shown through the transparent ghost layer.
- Updated the beat animation end color to an opaque color, I picked `.neutral(.shade10)` but lemme know if there's a better color!
- Log out of the app
- Log into the app
- …
> Update Ghost style beat end color to an opaque color

- WooCommerce/Classes/ViewRelated/ListSelector/PaginatedListSelectorViewController.swift
- WooCommerce/Classes/ViewRelated/ListSelector/PaginatedListSelectorViewController.xib
- WooCommerce/Classes/ViewRelated/ListSelector/PaginatedListSelectorViewProperties.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/List Selector Data Source/PaginatedProductShippingClassListSelectorDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/PaginatedListViewControllerStateCoordinator.swift
- WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
- WooCommerce/Classes/Yosemite/AuthenticatedState.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Mockups/MockProduct.swift
- WooCommerce/WooCommerceTests/ViewRelated/ListSelector/PaginatedProductShippingClassListSelectorDataSourceTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/PaginatedListViewControllerStateCoordinatorTests.swift
Fixes #1526 (part 2: paginated list)
This PR creates a paginated list selector view controller with a generic data source (could be any Storage model, and table view cell).
- Renamed `ProductsViewControllerState*` to `PaginatedListViewControllerState*` since the use cases are all for a paginated list
- Created `PaginatedListSelectorViewController` as a generic paginated list selector view controller with data source protocol `PaginatedListSelectorDataSource`. The UI could be in one of such states:
- no data - a placeholder label is displayed
- a paginated list of data: when scrolling to the bottom, it will request another batch of data from the data source
- syncing: when there are no data and it's fetching data from the server
- Created …
> Create a generic list selector screen - paginated list - shipping class example

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/ReusableViews/TwoColumnSectionHeaderView.swift
Fixes #1575 
This PR fixes a problem with large titles on section header, which truncates the content.
This problem affects not only the Product details but also every point of the app where `TwoColumnSectionHeaderView` was used.
1) Go to the Settings app > Accessibility > Display & Text Size > Larger Text.
2) Enable "Larger Accessibility Sizes" and set the text size to the largest possible size.
3) Open the Woo app and go to Settings > Experimental Features to enable the Products section if needed.
4) Open the Products tab.
5) Select a product to open the product details and scroll through the section.
6) Check also that every cell section of the app now is multiline.
> Fixed clipped content on section headings with larger font sizes

- WooCommerce/Classes/ViewRelated/Products/Cells/ProductsTabProductTableViewCell.swift
Fixes #1599
Now product list cells show the disclosure indicator.
- Enable experimental feature products
- Go to the product list
- Check that every cell shows the disclosure indicator.
> Disclosure indicators for each product in the list

- RELEASE-NOTES.txt
- WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift
Fixes #1373 
The badge with the number of processing orders on the Orders tab does not refresh after switching stores. This PR fixes this issue firing a badge reload after switching a store.
Prerequisites: having at least two stores, one with <= 9 orders with processing status, and the other with > 9 of them.
1) Launch the app logged in to one store, observe the Orders badge
2) Go to Settings and switch to the other store as in the prerequisites
3) Observe the Orders badge and make sure it was updated
> Fixed Orders badge which now is correctly refreshed after switching stores

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Dashboard/Dashboard.storyboard
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/About/AboutViewController.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/TableFooterView.xib
Fixes #1122 
When the device is on the larger font sizes, the app version footer text in Settings > About could overlap with other rows on certain screen sizes.
1) Go in Device Settings > Accessibility > Display & Text Size > Larger Text
2) Turn Larger Accessibility Sizes to ON, and move the cursor to the largest text
3) Open the app, go to Settings
4) Tap under the section "About the app" the first cell "WooCommerce"
5) Check that the footer now is not overlapping the last cell
> Fixed footer overlapping bottom row with larger font size in Settings > About

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Notes Section/Add Order Note/NewNoteViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
Fixes #1615 
Fixes #1614 
This is a good fix to have in the 3.2.1 release.
This PR fixes two problems of refresh on Order Detail.
The first one #1615 if you add a new order note in the app, it doesn't appear in the Order Notes section until you pull to refresh the screen. It was solved by updating the `orderNotes` array in the view model. I think it stopped working since the introduction of iOS 13, since we expected a refresh of the notes in the `viewWillAppear`.
The second one #1614 if you fulfill an order and then undo it, the status changes from Completed to Processing immediately, but the "Begin Fulfillment" button doesn't reappear until you pull to refresh the screen. This problem was solved refreshing not only the order status and the table view, but also the datasource section …
> Fixed issues on Order Detail refresh

- WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
Fixes #1543.
There are no steps to reproduce. I tried to follow the steps in [WPiOS fix](https://github.com/wordpress-mobile/WordPress-iOS/pull/12974) but it never successfully caused a crash for me. 
**Steps I tried:**
1. Delete the app from the sim
2. Build and run the app
3. Upon login, quickly switch to the Orders tab and pull-to-refresh while the ghostable table view is visible. 
Also tried Steps 1&2, followed by 3. Quickly tapping the filters button while the ghostable table view was visible.
From the crashes reported in Sentry, the fetchedResultsController appears to send inconsistent data to the Orders table view. Many of our Sentry reports for this issue mirror the problems WPiOS had experienced with ghostable tables. (See also: …
> Crash: Orders table row count in section zero is invalid during a refresh

- Podfile
- Podfile.lock
- WooCommerce/Classes/AppDelegate.swift
In preparation for the 3.3 release, bump the WordPressAuthenticator pod to 1.10.5, dropping the beta suffix.
> Bumps Authenticator pod to 1.10.5 release

- WooCommerce/Classes/Tools/UnitInputFormatter/DecimalInputFormatter.swift
- WooCommerce/Classes/Tools/UnitInputFormatter/UnitInputFormatter.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Shipping Settings/Product+ShippingSettingsViewModels.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Shipping Settings/ProductShippingSettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Shipping Settings/ProductShippingSettingsViewController.xib
- WooCommerce/Classes/ViewRelated/ReusableViews/UnitInputTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/UnitInputTableViewCell.xib
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Tools/DecimalInputFormatterTests.swift
Shipping Settings UI for #1422 
This PR implements the UI for the Product Shipping Settings. These are the TODO tasks after this PR:
- Fetch the product's shipping class model so that we can display the shipping class name on the Shipping Settings screen
- Navigate to the Shipping Class list selector from the Shipping Settings screen
- Functionality to update the Shipping Settings
Note: I will request design review after the shipping class name is displayed
- Created `UnitInputTableViewCell` that has a title, editable text field, and a unit. The UI is configured by `UnitInputViewModel` that contains a protocol `UnitInputFormatter` that formats and validates the unit input
- Please lemme know if you have a better naming!
- Added some extension helpers to `Product` to create …
> Edit Product: shipping settings UI

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/ReusableViews/TwoColumnSectionHeaderView.xib
Fixes #1647 
In release 3.3, we added multiline support to the right column label in https://github.com/woocommerce/woocommerce-ios/commit/ee05079abbea76f7163099420a9027ae31de62ca#diff-84d8ec864e2cbd59a2a0be78e3263aab. Without clear documentation from Apple, setting `numberOfLines = 0` to a label also changes its intrinsic width so that the label takes half of the stack view width as a side effect
- Updated the horizontal content hugging priority of the right column label from 251 to 1000 (`required`) so that the right column has its width that fits the content
- Go to Orders tab
- Tap on an Order --> the "QTY" label in the product list section header should align to the trailing edge, on portrait or landscape
before | after
-- | --
> Order Details: fix product quantity title in the 2-column header view isn't aligning to the trailing edge

- Networking/Networking.xcodeproj/project.pbxproj
- Networking/Networking/Model/Product/Product.swift
- Networking/Networking/Model/Product/ProductBackordersSetting.swift
- Networking/NetworkingTests/Mapper/ProductMapperTests.swift
- WooCommerce/Classes/Extensions/UIViewController+Helpers.swift
- WooCommerce/Classes/Tools/UnitInputFormatter/StringInputFormatter.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/Product+InventorySettingsViewModels.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventorySettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventorySettingsViewController.xib
- WooCommerce/Classes/ViewRelated/Products/Edit Product/List Selector Data Source/ProductBackordersSettingListSelectorDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/List Selector Data Source/ProductStockStatusListSelectorDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Shipping Settings/Product+ShippingSettingsViewModels.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/UnitInputTableViewCell.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Mockups/MockProduct.swift
- WooCommerce/WooCommerceTests/ViewRelated/ListSelector/ProductBackordersSettingListSelectorDataSourceTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/ListSelector/ProductStockStatusListSelectorDataSourceTests.swift
- Yosemite/Yosemite/Model/Model.swift
UI part for #1424 
This PR implements the UI for the Product Inventory Settings without the remote update functionality (the next task).
- Created a new enum `ProductBackordersSetting` based on `Product`'s `backordersKey` as the raw value. Added a calculated property `backordersSetting: ProductBackordersSetting` for `Product`
- Added `StringInputFormatter: UnitInputFormatter` for temporary SKU input view model
- Created 2 functions for `Product` extension to create view models for SKU and stock quantity
- Created `ProductBackordersSettingListSelectorDataSource` for backorders setting list selector + basic unit tests
- Created `ProductInventorySettingsViewController` with a table view that shows 3 sections of inventory settings. Implemented cell did select actions
- Added `keyboardType: …
> Edit Product: inventory settings UI

- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 24.xcdatamodel/contents
I forgot to mention a "gotcha" in Core Data. Mea Culpa.
ref: p99K0U-2hm-p2 to prevent this from happening in the future
Check out and run this branch. Xcode should no longer show the 3 warnings about Copy Bundle Resources.
> Remove Xcode warnings

- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- Yosemite/Yosemite/Actions/ProductAction.swift
- Yosemite/Yosemite/Stores/ProductStore.swift
Error handling for #1424 
When the user tries updating the Product SKU to an existing SKU or an invalid format (determined by the backend), the update fails with an error. This PR processes the error and displays an alert about the SKU error to the user
- Created a `ProductUpdateError` enum that corresponds to the error while updating a Product based on the dotcom error code. Passed this error in `ProductStore`'s `updateProduct` action
- Right now SKU is the only error returned by the server that I can think of. As we encounter more error types, we can add them to the enum
- In `ProductFormViewController`, displayed an alert based on `ProductUpdateError`
Not available yet until the inventory settings are on `develop`, just the screenshots and CI for now
Note: I came up with the copy …
> Product update error handling (SKU for now)

- WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
Resolves #1584 
- Showed the Products tab empty overlay view below the top banner view
Prerequisite: the store has no Products (or hard code to show the empty state)
- Go to Products tab --> the WIP banner should be shown above the "No products yet" message view
Dark | Light
-- | --
> Product List: show the empty state overlay to the bottom of the WIP banner

- RELEASE-NOTES.txt
- WooCommerce/Classes/Extensions/UITabBar+Appearance.swift
- WooCommerce/Classes/Styles/UIColor+SemanticColors.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformersViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsV4PeriodViewController.swift
- WooCommerce/Classes/ViewRelated/Notifications/Cells/NoteDetailsHeaderPlainTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/Fulfillment/FulfillViewController.swift
Orders, General, Reviews, Stats for #1638 
- Stats/Dashboard ("My store" tab): updated all chart and top performers separator colors to `systemColor(.secondarySystemGroupedBackground)`
- Reviews > Review Details: updated the color to `accent` in `NoteDetailsHeaderPlainTableViewCell`
- Orders > Fulfill Order: updated the color of "Add Tracking" icon to `accent`
- Navigation bar tint color: updated the bar color in Dark mode to `systemColor(.secondarySystemGroupedBackground)`
Prerequisite: the store has the shipment tracking extension
- Go to all 4 tabs --> the navigation and tab bar color should look as expected
- Go to Orders tab
- Tap on an Order with status processing
- Tap "Begin fulfillment" --> the "Add Tracking" icon should have the expected color
- Go to Reviews …
> Dark Mode: color updates for Fulfill Order, Review Details, Stats chart lines, Nav/Tab Bar

- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/Editor/FormatBar/Command/AztecBlockquoteFormatBarCommandTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Editor/FormatBar/Command/AztecBoldFormatBarCommandTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Editor/FormatBar/Command/AztecHorizontalRulerFormatBarCommandTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Editor/FormatBar/Command/AztecInsertMoreFormatBarCommandTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Editor/FormatBar/Command/AztecItalicFormatBarCommandTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Editor/FormatBar/Command/AztecLinkFormatBarCommandTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Editor/FormatBar/Command/AztecSourceCodeFormatBarCommandTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Editor/FormatBar/Command/AztecStrikethroughFormatBarCommandTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Editor/FormatBar/Command/AztecUnderlineFormatBarCommandTests.swift
Fixes #1421 
(The last step)
- Added unit tests for all the Aztec format bar commands
All changes are in the tests, just CI!
> Add unit tests for all Aztec format bar commands

- WooCommerce/Classes/ViewRelated/ListSelector/PaginatedListSelectorViewController.swift
- WooCommerce/Classes/ViewRelated/Products/PaginatedListViewControllerStateCoordinator.swift
- WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/PaginatedListViewControllerStateCoordinatorTests.swift
Fixes #1634 
Fixes #1658 
- Updated `PaginatedListViewControllerState`'s syncing case to take `pageNumber: Int` parameter instead of `withExistingData: Bool`
- In `PaginatedListSelectorViewController`, `ProductsViewController`, and `ProductVariationsViewController`:
- Placeholder is displayed when syncing the first page of data (so that older data aren't visible and interactable)
- Footer spinner is displayed when syncing beyond the first page
- This PR also fixed the disclosure indicator on the Product Variations screen
Prerequisite:
- make sure some Products are available on the Products tab before launching the app
- the store has non-zero shipping classes
---
- Go to the Products tab --> should see the placeholder flashing state, then the Product list becomes visible …
> Paginated List: show placeholder state when fetching for the first page of data

- WooCommerce/Classes/ViewRelated/ReusableViews/TwoColumnSectionHeaderView.swift
Fixes #1662 
Now `TwoColumnSectionHeaderView` takes the whole width of the left or right label if there is space available.
1) Choose a small device like an iPhone 5s
2) Go to Orders tab
3) Tap on an Order with shipment tracking information
4) Scroll to the "OPTIONAL TRACKING INFORMATION" section --> the header should take the whole width if there is space available
> TwoColumnSectionHeaderView now manage the column to take 100% of the width if the other column is hidden/empty

- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewController.swift
Part of #1423
In Edit Price Settings screen, when the keyboard was open was impossible to see all the fields, especially the fields at the bottom of the screen.
1) Open a product
2) Go in edit mode
3) Go in edit price settings
4) Make sure that with the keyboard open and also with all the date pickers opened, you are able to see and select all the fields.
> Edit Product Price: adjust table view's bottom content inset from keyboard frame changes

- Networking/Networking/Model/Site.swift
- Networking/Networking/Remote/AccountRemote.swift
- Networking/NetworkingTests/Mapper/AccountMapperTests.swift
- Networking/NetworkingTests/Responses/sites.json
- Storage/Storage.xcodeproj/project.pbxproj
- Storage/Storage/Model/MIGRATIONS.md
- Storage/Storage/Model/Site+CoreDataProperties.swift
- Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 25.xcdatamodel/contents
- WooCommerce/Classes/Extensions/TimeZone+Woo.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- Yosemite/Yosemite/Model/Storage/Site+ReadOnlyConvertible.swift
- Yosemite/YosemiteTests/Stores/AccountStoreTests.swift
Fixes #1375 
This PR introduces the website timezone, so now it's possible to use `TimeZone.websiteTimezone` to use the same timezone configured on the website.
- Introduced in `Site` the new property `gmtOffset`
- New model 25 in storage which adds the `gmtOffset` attribute to `Site` entity
- New `TimeZone+Woo` extension
- CI
> Ability to access to the correct site time zone

- WooCommerce/Classes/ViewRelated/Keyboard/KeyboardFrameObserver.swift
- WooCommerce/WooCommerceTests/ViewRelated/Keyboard/KeyboardFrameObserverTests.swift
Fixes #1693 
- On `UIResponder.keyboardWillHideNotification`, set the keyboard frame to zero instead of the end keyboard frame from the user info dictionary which is never 0 (ideally it indicates the target frame)
- Go to Products tab
- Edit Product inventory settings
- Tap on the SKU field to bring up the keyboard --> the scroll view should have a bottom inset that accommodates the keyboard height
- Toggle "Manage stock" to dismiss the keyboard --> the scroll view should not have a bottom inset
> Scroll view bottom inset isn't properly adjusted when keyboard is dismissed

- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesCollectionViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesCollectionViewController.xib
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesViewController.xib
- WooCommerce/Classes/ViewRelated/ReusableViews/ColumnFlowLayout.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
UI part for #1713 
- Created a generic `ColumnFlowLayout` collection view flow layout to render a grid layout
- Created `ProductImagesCollectionViewController` to render a collection view of Product images in a grid layout
- Created `ProductImagesViewController` that displays a Call-to-Action for adding images (no-op in this PR) and Product images via a child view controller `ProductImagesCollectionViewController`
- Added action configuration to `ProductFormTableViewDataSource` for adding images `onAddImage`
- In `ProductFormViewController`, implemented `onAddImage` to display `ProductImagesViewController`
- Go to Products tab
- Tap on a simple Product without images
- Tap on the top images header view with "+" action --> a "Photos" screen should be displayed with a CTA …
> Product images UI with CTA to add images (no functionality)

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/Fulfillment/FulfillViewController.swift
Fixes #705 by hiding the shipping address for an order, if all the products in the order are virtual. This change takes place in both Order Detail and Order Fulfill screens.
1) Open one order detail with only virtual products, and make sure there are not shipping details showed.
2) Open one order detail with both virtual and non-virtual products, and make sure shipping details are shown.
3) Open one order detail with only non-virtual products, and make sure shipping details are shown.
| Order with only virtual products             |  Order Fulfill with only virtual products |
| Order with both virtual and non-virtual             |  Order Fulfill with both virtual and non-virtual | …
> Order Detail: hide shipping address for virtual products

- WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
Amendment for #1669 
- This PR amended the previous PR https://github.com/woocommerce/woocommerce-ios/pull/1705 based on this CR comment thread https://github.com/woocommerce/woocommerce-ios/pull/1705#discussion_r364582988
- Tap on a simple Product without images --> it should go to the Edit Product screen with UI to add images (but no functionality)
- Go back to the Products tab
- Tap on a simple Product with images --> it should go to the Edit Product screen with UI to add images (but no functionality)
- On wp-admin, set the Product to be virtual
- Navigate back to the Products tab and then tap on the same Product --> the "shipping" row should not be shown
- On wp-admin, set the Product to be downloadable
- Navigate back to the Products tab and …
> Amendment for Edit Product permission checks

- Networking/Networking/Model/Refund/OrderItemRefund.swift
- WooCommerce/Classes/Extensions/Array+Helpers.swift
- WooCommerce/Classes/ViewModels/Order Details/OrderDetailsViewModel.swift
- WooCommerce/Classes/ViewModels/Refunds/OrderItemRefundSummary.swift
- WooCommerce/Classes/ViewModels/Refunds/OrderItemRefundSummaryViewModel.swift
- WooCommerce/Classes/ViewModels/Refunds/RefundedProductsDataSource.swift
- WooCommerce/Classes/ViewModels/Refunds/RefundedProductsViewModel.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Payment Section/Refunds/RefundedProductsViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/ProductDetailsTableViewCell.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Part 1 of #1717.
So the first step is to get it working. I can successfully smush the data together to create aggregate product cells. It's now readable enough to start making changes 😀 
cc: @koke @jleandroperez (if can spare the time)
The data provided by the API makes the Refunded Products table render like this:
The aggregate data, which is what the user wants to see, should render like this:
- I added a new class, `OrderItemRefundSummary`. It's based off of the struct `OrderItemRefund`.
- The `OrderItemRefundSummaryViewModel` is used for configuring the `ProductDetailsTableViewCell`.
- [summedItems](https://github.com/woocommerce/woocommerce-ios/pull/1720/files#diff-ef4a45e82a4b0b7d3eae5834c6f6d07cR18) is where the calculations happen. 
The goal is to create multiple refunds with …
> Refunded Products: summarize algorithm

- Storage/Storage.xcodeproj/project.pbxproj
- Storage/Storage/Model/MIGRATIONS.md
- Storage/Storage/Model/Product+CoreDataProperties.swift
- Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 26.xcdatamodel/contents
- Yosemite/Yosemite.xcodeproj/project.pbxproj
- Yosemite/Yosemite/Internal/NSOrderedSet+Array.swift
- Yosemite/Yosemite/Model/Storage/Product+ReadOnlyConvertible.swift
- Yosemite/Yosemite/Model/Storage/ProductVariation+ReadOnlyConvertible.swift
- Yosemite/Yosemite/Stores/ProductStore.swift
- Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
"fix the order of Product images (requires schema migration)" step in #1713 
The order of the Product images matters because it is the order they appear on the production Shop > Product page. Before this PR, `Product`'s `images` is an unordered set when we import the images from the API response to Storage and thus the order is lost. This PR preserves the order of Product images to be the same as the order in the API response.
Note: the actual changes are after the first commit that created the model version, I'd recommend reviewing by each commit
- Created a new model version 26 based on 25
- Updated the `Product`'s `images` relationship to be ordered, and now the `images` property is an `NSOrderedSet`
- Created an extension for `NSOrderedSet` to return a generic array as a helper
- In …
> Fix Product images order

- WooCommerce/Classes/ViewRelated/Products/Media/ProductImageViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImageViewController.xib
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesCollectionViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
"fullscreen image with action to delete an image" step for #1713 
- Created `ProductImageViewController` with an image view and a delete action
- Implemented Product image delete action, and on tapping a Product image cell
Prerequisites: have a Product with more than one image
- Go to Products tab
- Tap on a Product with more than one image
- Tap the last “+” cell on the images header
- Tap on an image cell to delete
- Tap the trash icon on the navigation bar
- Tap “Cancel” in the alert —> should stay on the image screen
- Tap the trash icon on the navigation bar
- Tap “Remove” in the alert —> should go back to the Product images screen
- Tap “Done”
- Tap “Update” —> the image should be deleted after the Product is updated in the app and wp-admin
Product images | Product …
> Edit Product: Product image UI with action to delete the image

- WooCommerce/Classes/Extensions/UIAlertController+Helpers.swift
- WooCommerce/Classes/Extensions/UINavigationController+Woo.swift
- WooCommerce/Classes/ViewRelated/Editor/AztecEditorViewController.swift
- WooCommerce/Classes/ViewRelated/Editor/EditorFactory.swift
- WooCommerce/Classes/ViewRelated/Editor/EditorViewProperties.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ActionSheetSaveChangesViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventorySettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Shipping Settings/ProductShippingSettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Text View Screen/TextViewViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Fixes #1640 
If there are outstanding changes on the Product Title/Description/Shipping/Price/Inventory Settings, now we show this action sheet when the user navigates back from the settings screen in case they intend to save the changes.
- New `UIAlertController` helpers extension useful to present the Save Changes ActionSheet
- New extension and protocol in `UINavigationController` extension to handle `UINavigationBar`'s **Back** button action
- Managed Save Changes Action Sheet in `AztecEditor`
- Managed Save Changes Action Sheet in `TextViewViewController`
- Managed Save Changes Action Sheet in all the controllers for editing product settings 
1) Open a product detail
2) For every editable field (Title, Description, Price, Shipping, Inventory) try to edit something, and press the back …
> Edit Product/Shipping/Price/Inventory Settings: handled back navigation while there are outstanding changes

- RELEASE-NOTES.txt
- WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
Fixes #1738 
The cause of the issue was from `presentInController` being nil, which causes the app to early return when we react to email text changes in https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift#L656. The "OK" action button is only enabled when the email input is a valid email. Because the `presentInController` was never set in the name/email text field entry point, it is always nil and thus no-op when the email text changes.
- Set `presentInController` in `getUserInformationAndShowPrompt`
- Set the email text field keyboard type to email, a minor UX improvement
(thanks @rachelmcr for the steps to repro)
1. Log out of the app.
2. Select "Log in with Jetpack" to start logging in.
3. Tap "Help" in the top right.
4. On …
> Support: fix name/email to contact support during login

- WooCommerce/Classes/ViewRelated/Products/Media/CameraCaptureCoordinator.swift
- WooCommerce/Classes/ViewRelated/Products/Media/DeviceMediaLibraryPicker.swift
- WooCommerce/Classes/ViewRelated/Products/Media/MediaPickingContext.swift
- WooCommerce/Classes/ViewRelated/Products/Media/MediaPickingCoordinator.swift
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Media picking action sheet for #1713 
This PR creates the UI and its coordinator that displays an action sheet to add images from various sources.
- Created `CameraCaptureCoordinator` that enables the user to take a photo from the device camera, no implementation yet
- Created `DeviceMediaLibraryPicker` that enables the user to pick photos from the device Photo Library, no implementation yet
- Created `MediaPickingCoordinator` that displays an action sheet menu for picking media from various sources, with `MediaPickingContext` that contains the UI context for presenting the action sheet
- Added `MediaPickingCoordinator` to `ProductImagesViewController` and displayed the media picking options menu when the user taps the "Add Photos" CTA
- Updated the "Add Photos" CTA to secondary button …
> Image Upload: media picking action sheet UI (no actions)

- RELEASE-NOTES.txt
- WooCommerce/Classes/Notifications/PushNotificationsManager.swift
- WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift
Fixes #1735 
Fixes #1736 
Before this PR, we always assumed the badge update is on the Reviews tab (previously the Notifications tab). This PR checks the notification type and then updates the badge accordingly.
- When handling a notification in `PushNotificationsManager`, added a check for notification type and then updated the badge for Orders and Reviews tab based on the type
Prerequisites: the store has < 9 processing orders, so that we can observe the order badge count update
1. Open the app and visit the Reviews tab to clear any badge on the Reviews tab icon.
2. Go to another tab e.g. My Store tab and leave the app open.
3. Receive a new order on your store.
4. Wait for the new order notice to appear in the app --> the badge count on the Orders tab should change, and there should …
> Notifications: update the badge on the Orders and Reviews tab based on the notification type

- WooCommerce/Classes/Tools/Currency/CurrencyFormatter.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewController.swift
Part of #1652 
Display an error notice on Product Price Settings if the user tries to save a sale price which is higher or equal than the regular price.
1) Go to Products tab
2) Select a product
3) Tap price cell
4) Try to add a sale price higher than the regular price, and press save.
5) You get an error.
6) Try to add a sale price equal to the regular price, and press save.
7) You get an error.
8) Try to add a sale price less than the regular price, and press save.
9) The price is saved correctly.
Let me know if you like the message error, or if you'd like to change it.
> Edit Product Price: sale price validation if is higher or equal to the regular price

- WooCommerce/Classes/ViewModels/ShippingProvidersViewModel.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/Add Tracking/ManualTrackingViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipment Tracking Section/Add Tracking/ShipmentProvidersViewController.swift
Fixes #1052.
Before | After 
Before | After 
current provider is not marked | current provider is **marked with checkmark**
touching an item highlights it by changing the background and showing a checkmark | touching an item highlights it by changing the background **only**
@Garance91540 As shown in the Before and After GIFs above, this change removes the checkmark when highlighting (touching) an item in the provider list. Is this okay? Or the highlighting with checkmark is important? 
I noticed that we don't highlight with a checkmark in Android too. 
I changed `ShipmentProvidersViewController` to use `WooBasicTableViewCell`. The selection (checkmark) behavior of the previously used `StatusListTableViewCell` requires us to preselect the item using …
> Shipment Tracking: Mark currently selected provider

- docs/ARCHITECTURE.md
- docs/NETWORKING.md
- docs/README.md
- docs/STORAGE.md
- docs/YOSEMITE.md
I added links to the class files as I was reading the docs. I only added links to where it made sense. 
This should help in understanding the doc quickly. I don't have to find the class/file in Xcode manually.
I also fixed some typos along the way.
1. View all the docs [here](https://github.com/woocommerce/woocommerce-ios/tree/update/docs/docs). 
2. Tap on the links to make sure they work. No need to go through everything. I suggest `STORAGE.md`. 
You can also try opening the files on your local editor like Visual Studio Code. CMD+tapping on a link in VS Code will open the file. 
> Docs: Add links 

- WooCommerce/Classes/Tools/Logging/CrashLogging.swift
New installs will have crash reports turned on default.
> Makes crash reports opt-in by default to match Android

- Yosemite/Yosemite.xcodeproj/project.pbxproj
- Yosemite/Yosemite/Model/Model.swift
- Yosemite/Yosemite/Tools/Media/ExportableAsset.swift
- Yosemite/Yosemite/Tools/Media/FileManager+URL.swift
- Yosemite/Yosemite/Tools/Media/ImageSourceWriter.swift
- Yosemite/Yosemite/Tools/Media/MediaAssetExporter.swift
- Yosemite/Yosemite/Tools/Media/MediaExport.swift
- Yosemite/Yosemite/Tools/Media/MediaExportService.swift
- Yosemite/Yosemite/Tools/Media/MediaFileManager.swift
- Yosemite/Yosemite/Tools/Media/MediaImageExporter.swift
- Yosemite/Yosemite/Tools/Media/URL+Media.swift
- Yosemite/YosemiteTests/Mockups/MockupFileManager.swift
- Yosemite/YosemiteTests/Tools/Media/FileManager+URLTests.swift
- Yosemite/YosemiteTests/Tools/Media/MediaDirectoryTests.swift
- Yosemite/YosemiteTests/Tools/Media/MediaFileManagerTests.swift
- Yosemite/YosemiteTests/Tools/Media/URL+MediaTests.swift
"Export image assets to local file system" part for #1713 
First, I apologize for the size of the PR 🙇🏻‍♀️ The tests are about 200 diffs. A lot of the export code is based on WPiOS, simplified to our use cases. In addition to the PR branch, I have a [`spike/media-library` branch](https://github.com/woocommerce/woocommerce-ios/compare/spike/media-library?expand=1) that includes the changes in this PR with WIP UI for initial integrated testing. I wasn't sure how to test the actual media and image export, lemme know if you have any ideas!
Also mentioned in p99K0U-2mN-p2, when the user picks an image from the device media library or took a picture from the device camera, we have to first save it in the app file system and then upload the image given the file URL. The image from the device …
> Image Upload: export an image asset to local file system

- fastlane/Fastfile
This PR adds a simple public lane that can be used by developers to generate new Match handled profiles for new components.
1. Run `bundle exec fastlane update_certs_and_profiles` and verify that the provisioning profiles for alpha, internal and production builds are installed (develop certs and profiles are not handled yet).
> Add lane to update certs and profiles

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
Fixes #1737 
Right now, we only sync and load the Product list in these 3 scenarios:
- `viewDidLoad` (once per app lifetime)
- when the site is updated, notified via `NotificationCenter`
- pulled to refresh
when logging out, we remove the view controller from listening to `NotificationCenter`, and thus after logging in again, the second scenario above isn't working anymore.
- Removed handling `logOutEventReceived` notification that removes the view controller from listening to the default `NotificationCenter`
- Launch the app while logged in to a store
- Go to the Products tab and make sure the list is loaded properly
- Log out
- Log in again to any store
- Go to the Products tab --> the list should be loaded properly instead of being empty as on `develop`
> Product List: fix Product list not loading after logging out and in

- WooCommerce/Classes/Extensions/Date+Woo.swift
- WooCommerce/Classes/Extensions/DateFormatter+Helpers.swift
- WooCommerce/Classes/Extensions/UILabel+Helpers.swift
- WooCommerce/Classes/ViewModels/Order Details/OrderDetailsViewModel.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.xib
- WooCommerce/WooCommerceTests/Extensions/DateWooTests.swift
- WooCommerce/WooCommerceTests/Tools/MockOrders.swift
- WooCommerce/WooCommerceTests/ViewRelated/OrderDetailsViewModelTests.swift
Refs #956. 
This adds the creation date of the order in the Order List.  
Before | After 
Before | After 
If the order was created from a different year, the year will be shown. If not, only the month and day.
1. Navigate to Orders
2. Confirm that the correct creation date is shown.
3. Confirm that if the order was created during the last year, the year will be shown. 
@Garance91540 I'm not sure if the spacing is too much. I only used the existing spacing of 6 pts between the labels. 
> [Order List Redesign] Add dates to each cell

- WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Notes Section/Add Order Note/NewNoteViewController.swift
Fixes #1618 
This PR fixes issue #1618.
When activating the "Email note to customer" switch, the note icon in the "Write Note" text area wasn't getting changed to the right color (.primary).
Result after fixing the issue:
"Email note to   customer" not activated | "Email note to   customer" activated
> Order Notes > Icon now changes color when activate "Email note to customer"

- WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift
- WooCommerce/Classes/ViewModels/Order Details/OrderDetailsViewModel.swift
Refs #956. This changes the total so that it is no longer abbreviated. The full total amount is now shown with up to 2 decimal numbers.
Before | After 
After (Arabic) | After (Large Font)
I removed the `totalFriendlyString` from `OrderDetailsDataSource` and just kept it in `OrderDetailsViewModel`. The `OrderDetailsDataSource` location seems like an incorrect placement since that class is used as a [table `dataSource`](https://github.com/woocommerce/woocommerce-ios/blob/f2e3e89ec63c8a84b02b103c88df97e4fbb81c0b/WooCommerce/Classes/ViewRelated/Orders/Order%20Details/OrderDetailsViewController.swift#L89). 
1. Navigate to Orders List 
2. Confirm that the totals are no longer abbreviated. 
> [Order List Redesign] Do not abbreviate the total amount

- WooCommerce/Classes/Extensions/Array+Helpers.swift
- WooCommerce/Classes/Extensions/String+Helpers.swift
This PR adds the property 'isNotEmpty' for Strings and Arrays.
Properties were created at:
WooCommerce/Classes/Extensions/Array+Helpers.swift
WooCommerce/Classes/Extensions/String+Helpers.swift
Please feel free to let me know whether I placed it in the right file, otherwise I can move it to the right one.
> Creation of a boolean property isNotEmpty for String and Array

- WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Notes Section/OrderNoteTableViewCell.swift
This PR fixes issue #1809 
The issue was that when adding a public note on an order it was showing some strange characters near the date/time field.
| Before | After |
| :-----: | :------: |
| ![image](https://user-images.githubusercontent.com/2797522/73708887-b43d5f00-4753-11ea-8b48-3608befc3163.png) | ![image](https://user-images.githubusercontent.com/2797522/73708781-75a7a480-4753-11ea-8226-64a1f3580dee.png) |
> [Order Notes] Fixing strange character in note to customer

- RELEASE-NOTES.txt
- WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
Fixes #1509 
- Truncated the log file size to the last 64k characters if needed
(I meant to add unit tests for this change, but there's no public interface for this info right now, since the log file is embedded in the Zendesk view controller of `UIViewController` type)
Prerequisite: the app log file exceeds ~64k characters. Generally, after using the app for a while the file goes over 64k characters). You can double check the log file while logged in to a store under **Settings > Help & Support > View Application Log** and look for the first file.
- Build from `develop`
- While logged in to a store, go to Settings > Help & Support > Contact Support 
- Submit a ticket --> the ticket will fail to send if the log file is over the limit
- Build the PR branch
- Go to Settings > Help & Support …
> Zendesk: limit log size to 64k characters

- Networking/Networking.xcodeproj/project.pbxproj
- Networking/Networking/Extensions/String+HTML.swift
- Networking/Networking/Model/OrderItem.swift
- Networking/Networking/Model/Product/Product.swift
- Networking/NetworkingTests/Extensions/String+HTMLTests.swift
- RELEASE-NOTES.txt
- WooCommerce/Classes/Extensions/String+HTML.swift
- WooCommerce/WooCommerceTests/Extensions/StringHTMLTests.swift
Fixes #1808 
When a user who is not an admin edits a Product (or Post) in `wp-admin`, we don't allow special characters in the Product/Post's name. Thus, the raw Product name could contain the escape characters that we want to decode in the app.
- Moved `String`'s `strippedHTML` extension to the Networking framework
- Applied `strippedHTML` to `OrderItem` and `Product`'s `name` field during decoding in the Networking layer
Prerequisites:
- have a Product whose name has some HTML escape characters (like `&amp;`, `&quot;`)
- have an order with the Product above
---
- Go to the Products tab and scroll to the Product whose name has HTML escape characters --> the Product name UI should not have the escape characters
- Tap on the Product and navigate around --> the Product name …
> Decode Order Item & Product's name

- WooCommerce/Classes/ViewRelated/Base.lproj/Main.storyboard
- WooCommerce/Classes/ViewRelated/MainTabBarController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersMasterViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersMasterViewController.xib
- WooCommerce/Classes/ViewRelated/Orders/OrdersMasterViewModel.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Refs #956. 
😱This is more than 500 lines but most it is mostly moving stuff to a different class. 
The initial goal was to continue the work in #1805 and support the transition from picking a filter and showing a list of filtered Orders. 
After some discussion and pair-programming with @pmusolino, we decided that the best way to do this is to repurpose [`OrdersViewController`](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift). We can simplify it so that its single responsibility is to **display a list of Orders**. The `OrdersViewController` can then be used in a few places in the Order List Redesign. 
There are no new _features_ added in this PR. The changes are:
1. Creating a new container class, …
> [Order List Redesign] Make OrdersViewController reusable

- Networking/Networking/Model/Order.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderLoaderViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/Orders.storyboard
- WooCommerce/Classes/ViewRelated/Orders/OrdersMasterViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.xib
- WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchUICommand.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Refs #956. This is a continuation of #1816.  
Like #1816, the goal is still to support the transition from picking a filter and showing a list of filtered Orders. 
To move towards that, I'm planning to pass the `OrderStatus` to `OrdersViewController`. We can _technically_ do that like this right now:
```swift
let ordersVC = OrdersViewController.instantiatedViewControllerFromStoryboard()
ordersVC.statusFilter = theSelectedFilter
```
But I'd like to make it safer. I want to make `statusFilter` a `let` instead of `var` so `OrdersViewController` itself will never be able to change it again. 
```swift
let ordersVC = OrdersViewController(statusFilter: theSelectedFilter)
```
To support the `init(statusFilter:)`, I moved `OrdersViewController` out of the `Orders.storyboard`. 
I removed the logout …
> [Order List Redesign] Move OrdersViewController out of the storyboard

- WooCommerce/Classes/ViewModels/MainTabViewModel.swift
Found this one while doing screenshots – this PR localizes the order count badge for locales that use non-english numerals.
**Before**
**After**
> Localize the order count badge

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift
- WooCommerce/Classes/ViewModels/Order Details/OrderDetailsViewModel.swift
Fixes #1839
Because `Order` is mutable in both `OrderDetailsDataSource` (that renders each cell) and `OrderDetailsViewModel` (that owns `OrderDetailsDataSource` and handles the cell tap event), it's easy to miss updating the data (Order and Order Items) everywhere and make sure they are the same. For this bug, the order's `items` somehow got out of sync between the data source and view model.
Perhaps we could refactor these two to have immutable `Order` in the future. Also, the `Order`'s `items` are currently not ordered in the schema, we probably want to keep them in the same order as in the API response?
- In `OrderDetailsDataSource`, updated `items: [OrderItem]` variable to derive from its `Order`
- In `OrderDetailsViewModel`:
- updated `items: [OrderItem]` variable to derive from its …
> Order Details: tapping on a Product doesn't always open the same Product if there are multiple Products

- WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
- WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchStarterViewController.swift
- WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchStarterViewModel.swift
Refs #1845. This implements filtering by Order Statuses from the Search view.
Behavior | Empty Screen 
This builds upon the changes in #1835. The linking works by injecting `OrderStatus` to the `OrderStatusViewController.init`. 
https://github.com/woocommerce/woocommerce-ios/blob/cbc13db244977dcb5a95886762f71447550c0415/WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchStarterViewController.swift#L54-L57
I have not been able to change `OrdersViewController.statusFilter` to a `let` yet. The controller is still currently being used for filtering in `OrdersMasterViewController`. 
The empty view, by default, shows a "Remove Filter" button. I hid that by passing a new argument, `showsRemoveFilterActionOnFilteredEmptyView`, to the `OrdersViewController.init`. 
There are …
> [Order List Redesign] Link Search Filtering to OrdersViewController

- RELEASE-NOTES.txt
- WooCommerce/Classes/System/DefaultFeatureFlagService.swift
This PR enables the Refunds feature in the next release 3.6 for all the users.
Make sure that Refunds and partial refunds are showed correctly inside an Order Detail, and that everything works like expected (no empty actions, no placeholder or strange things).
| Screen 1             |  Screen 2 | Screen 3 | Screen 4
:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:
> Enabled the refunds feature for all the users

- WooCommerce/WooCommerce.xcodeproj/xcshareddata/xcschemes/WooCommerceScreenshots.xcscheme
**To Test:**
1. Check out this PR
2. Run `bundle exec pod install`
3. Run `bundle exec fastlane screenshots languages:en-US`
4. When complete, ensure that:
- The time is set to 9:41 am in all screenshots
- The battery is full in all screenshots
- 5 bars of cellular signal are displayed (on iPhone devices)
- Full bars of wifi signal are displayed (on iPad devices)
- Jan 9 is displayed as the date on all devices (iPads should include the day of the week)
> Use stock date and time for screenshots

- WooCommerce/Resources/AppStoreStrings.pot
- fastlane/Fastfile
- fastlane/appstoreres/metadata/source/promo_screenshot_1.txt
- fastlane/appstoreres/metadata/source/promo_screenshot_1_b.txt
- fastlane/appstoreres/metadata/source/promo_screenshot_2.txt
- fastlane/appstoreres/metadata/source/promo_screenshot_3.txt
- fastlane/appstoreres/metadata/source/promo_screenshot_4.txt
- fastlane/appstoreres/metadata/source/promo_screenshot_5.txt
- fastlane/appstoreres/metadata/source/promo_screenshot_6.txt
- fastlane/appstoreres/metadata/source/promo_screenshot_7.txt
Updates the strings to match the new screenshots for localization.
> Update App Store Headers for localization

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewModels/ProductDetailsCellViewModel.swift
@astralbodies' [comment](https://github.com/woocommerce/woocommerce-ios/pull/1829#issuecomment-582697942) on #1829 caused me to go back and take a look at the other screenshots to see if there were any more places numbers weren't localized. There was one!
**The change:**
The item list within an order will now localize the quantity for locales that use non-english numerals.
**How to test**
You'll need to set your device to Arabic to see this change work – just changing the app locale doesn't work. Once you've changed the locale, open up a specific order's details and observe the item quantities.
**Screenshots**
| Before        | After           | 
| ------------- |-------------| 
| ![before](https://user-images.githubusercontent.com/1123407/74060902-2c03c780-49a8-11ea-8f92-9fa269c70bd3.png) …
> Localize order item quantity

- fastlane/Fastfile
This PR adds some steps to the release_finalize Fastlane action:
- removing the branch protection.
- removing the frozen tag.
- closing the milestone.
- creating a new milestone.
Testing is a bit tricky as it requires to change the state of the release.
The easiest way is probably to mock up a release and to test only the new steps in the lane. The following steps use 3.8 as test version because it doesn't affect the current release (3.6) and the milestone currently used in develop (3.7).
*Set up*
1. Checkout a `release/3.8` branch out of this branch.
2. Change the version in Version.public.xcconfig to `3.8`.
3. Comment the `ios_update_metadata(options)`, `ios_bump_version_beta()` and `ios_final_tag(options)` steps in the lane as they will fail.
4. Commit and push the branch.
5. Enable …
> Update finalise lane to handle wrap up tasks

- WooCommerce/Classes/ViewRelated/Dashboard/Settings/Beta features/BetaFeaturesViewController.swift
- WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
Fixes #1678 
Depending on whether the Edit Products feature flag is on:
- Updated the copy in Settings > Experimental Features > Products
- Updated title and message in the Products tab WIP banner
screen | Edit Products feature on | Edit Products feature off
-- | -- | --
Settings > Experimental Features | ![Simulator Screen Shot - iPhone 11 Pro - 2020-02-24 at 13 03 21](https://user-images.githubusercontent.com/1945542/75130006-f3355380-5706-11ea-92bd-a9bed5ae5f52.png) | ![Simulator Screen Shot - iPhone 11 Pro - 2020-02-24 at 13 08 03](https://user-images.githubusercontent.com/1945542/75130013-fa5c6180-5706-11ea-90a6-1414b770d154.png)
Products tab WIP banner | ![Simulator Screen Shot - iPhone 11 Pro - 2020-02-24 at 13 04 51](https://user-images.githubusercontent.com/1945542/75130009-f8929e …
> Edit Products M1: update WIP banner message & experimental features copy

- WooCommerce/Classes/ViewRelated/ReusableViews/CircleSpinnerView.swift
"The spinner stops after backgrounding the app" part for #1713 
- In `CircleSpinnerView`, listened for `UIApplication.didBecomeActiveNotification` to keep the spinner animating
Note: feel free to disable the image upload action so that the spinner stays for the whole time (e.g. return early here https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesService.swift#L14)
- Choose a photo or take one with camera --> there should be a spinner cell after picking a photo
- Background the app and come back --> the spinner should keep spinning (vs. the spinner stops before this PR)
> Image Upload: keep the spinner animating after backgrounding the app

- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesCollectionViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesViewController.swift
Part of #1713 
- Used `weak self` for the closures passed to another class that it owns
- Lemme know if you know any more concise ways to pass self's function with weak self!
Note: memory debugger works better on the simulators
- Tap on the "+" cell in the images header to edit images
- Add an image
- Go back to the Edit Product screen
- Go back to the Products tab (whether saving the Product or not)
- Run the memory debugger and search by "product" --> there should be no `ProductImage*` classes in the memory (feel free to check if you see some `ProductImage*` classes on `develop` after the same steps)
> Image Upload: weak self when passing closures

- fastlane/Fastfile
This PR adds support for uploading dSYMs to Sentry as part of an installable build.
**To Test**
- In this PR, I've already generated an installable build. In [the CI log](https://circleci.com/gh/woocommerce/woocommerce-ios/6380?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), under the `Build` phase, you can verify that the symbols were uploading by searching for `Starting sentry-cli` in the log. You can choose a file UUID at random, and search for it in the [Sentry debug file list](https://sentry.io/settings/a8c/projects/woocommerce-ios/debug-symbols/). It will be present in the list.
- If you'd like to be extra-sure this works, you can create your own branch from this one, open a PR, and run the installable build action yourself. Following the steps …
> Upload dSYMs to Sentry for installable builds

- Networking/Networking/Model/Product/Product.swift
- WooCommerce/Classes/Extensions/UIImage+Woo.swift
- WooCommerce/Classes/ViewRelated/Editor/EditorFactory.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Product+ProductForm.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormSection+ReusableTableRow.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
- WooCommerce/WooCommerceTests/Mockups/MockFeatureFlagService.swift
- WooCommerce/WooCommerceTests/ViewRelated/MainTabBarControllerTests+ProductListFeatureFlag.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel+EditProductsM2Tests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Product+ProductFormTests.swift
- Yosemite/Yosemite/Model/Updaters/ProductUpdater.swift
- Yosemite/YosemiteTests/Model/Updaters/Product+UpdaterTestCases.swift
Fixes #1831 
- In Networking layer, encoded `briefDescription` field
- Added a `UIImage` icon `briefDescriptionImage` + test case in `IconsTests`
- In `EditorFactory`, created an editor factory method for editing Product brief description
- In `DefaultProductFormTableViewModel` where we set up the sections and rows for Product Form UI, DI'ed `FeatureFlagService` for a flag that indicates whether Edit Products M2 flag is on
- Added configuration for the brief description row
- Showed the brief description row if Edit Products M2 flag is on
- Used `trimmedBriefDescription` to trim HTML tags for brief description data for this row
- In `ProductFormViewController`, handled the edit brief description action by navigating to the Aztec editor
- Added unit tests
- Tap on …
> Edit Product: short description

- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.xib
Refs #956. 
This fixes some of the design issues found in https://github.com/woocommerce/woocommerce-ios/pull/1851#pullrequestreview-357598719. This is targeting `develop` since the design changes are not dependent on #1851. 
> G: Similarly as for the product list, the bottom divider between each order row should not span the full width, but have a 16px left padding
Fixed by removing the manually set `0` inset and keeping it as automatic in 191c7e4a50d3cfd64df9a99183041c2497420e59.
Before | After | After (Dark)
--------|-------|---
> G: Order row: the font weight of the customer name is Body (it looks bold here)
Fixed by using the body style in e629d4b1fff158e894cae4329a7d737741dec054.
Before | After | After (Dark)
--------|-------|---
1. Navigate to Orders list
2. Confirm that the fixes …
> [Order List Redesign] Fix Order List Design 

- .github/workflows/screenshots.yml
- .gitignore
- WooCommerce/WooCommerceScreenshots/WooCommerceScreenshots.swift
- fastlane/Fastfile
**To Test:**
**Part 1:**
- See that the Checks list shows that all jobs are passing – that means the screenshots were generated successfully.
**Part 2:**
- Create a new branch from this one, and create a PR for it. 
- Note that the PR by default doesn't create screenshots.
- Add the "Needs Screenshots" label to the PR – that'll cause the process to start.
- Verify that it succeeds (it usually takes about an hour, give or take)
**Cleanup:**
- Close down your test PR and delete the test branch.
**Note:**
This functionality can still be a little flaky at times – based on the logs and automated screenshots captured during failures, this seems to be an issue on Xcode's part – it sometimes can't properly launch and communicate with the app in the simulator. Because it's so intermittent, and …
> Generate Screenshots in CI

- WooCommerce/Resources/AppStoreStrings.pot
- WooCommerce/Resources/release_notes.txt
Just what it says on the tin – merges the release notes to be picked up by GlotPress.
> Merge 3.7 release notes into develop

- WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
This fixes the section header height issue described in https://github.com/woocommerce/woocommerce-ios/pull/1851#pullrequestreview-357598719. The other design issues were fixed in #1861. 
This is targeting `develop` since the changes are not dependent on #1851.  
Before | After (Light)
After (Dark) | After (Large)
I used the `TwoColumnSectionHeaderView` which seems to have the correct height and is used by most parts of the app. 
1. Navigate to Orders
2. Confirm the changes to the header above.
> [Order List Redesign] Decrease header height

- WooCommerce/Classes/ViewRelated/Orders/OrdersMasterViewController.swift
Refs #956. 
This adds a border underneath the "Processing" and "All Orders" tabs. This is the last design issue to fix from #1851. 
I used the standard `UIView.createBorderView()` that we have which seems to use the separator color. 
Before | After  | After (Dark)
--------|-------|---
| After (Landscape) |
|-------|
|![image](https://user-images.githubusercontent.com/198826/75489531-a607ea80-596f-11ea-91c8-2a5e5ab0aa7a.png)|
1. Navigate to Orders
2. Confirm the border is there.
> [Order List Redesign] Add border to the bottom bar

- WooCommerce/Classes/ViewRelated/ReusableViews/ColumnFlowLayout.swift
Collection view warning part for #1713 
More context in https://github.com/woocommerce/woocommerce-ios/pull/1714#pullrequestreview-340526979
- Moved `itemSize` calculation before `super.prepare()` to avoid collection view warning
The collection view layout warning is reproducible on iPhone 11 Pro simulator, iOS 13.2
Prerequisite: the store has a simple Product with a few images
- Tap on the simple Product as in the prerequisite
- Tap on the "+" cell in the images header to edit Product images
- From portrait mode, rotate the device to landscape and then back to portrait --> there should not be warnings like below:
```
2020-02-28 17:57:26.695250+0800 WooCommerce[1641:11271964] The behavior of the UICollectionViewFlowLayout is not defined because:
2020-02-28 …
```
> `ColumnFlowLayout`: fix `UICollectionViewFlowLayout` warnings

- Networking/Networking.xcodeproj/project.pbxproj
- Networking/Networking/Model/Product/ProductReview.swift
- Networking/NetworkingTests/Remote/ProductReviewsRemoteTests.swift
- Networking/NetworkingTests/Responses/reviews-missing-avatar-urls.json
- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Notifications/ReviewDetailsViewController.swift
- Yosemite/Yosemite/Model/Storage/ProductReview+ReadOnlyConvertible.swift
- Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift
Fixes #1917
As described in #1917, we could not find the cause of why `reviewer_avatar_urls` is `null` in the JSON response. We will fix it by making `Networking.ProductReview.reviewerAvatarURLs` for now. 
Luckily, the Core Data `ProductReviews.reviewerAvatarURL` is **Optional** so we don't need to do any migration. This was odd too, because Networking's `reviewerAvatarURL` **is not** optional while Storage's `reviewerAvatarURL` **is** optional. ¯\\\_(ツ)\_/¯
The main change is utilizing `decodeIfPresent` so that the avatar URLs object will not be parsed if the key is not there or if it's `null`. 
https://github.com/woocommerce/woocommerce-ios/blob/b30443f70eca4dcc1e310b46e25506063ea63f65/Networking/Networking/Model/Product/ProductReview.swift#L68
I then added a test that proves that if …
> Make reviewer_avatar_urls optional

- RELEASE-NOTES.txt
- WooCommerce/Classes/System/DefaultFeatureFlagService.swift
Fixes #1887 
This PR enables the edit product functionality, which is behind the switch in Settings > Experimental Features that shows/hides the Products tab.
> Turned on edit products editing feature behind switch

- Gemfile.lock
Dismisses the warning – will not be a breaking change as it just updates the libxml version.
> Update Nokogiri to fix a warning

- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Fixes #1953
- On the Edit Product main screen, added a check to compare the latest product against the original product to detect any outstanding changes. If so, the same "discard changes" alert is presented like in other Edit Product settings
- Tap "< Products" in the navigation bar --> it should navigate back to the Products tab since there are no changes
- Tap on a simple Product again
- Edit the product in any way you like - name, description, price, inventory, shipping
- Tap "< Products" in the navigation bar --> it should prompt an action sheet asking if you'd like to discard changes to the product like in the screenshot below
- Tap "Cancel" --> it should stay on the Edit Product screen without the action sheet
- Tap "Update" and …
> Edit Products: show discard changes action sheet if the product has outstanding changes when navigating away

- WooCommerce/Classes/Extensions/UITabBar+Appearance.swift
Refs https://github.com/woocommerce/woocommerce-ios/issues/1938
It was reported that the tab-bar separator was not visible while using the app in dark mode.
After some investigation we realized that there is a bug on `iOS 13.1` that doesn't render the tab-bar shadow color correctly. iOS 13.3 seems to have the issue fixed.
While testing this, I also noticed that the badge text color in dark mode [should be black](https://www.figma.com/file/S62xbAwtgoMgax4GcuFjKS/System---Dark%2FLight-modes?node-id=307%3A609), so I've proceed to adjust that too.
In order to fix it, we have to specifically set it in the `standardAppearance` object to the `UITabbar.Appearance()` That also forces forces us to set other properties like `badgeBackgroundColor` and `badgeTextAttributes` to the …
> [Dark Mode] Fixes tab-bar invisible border in iOS 13.1

- WooCommerce/Classes/Extensions/UIImage+Woo.swift
- WooCommerce/Classes/ViewRelated/Notifications/ReviewsViewController.swift
- WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
Fixes https://github.com/woocommerce/woocommerce-ios/issues/1935
As part of the [Woo app UX audit](https://hogsmeadep2.wordpress.com/2019/11/27/woo-app-ux-audit-ios/) the design team has requested to update the `ReviewsViewController` comment icon in favor of the start outlined icon. 
- Update the method that generates a `startOutlined` icon to have a default icon value in order to not expose `Gridicon.defaultSize` and make them behave like the rest of icons defined on `UIImage+Woo.swift`
- Update `ReviewsViewController` to use `starOutlineImage()` instead of `commentImage`
Light|Dark
---|---
> Update ReviewsViewController tabbar-item icon

- Podfile
- Podfile.lock
Ref. #1983 
This PR updates the Gridicons pod to use 0.20-beta. It's part of an effort to update all the internal pods to the latest versions after Hack Week.
1. `rake dependencies`
2. build and run
3. Navigate through the app and check that the Gridicons used in the app haven't changed. (This has been smoke-tested. I didn't see any anomalies.)
> Update Gridicons pod to 0.20-beta

- Podfile
- Podfile.lock
Ref. #1983 
This PR updates the Tracks pod to use 0.4.4-beta.2. It's part of an effort to update all the internal pods to the latest versions after Hack Week. Once the internal pods are updated, I can begin testing Authenticator changes against WCiOS.
1. `rake dependencies`
2. Build and run
3. Navigate through the app and observe that Tracks events are firing.
> Update Tracks to use the latest available version, 0.4.4-beta.2

- Podfile
- Podfile.lock
Ref. #1983
This PR updates the WordPressUI pod to use 1.5.2-beta.1. The latest version of WordPressUI supports Swift 5.
1. `rake dependencies`
2. Build and run, to ensure there are no warnings
> Update WordPressUI pod to 1.5.2-beta.1

- Podfile
- Podfile.lock
Fixes #1983.
Update several at the same time because the dependency graph is a web, not a line. 
- Alamofire updated from 4.7.x to 4.8.x in order to support Authenticator and WordPressShared dependencies on 4.8.x. 
- Authenticator updated to 1.11.0-beta.1, which allows Authenticator to update to the latest internal pod versions.
- WordPressShared updated to 1.8.13-beta
1. `rake dependencies` (no errors should appear)
2. Build and run (no new warnings should appear)
> Update Authenticator, WordPressShared, and Alamofire

- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventorySettingsViewController.swift
Fixes #1959 
Please make sure you can reproduce the issues on `release/3.8` following the steps below!
Prerequisite: the simple product has a standard tax class (`product.taxClass` is empty), and its stock management is disabled (`product.manageStock` is false)
- Tap on the simple Product in the prerequisite
- Tap Price
- Update the regular price to a different value
- Tap "Done"
- Tap Price again
- Tap "<" in the navigation bar -->
- on `release/3.8`, the discard changes action sheet comes up without any overall changes
- now it should just navigate back to the Edit Product main screen
- Tap on the simple Product in the prerequisite
- Tap Inventory
- Turn on the "Manage stock" toggle
- Change the "Quantity" field to a different value from …
> Edit Products: fix unexpected discard changes prompt

- Yosemite/Yosemite/Actions/TaxClassAction.swift
- Yosemite/Yosemite/Stores/TaxClassStore.swift
- Yosemite/YosemiteTests/Stores/TaxClassStoreTests.swift
Attempt for #1978 
- More background in https://github.com/woocommerce/woocommerce-ios/issues/1978#issuecomment-599977771
- When upserting tax classes from API response inside a Core Data child context's async `perform` block, updated the call to `resetStoredTaxClasses(onCompletion:)` (which saves the parent context) to directly delete the existing storage models
- Removed unused `resetStoredTaxClasses(onCompletion:)`
The difficulty to reproduce the crash depends on the device and maybe other factors. I haven't been able to repro in a simulator yet, while @pmusolino has! I found that removing the `DDLogDebug("Tax Classes deleted")` line helped a little bit. I'd recommend trying to reproduce on a device/simulator on `release/3.8` first.
Generally, I was able to reproduce by:
- Go to the …
> Attempt to fix crash after visiting the tax class list selector screen a few times

- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Fixes #1968 
Moved navigation right bar button items logic from `configureNavigationBar()` to `updateNavigationBar(isUpdateEnabled: Bool)`, which is called in the original `configureNavigationBar()` and when view controller's `product` is set (e.g. when some properties are updated or when the product has been updated remotely)
- Tap on a simple Product --> Update button should not appear in the navigation bar
- Update the product in any way you like (e.g. name, description) --> Update button should appear in the navigation bar after a change is made
- Tap "Update" button and wait for the product to be updated remotely --> Update button should not appear in the navigation bar afterward
> Edit Product: "update" CTA should only be displayed when a change is made

- WooCommerce/Classes/Styles/UIColor+SemanticColors.swift
- WooCommerce/Classes/ViewRelated/Editor/AztecUIConfigurator.swift
Fixes #1963 
- Updated the text color of the HTML text view via `editorView.htmlStorage.textColor = .text`
- Updated the colors of blockquote text
- Tap the Description row to edit product description
- Format some text with blockquote (`"` icon) --> make sure the blockquote text looks good in both Dark and Light modes
- Tap the HTML icon in the keyboard toolbar (`</>` icon) --> make sure the content is visible in both Dark and Light modes
mode | before | after
-- | -- | --
blockquote - dark | ![Simulator Screen Shot - iPhone 11 - 2020-03-17 at 10 38 51](https://user-images.githubusercontent.com/1945542/76816771-1782dc80-683c-11ea-865b-e5b56a1ea680.png) | ![Simulator Screen Shot - iPhone 11 - 2020-03-18 at 09 47 …
> Update colors for Aztec HTML text view and blockquote text

- WooCommerce/Classes/ViewRelated/Editor/AztecEditorViewController.swift
Fixes #1964 
This PR resolved the issue the same way as in WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/12898
- Tap on the product description row
- Create a link for some text, if there are no links in the text already
- Tap into the link --> the link should be tappable without navigating to the web view and the link settings can be updated from the toolbar above the keyboard
> Allow editing a link on tap in Aztec

- Podfile
- Podfile.lock
- WooCommerce/Classes/Extensions/UIImage+Woo.swift
- WooCommerce/Classes/ViewRelated/Editor/FormatBar/AztecFormatBarFactory.swift
- WooCommerce/Classes/ViewRelated/Editor/FormatBar/FormatBarItemViewProperties.swift
- WooCommerce/Classes/ViewRelated/Top Banner/TopBannerView.swift
I went to merge https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/207 and https://github.com/woocommerce/woocommerce-ios/pull/2007. Unfortunately, the Authenticator recently had a Gridicons pod update to 1.0-beta.1. Since the Gridicon pods can't be out of sync for version numbers in Authenticator podfile and in the main project's podfile, this PR must be approved before I can merge in https://github.com/woocommerce/woocommerce-ios/pull/2007.
- updates the Authenticator to point to the latest pod changes, which upgraded Gridicons from `0.20` -> `1.0`
- updates the main podfile to Gridicons `1.0`
- find / replace deprecated Gridicons method calls
1. `rake dependencies`
2. Build and run
3. Choose an icon at random from the code to smoke-test
> Update main project to use Gridicons 1.0-beta.1 pod

- Podfile
- Podfile.lock
- WooCommerce/Classes/ViewRelated/Editor/FormatBar/FormatBarItemViewProperties.swift
Ref. #2003.
- TIL that Cocoapods does not like our beta versions and will ignore newer beta versions, so I made the beta versions explicit in the podfile.
- Authenticator has been updated to remove the storyboard segue `.showLoginEmail`
- See also https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/207
1. Check out this branch
2. `rake dependencies`
3. Run unit tests
4. Build and run
5. Log out
6. Select the "Log in with Jetpack" button. 
1. The Authenticator PR has been merged: wordpress-mobile/WordPressAuthenticator-iOS#207 ✔️
2. A new Authenticator release has been created ✔️
3. The release is published on Cocoapods trunk ✔️
4. This PR points to the new release ✔️
**Expected result:** it should show the expected LoginEmailViewController
> [Auth] Remove the `.showLoginEmail` segue and navigate programmatically

- WooCommerce/Classes/Tools/Currency/CurrencyFormatter.swift
- WooCommerce/Classes/Tools/Currency/CurrencySettings.swift
- WooCommerce/Classes/Tools/UnitInputFormatter/PriceInputFormatter.swift
- WooCommerce/WooCommerceTests/Tools/PriceInputFormatterTests.swift
Part of #1956 
This PR is just a small refactoring to make `CurrencyFormatter` and `PriceInputFormatter` more testable without having to modify the app `CurrencySettings` shared instance. No user-facing changes are intended.
- DI'ed `CurrencySettings` to `CurrencyFormatter`
- DI'ed `CurrencySettings` to `PriceInputFormatter`
- In `CurrencySettings` init with parameters for all the properties, removed the side effect of `configureResultsController()` and called `configureResultsController()` in the convenient `init()` that is only used in the app shared instance
- Updated unit tests to specify the currency settings for test cases that depend on certain settings (e.g. decimal separator, thousand separator)
- Go to the Orders tab --> make sure the price is formatted as in …
> Pass `CurrencySettings` to `CurrencyFormatter` and `PriceInputFormatter` for unit tests

- WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
Matches change for Android https://github.com/woocommerce/woocommerce-android/pull/2072
> Adds an exclamation point to the end of the product banner

- docs/README.md
- docs/coding-style-guide.md
This adds an initial Coding Style Guide doc. It is based on the [WordPress Swift Style Guide](https://github.com/wordpress-mobile/swift-style-guide) which we currently use. 
I mainly copied the contents and fixed some typos. I did not copy everything as some of the rules described in the WP Style Guide are already well enforced by SwiftLint. We should only document those that we cannot automate. 
I also changed the “Correct” and “Wrong”  wording to “Preferred” and “Not Preferred”. There are always exceptions to rules. 
We've been discussing about styling during pull request reviews and I believe it's better if we start documenting our team's agreements. Having our own explicitly defined style guide, though still heavily dependent on WP, should make us **move faster**. 
- Please view the …
> Add Coding Style Guide

- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/Cells/ProductTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/Cells/ProductTableViewCell.xib
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.xib
- WooCommerce/Classes/ViewRelated/Products/Cells/ProductsTabProductTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
Fixes: https://github.com/woocommerce/woocommerce-ios/issues/1934
It has been required to update the Product Cell and the TopPerformers Cell as per the latests design.
- Updates cell image background color
- Increase spacing between text components
- Updates cell separator width by replacing the standard table view separator for a custom view, as it varies depending on the image size, which varies depending on the screen size.
- Removes cell `accessoryType` on Product Tab
Top Performer|Product
---|---
Top Performer|Product
---|---
> Update Product cell style

- WooCommerce/Classes/System/DefaultFeatureFlagService.swift
- WooCommerce/Classes/System/FeatureFlag.swift
This tiny PR aims to start the development of the [Manage Categories feature](https://github.com/woocommerce/woocommerce-ios/issues/2000) 
I've submitted only the feature flag code in case someone considers working with a feature branch is better for this case, however I think that working under a feature flag is easier to manage and maintain.
- Adds `.editProductsRelease3` case
- Enable it when `BuildConfiguration.current == .localDeveloper` and `BuildConfiguration.current == .alpha`
> Adds ManageProductCategories feature flag #2000

- WooCommerce/Classes/ViewRelated/Orders/OrdersMasterViewController.swift
Turns out that mentioning `NSLocalizedString` **inside a comment** triggers `genstrings` to validate it. Since the comment has obviously incorrect syntax, this error is generated by `genstrings`:
```
genstrings: error: bad entry in file
WooCommerce/Classes/ViewRelated/Orders/OrdersMasterViewController.swift (line =
86): Argument is not a literal string.
```
Ref: p1585064201352500-slack-C6H8C3G23
1. Go to the project folder in the terminal
2. Run `./Scripts/localize.py`
3. Confirm that no errors are generated 
Note that the `Localizable.strings` may be changed after running `localize.py` so please revert it when you're done.
> Remove "NSLocalizedString" in comment

- WooCommerce/Classes/Tools/Currency/CurrencySettings.swift
Related to #1956, a refactoring task from this conversation with @shiki  https://github.com/woocommerce/woocommerce-ios/pull/2008#discussion_r395638889
- Removed `configureResultsController` from  `CurrencySettings`'s `init()` so that the initialization is just setting up its properties. Called `configureResultsController` in the singleton's init
There should be no UX changes. To sanity check, please check the steps below:
Prerequisite: having 2 sites with different currency settings
- Check the UI that displays prices in the app (e.g. Orders, Products) --> the price format should follow the currency settings in core under `wp-admin > WooCommerce > Settings > General`
- Go to the "My store" tab, and switch to another store
- Check the UI that displays prices in the app …
> Remove extra logic in `CurrencySettings`'s init

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/ListSelector/PaginatedListSelectorViewController.swift
Fixes #1954
It looks like we are already caching tax classes in `retrieveTaxClasses`:
https://github.com/woocommerce/woocommerce-ios/blob/b13f081de28c08b807e219ef41bc1a3714d309db/Yosemite/Yosemite/Stores/TaxClassStore.swift#L45-L56
The concern was because we're always showing the placeholders (ghost) if we are synchronizing the first page. 
https://github.com/woocommerce/woocommerce-ios/blob/b13f081de28c08b807e219ef41bc1a3714d309db/WooCommerce/Classes/ViewRelated/ListSelector/PaginatedListSelectorViewController.swift#L258-L261
It looks like this was done during https://github.com/woocommerce/woocommerce-ios/pull/1659 (0c8c6fab3b346487680677f78050c198663a1eb7). 
This reverts the change in 0c8c6fab3b346487680677f78050c198663a1eb7 so that the placeholders are only shown if there is no …
> Tax and Shipping Classes: Show existing data instead of ghost view when synchronizing

- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel+EditProductsM2Tests.swift
Fixes #2045 
- Updated the name of 2 test cases to avoid future confusion (more context in #2045)
no user facing changes, just CI!
> Fix function name in `DefaultProductFormTableViewModel+EditProductsM2Tests`

- WooCommerce/Classes/Extensions/UIImage+Woo.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Product+ProductForm.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormSection+ReusableTableRow.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
- WooCommerce/WooCommerceTests/Mockups/MockFeatureFlagService.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel+EditProductsM3Tests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Product+ProductFormTests.swift
Relates to: #2000 
- This PR displays(under the `editProductsRelease3`)  the product categories in the product edit screen.
- This PR also fixes some icon orientation issues on RTL languages.
- Adds a `.categories` case in the `ProductFormSection.SettingsRow` enum.
- Adds a `categoriesDescription` helper method on `Product` to display a comma separated list of category names.
- Added the necessary code to include the new categories section on `DefaultProductFormTableViewModel`
- Added tests
- Tap on a simple Product with no categories
- See categories row with "Uncategorized" description label
- Tap con a simple Product with one category
- See categories row with the single category in the description label
- Tap con a simple Product with multiple categories
- See …
> [Categories] Display product categories on Product Edit screen

- WooCommerce/Classes/ViewRelated/Keyboard/KeyboardFrameAdjustmentProvider.swift
- WooCommerce/Classes/ViewRelated/Keyboard/KeyboardScrollable.swift
- WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchStarterViewController.swift
- WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
I'm almost done with #1974 but I was currently blocked by this today. 
I was trying to vertically align the text and image shown in #1974 but found out that there's an inherited `safeAreaInsets` from `SearchViewController` that causes the vertical alignment to be skewed. 
If you'll look at the image below, the bottom area is slightly bigger. It's not because the keyboard height calculation is wrong. It's because the view is placed slightly higher because of the parent's (`SearchViewController`) `safeAreaInsets` already including the iOS Home Indicator's height.
I also found that the `safeAreaInsets` is the cause of the extra space at the bottom of the Products and Orders search results.
To remove the extra space in the search results, I included the `view.safeAreaInsets.bottom` as part of …
> Allow Customization of Keyboard Height Frame

- WooCommerce/Classes/AppDelegate.swift
- WooCommerce/Classes/ServiceLocator/ServiceLocator.swift
- WooCommerce/Classes/ViewRelated/Keyboard/KeyboardFrameObserver.swift
- WooCommerce/Classes/ViewRelated/Keyboard/KeyboardStateProvider.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Tools/ServiceLocatorTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Keyboard/KeyboardFrameObserverTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Keyboard/KeyboardStateProviderTests.swift
Refs #1974. 
In my WIP for #1974, the empty state view is created when the keyboard is **already present**. This makes it challenging to _adjust_ constraints to fit the viewable space. Or vertically align the image and text. 
This is how it currently looks right now. 😭 
I'm using the `KeyboardFrameObserver` for the constraint adjustments. However, `KeyboardFrameObserver` doesn't inform the consumer _right way_ if the keyboard is already present. It has to _wait_ for events to happen. 
This PR adds that feature:
https://github.com/woocommerce/woocommerce-ios/blob/b2498fd3f0dc4069760dd89161433573f17fccfd/WooCommerce/Classes/ViewRelated/Keyboard/KeyboardFrameObserver.swift#L37-L40
There doesn't seem to be a way to _detect_ if the keyboard is currently present. To support this, I created a …
> Allow sending of initial events in KeyboardFrameObserver

- WooCommerce/Classes/ViewRelated/ListSelector/PaginatedListSelectorViewController.swift
- WooCommerce/WooCommerceTests/ViewRelated/Keyboard/KeyboardStateProviderTests.swift
This PR fixed 2 straightforward build warnings 😄 
- WooCommerce target
```
/woocommerce-ios/WooCommerce/Classes/ViewRelated/ListSelector/PaginatedListSelectorViewController.swift:258:27: warning: immutable value 'pageNumber' was never used; consider replacing with '_' or removing it
case .syncing(let pageNumber):
^~~~~~~~~~
```
- WooCommerceTests target
```
/woocommerce-ios/WooCommerce/WooCommerceTests/ViewRelated/Keyboard/KeyboardStateProviderTests.swift:86:84: Expression implicitly coerced from '[AnyHashable : Any?]' to '[AnyHashable : Any]'
```
Just CI!
> Fix build warnings on `develop`

- Networking/Networking/Remote/MediaRemote.swift
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImageActionHandler.swift
"Update the media POST endpoint to 1.1" part of #1713 
- During testing, I realized site media POST endpoint isn't available in WP.com API v1.2 (https://developer.wordpress.com/docs/api/1.2/post/sites/%24site/media/new/ isn't available and the API response is 404) as for the [media GET endpoint](https://developer.wordpress.com/docs/api/1.2/get/sites/%24site/media/). This PR updated the endpoint from 1.2 to 1.1.
- I also noticed that no error was thrown on `develop` before this PR when receiving 404 from the media POST request. It was because `func updateProductImageStatus(at index: Int, error: Error?)` wasn't propagating the error to the all statuses callbacks. This PR updated the all statuses state to include the optional error for each update event
- Tap on a …
> Update media POST endpoint to v1.1 with error handling

- fastlane/Fastfile
This PR fixes the hotfix branch creation tooling.
The current implementation tags the branch as soon as it's created, which means that the tag has to be manually deleted and re-added after the changes are merged.
This PR removes the tagging step from the creation lane and adds a short lane only for tagging.
> Update hotfix tooling

- WooCommerce/Classes/ViewRelated/Products/Media/ProductImageActionHandler.swift
This PR fixes the build error on `develop` in https://circleci.com/gh/woocommerce/woocommerce-ios/7352?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
▸ Compiling ProductImageActionHandler.swift
❌  /Users/distiller/project/WooCommerce/Classes/ViewRelated/Products/Media/ProductImageActionHandler.swift:92:9: cannot assign to property: 'productImageStatuses' is a get-only property
productImageStatuses = newProductImageStatuses + productImageStatuses
^~~~~~~~~~~~~~~~~~~~
```
The internal state variable type was changed from just the statuses array to a tuple of the statuses array and the optional error in https://github.com/woocommerce/woocommerce-ios/pull/2075, but this change was missed in the new action for media from WP media library in …
> Fix build error on `develop`

- WooCommerce/Classes/Extensions/NSMutableAttributedString+Helpers.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Extensions/NSMutableAttributedStringHelperTests.swift
Refs #1974.
This adds a new `NSMutableAttributedString.replaceFirstOccurrence()` method. It is used to generate the _empty results_ messages in #1974. The unique case here is the search text entered by the user should be **bold**.
Here is an example of how it will be used: 
https://github.com/woocommerce/woocommerce-ios/blob/b820192bdf81d3e4b4a258593356762233ea55e6/WooCommerce/Classes/ViewRelated/Search/Product/ProductSearchUICommand.swift#L35-L40
We'd usually use [`String.localizedStringWithFormat()`](https://developer.apple.com/documentation/swift/string/1414192-localizedstringwithformat) for cases like this but there doesn't seem to be something like that in `NSAttributedString`. 
The method isn't used anywhere yet. Please review the unit tests instead. 
Only 1 reviewer is needed but …
> Add NSMutableAttributedString.replaceFirstOccurrence

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsV4PeriodViewController.swift
- Yosemite/Yosemite/Model/Extensions/OrderStatsV4Interval+Date.swift
- Yosemite/YosemiteTests/Model/Extensions/OrderStatsV4Interval+DateTests.swift
Fixes #2061 
More details in p91TBi-2Ba-p2
- When converting a date string to a `Date` object for `OrderStatsV4Interval`'s start/end dates, a time zone is now used to parse the date
- Used the site time zone `TimeZone.siteTimezone` to convert the stats v4 date strings to `Date` for UI display, instead of the device time zone (the crash was from not being able to parse a non-existent date time). Since the site time zone is from the site's `gmt_offset`, it doesn't have daily saving time and thus can parse any time.
Prerequisites:
1. set the device date time to anytime on March 29, 2020 in Rome, Italy (or any other city that has daily saving time change on the same day) under Settings > "Date & Time".
2. the site has WC 4.0+ or WC Admin plugin activated
* Notes:
1. try relaunching the app …
> Parse the stats v4 dates with the site time zone instead of device time zone

- Networking/Networking/Model/Product/Product.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsRows.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Slug/ProductSlugViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Slug/ProductSlugViewController.xib
- WooCommerce/Classes/ViewRelated/ReusableViews/TextFieldTableViewCell.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Mockups/MockProduct.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Settings/ProductSettingsViewModelTests.swift
- Yosemite/Yosemite/Model/Products/ProductSettings.swift
- Yosemite/Yosemite/Model/Updaters/ProductUpdater.swift
- Yosemite/YosemiteTests/Model/Updaters/Product+UpdaterTestCases.swift
Resolve #1826 
This PR implement the edit product slug under Product Settings, part of milestone 2.
- Encoded the `slug` field in Product model
- `ProductSettingsRows` now  manage the Slug cell
- Improved init of product settings in `ProductSettingsViewModel`
- New `ProductSlugViewController` that handle all the changes to the slug field
- Fixed tests to match the introduction of `slug`
- Updated `ProductSettings` and `ProductUpdated` to handle the `slug`
- The `textField` variable is no more private because we need to change the style of the text.
1. Navigate to a product detail
2. Press the "more" button in the navigation bar
3. Press "Product Settings" -> You are able to see the cell "Slug" with the current slug.
4. Press the "Slug" cell, you will be able to see the current slug
5. Try …
> Product Settings: edit the product slug (product's URL)

- WooCommerce/Classes/ViewRelated/Dashboard/Settings/About/LicensesViewController.swift
- WooCommerce/Resources/HTML/licenses.html
Adds dark mode support to the Settings > Open Source Licenses screen.
Uses colours pulled from other areas of the app, but could probably use a quick design review.
**To Test:**
- On the simulator, go to the licenses screen in dark or light mode – swap modes twice to see that it properly changes as the mode setting changes.
> Add Dark Mode support to the open-source licenses

- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Resolve #1824 
This PR adds the **View product in store** option inside the "**More**" action sheet in Add/Edit Products. This is part of Products Milestone 2.
| Action Sheet             |  Product in store opened |
- Run the app, and navigate to a simple product detail
- Tap the "More" nav bar button
- Make sure to see the "View product in store"
- Tap the button, make sure that a Safari VC is opened and loads the product in store
> Added "View product in store" option in Products "More" Action Sheet

- Networking/Networking/Mapper/ProductCategoryListMapper.swift
- Networking/Networking/Model/Product/ProductCategory.swift
- Networking/Networking/Remote/ProductCategoriesRemote.swift
- Networking/NetworkingTests/Mapper/ProductCategoyListMapperTests.swift
- Networking/NetworkingTests/Remote/ProductsRemoteTests.swift
- Storage/Storage.xcodeproj/project.pbxproj
- Storage/Storage/Model/MIGRATIONS.md
- Storage/Storage/Model/ProductCategory+CoreDataProperties.swift
- Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 27.xcdatamodel/contents
- Storage/Storage/Tools/StorageType+Deletions.swift
- Storage/Storage/Tools/StorageType+Extensions.swift
- WooCommerce/WooCommerceTests/Mockups/MockReviews.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Product+ProductFormTests.swift
- Yosemite/Yosemite.xcodeproj/project.pbxproj
- Yosemite/Yosemite/Actions/ProductCategoryAction.swift
- Yosemite/Yosemite/Model/Storage/ProductCategory+ReadOnlyConvertible.swift
- Yosemite/Yosemite/Model/Updaters/ProductCategoryUpdated.swift
- Yosemite/Yosemite/Stores/ProductCategoryStore.swift
- Yosemite/Yosemite/Stores/ProductStore.swift
- Yosemite/YosemiteTests/Mockups/MockProduct.swift
- Yosemite/YosemiteTests/Mockups/MockupStorage+Sample.swift
- Yosemite/YosemiteTests/Model/Updaters/Product+UpdaterTestCases.swift
- Yosemite/YosemiteTests/Stores/ProductCategoryStoreTests.swift
- Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Refs https://github.com/woocommerce/woocommerce-ios/issues/2000
Following #2043 where an action to retrieve product categories from a remote source was introduced.
This PR modifies that action to store such product categories in our storage layer.
All this efforts are made to power the ProductCategory Selector screen in a following PR.
- Adds `SiteID` and `ParentID` to Networking.ProductCategory and `Storage.ProductCategory` - includes xcdatamodel migration to v27
- Update `loadProductCategory` method to not rely on `productID` as categories would be shared through several products.
- Update `ProductCategoryStore` to upset categories in our storage layer upon a successful `loadAllProductCategories` network response.
- The big diff is due to the new `xcdatamodel` file.
- Open the app with …
> [Manage Categories]Synchronize product categories

- Podfile
- Podfile.lock
- WooCommerce/Resources/en.lproj/Localizable.strings
This PR merges `release/4.0` into `develop` in order to upload some new strings for translation and to update the Authenticator pod.
> Merge release 4.0 into develop

- Networking/NetworkingTests/Mapper/ProductMapperTests.swift
- Networking/NetworkingTests/Responses/product.json
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Shipping Settings/ProductShippingSettingsViewController.swift
- Yosemite/Yosemite/Stores/ProductStore.swift
- Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Fixes #2064 
Note: I'm targeting release 4.0 branch for M1, lemme know if you think it's better to target `develop`!
There 2 issues to this shipping class UX problem:
We retrieve the product's shipping class with the shipping class ID so that we can display the name on the shipping class row. Before this PR, we only retrieve the product's shipping class if the product's `shippingClass: ProductShippingClass?` relationship object is non-nil. However, a product could have a shipping class (which we can tell from its `shippingClass` the slug and `shippingClassID` the remote ID) while its `productShippingClass` relationship object hasn't been retrieved and linked yet (for example, before we never load the shipping class list when the user navigates to the shipping class selector UI).
This PR …
> Edit Product > Shipping Settings: retrieve shipping class and block tap action before completion

- WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/Cell/ProductCategoryTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/Cell/ProductCategoryTableViewCell.xib
- WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/ProductCategoryListViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/ProductCategoryListViewController.xib
- WooCommerce/Classes/ViewRelated/Products/Edit Product/EditCategories/ProductCategoryListViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Mockups/MockProduct.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Categories/ProductCategoryListViewModelTests.swift
References https://github.com/woocommerce/woocommerce-ios/issues/2000
After adding the ability to synchronize product categories in #2079. This PR makes sure that when the user taps on the category section in the product detail screen, the app navigates to the category selector screen.
- In order to keep this PR small, here I only render categories in the most simple way. Following PRs will take care of pagination, loading states, and category selection.
- Adds `ProductCategoryListViewController` that holds a table view to display `ProductCategoryTableViewCell` items
- Adds `ProductCategoryListViewModel` to hold state and interact with the `Yosemite` layer by handling a `ResultsController` instance to feed the table view and by dispatching the `synchronizeProductCategories` action. …
> [Manage Categories] Shows simple/basic Category Selector screen

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Media/DefaultProductUIImageLoader.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Media/ProductUIImageLoaderTests.swift
"The app shouldn't request Photos permission when opening Edit Product for the first time" for #1713 
Since just initializing a `PHImageManager` or its subclass could trigger the Photo Library permission alert ([SO post](https://stackoverflow.com/questions/38213857/what-triggers-photo-library-authorization-request-ios)), the permission alert could be shown when opening the readonly Product Details screen or Edit Product screen without any image upload actions. This is reproducible consistently in iOS 12, but not in iOS 13.
edit product (without any image upload action) | readonly product details
-- | --
- Updated the `PHAssetImageLoader` property to be a lazy var and the instance is provided by the `phAssetImageLoaderProvider: (() -> PHAssetImageLoader)? = nil` callback in the initializer …
> Only request Photo Library permission when adding images from Photo Library in image upload

- WooCommerce/Classes/Tools/Currency/CurrencyFormatter.swift
- WooCommerce/WooCommerceTests/Tools/CurrencyFormatterTests.swift
Hopefully fixes all cases in #1409
In [a previous PR](https://github.com/woocommerce/woocommerce-ios/pull/2008), it enabled DI'ing `CurrencySettings` to `CurrencyFormatter` for testing `PriceInputFormatter`, but we still use the initializer that uses the singleton values in `CurrencyFormatterTests`.
There are multiple factors that cause the test failures in `CurrencyFormatterTests`:
- `CurrencyFormatter` was using `Locale.current` for language code for manual RTL/LTR & negative formatting, so it failed on RTL device languages
- This PR DI'ed the `Locale` to each function that uses it, with default value to `.current`
- `CurrencyFormatter` and `CurrencyFormatterTests` were using `CurrencySettings.shared` (singleton) values, which could be any values if the simulator has launched previously …
> Fix test cases in `CurrencyFormatterTests` from locale, singleton usage, and negative value with RTL

- README.md
I mainly updated this to recommend `rake dependencies` since it does everything so there will be less to explain. 
I changed the instructions to use code blocks. Please let me know what you think about how that looks. Is it too much? 
Please view the changes in https://github.com/woocommerce/woocommerce-ios/blob/update/readme-doc/README.md
> Update README to recommend rake dependencies

- WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewModel.swift
- WooCommerce/WooCommerceTests/ViewRelated/Orders/OrdersViewModelTests.swift
This is just a step towards implementing Future Orders (#956). 
This continues the migration of the data loading logic from `OrdersViewController` to the `OrdersViewModel`. This mainly moves the `ResultsController<StorageOrder>` to the `ViewModel`. 
There should be no new feature changes in this PR. 
The previous `ResultsController` initialization was a bit scattered. Mostly because of my recent changes to the Orders list. 😅 They should now be in a single location inside the `ViewModel`:
https://github.com/woocommerce/woocommerce-ios/blob/fbadea3b32c8a709de9167aa358e3643191f9263/WooCommerce/Classes/ViewRelated/Orders/OrdersViewModel.swift#L31-L53
Because of the move, I had to add new methods in `OrdersViewModel` to support the `UITableView`: …
> Orders → Move ResultsController to ViewModel

- Yosemite/Yosemite/Tools/Media/MediaExportService.swift
Fixes #1836 
- Set `MediaImageExportOptions`'s `stripsGeoLocationIfNeeded` option to be `true` by default, so that the geolocation is stripped from the image
- Choose a photo that has geolocation data or take one with camera with geolocation enabled (in camera settings)
- After the image is uploaded to wp-admin > Media, check the metadata of the image (I used http://metapicz.com/ with the public image link) and make sure the geolocation isn't available (if you repeat the above on `develop`, you'd see the geolocation like in the screenshots below)
before | after
-- | --
> Strip geolocation data from images for upload by default

- WooCommerce/Classes/ViewRelated/Products/Media/ProductImageActionHandler.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Media/ProductImageActionHandlerTests.swift
Thread safety for image statuses in `ProductImageActionHandler` https://github.com/woocommerce/woocommerce-ios/pull/1878#discussion_r384614471 for #1713 
I wasn't super sure how to add unit tests to enforce thread safety (since we can't ensure which thread is executed first), please lemme know if you have any ideas!
- In `ProductImageActionHandler`, added a `queue: DispatchQueue` parameter (default to the main thread) where the `observations` and `allStatuses` are updated and accessed
- Updated unit tests
The following steps ensure the image upload works as before.
- Tap "Choose from device" and pick at least one photo --> the image(s) should be being uploaded
- Tap "Done"
- …
> Thread safety for image statuses in `ProductImageActionHandler`

- Gemfile.lock
- fastlane/Fastfile
- fastlane/Pluginfile
This PR updates `release-toolkit` in order to fix two localisation issues we saw during the last code freeze where the last version of the pods was not installed before the localization script runs and where the `localizable.strings` file was not automatically committed on changes. 
**To Test:**
1. Run `bundle install`.
2. Checkout a new test branch out of this one. 
3. Run `bundle exec fastlane update_localization`. It will run the same `ios_localize_project` step that is run during the code freeze.
4. Verify that the log contains the `pod install` step.
5. Verify that the strings are updated, committed and pushed. 
6. Run `bundle exec fastlane update_localization` again.
7. Verify that the script doesn't fail when there are no changes.
8. Delete the test branch from GitHub.
**Note:** …
> Fix localisation issues

- Podfile
- Podfile.lock
Ref. #2003 
This PR removes the segue `.showSelfHostedLogin` that sends a user to the "Login by Site Address" screen. It now navigates the user programmatically.
See also: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/242
1. Check out this branch
2. `rake dependencies`
3. Build and run
4. Log out if logged in
5. Log in with Jetpack > tap the text link "Enter the address of the WordPress site you'd like to connect."
6. **Expected:** you are navigated to the Site Address login screen.
1. The Authenticator PR has been merged: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/242
2. A new Authenticator release has been created 
3. The release is published on Cocoapods trunk
4. This PR points to the new release 
> UL&S: Remove .showSelfHostedLogin segue

- Networking/Networking/Network/Network.swift
- Networking/Networking/Remote/MediaRemote.swift
- Networking/NetworkingTests/Remote/MediaRemoteTests.swift
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImageActionHandler.swift
- WooCommerce/WooCommerceTests/Mockups/MockMediaStoresManager.swift
- Yosemite/Yosemite/Actions/MediaAction.swift
- Yosemite/Yosemite/Stores/MediaStore.swift
- Yosemite/YosemiteTests/Stores/MediaStoreTests.swift
Fixes #1988
- Added `productID` to `uploadMedia` media action/store/remote
- Added `func append(_ data: Data, withName name: String)` to `MultipartFormData` protocol that `Alamofire.MultipartFormData` implements ([Alamofire reference](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md#uploading-multipart-form-data))
- In `MediaRemote`, appended the product ID as each media item's parent ID in the multipart form data
- Choose a photo or take one with camera
- After the photo is uploaded (the spinner disappears), check that the image on `wp-admin > Media` includes the product name and link
before | after
-- | --
> Image upload: attach the product ID to an image uploaded from edit product

- WooCommerce/Classes/Extensions/UINavigationController+Woo.swift
- WooCommerce/Classes/ViewRelated/Editor/AztecEditorViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventorySettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Shipping Settings/ProductShippingSettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesViewController.swift
- WooCommerce/Classes/ViewRelated/Text View Screen/TextViewViewController.swift
Fixes #2123
As iOS users, if there’s one thing we really love on the iPhone/iPad is the global (mostly) swipe-back gesture.
This is a function that we want to continue to guarantee to our users, but there are some cases in which we need to prevent the user from going back through a swipe back gesture.
One of these cases is our needs to show the Discard Changes Action Sheet, that we started to use extensively in our new Add/Edit Products feature. Basically, the Discard Changes Action sheet will be shown when a user presses the back button, but there are changes to the data on the screen. To prevent him from inadvertently losing the data he has modified, we ask him if he really wants to discard the information.
But, @shiki discovered here #2123 that when the user uses the swipe back …
> Handled the Swipe Back gesture that triggers the "Discard Changes" action sheet

- Podfile
- Podfile.lock
I updated [Wormholy](https://github.com/pmusolino/Wormholy) to the new release 1.6.0.
The new version includes the possibility to:
- share cURL representation of requests
- share requests and responses (as examples) as [Postman](https://www.postman.com) collection (v2.1)
1) Launch Wormholy from the settings in debug mode.
2) Try to export as cURL the list of requests or a single request.
3) Try a cURL on your console, or better here: https://reqbin.com/curl
4) Share the list of requests or a single request for Postman.
5) Launch Postman, and import the output.
> Updated Wormholy to version 1.6.0

- Podfile
- Podfile.lock
Ref. #2003 
This PR removes the segue `.showWPUsernamePassword` that sends a user to the "Login with WP.com username and password" screen. It now navigates the user programmatically.
See also: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/245
1. Check out this branch
2. `rake dependencies`
3. Build and run
4. Log out if logged in
5. Log in with Jetpack > tap the text link "Enter the address of the WordPress site you'd like to connect."
6. Enter a site address > Next
7. **Expected:** you are navigated to the WP.com username / password screen.
This is a hidden option with login features that WCiOS may use in the future. Context: https://git.io/JfJ4s and pauD4L-li-p2/#comment-268.
1. Check out this branch
2. In the `AuthenticationManager`, add …
> UL&S: Remove .showWPUsernamePassword segue

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/ReusableViews/TitleAndTextFieldTableViewCell.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/UnitInputTableViewCell.swift
Fixes #2148 
Now when a user taps on the row of an editable field in Products, we begin editing that field, since it was hard to tap on the UITextField directly when the content is tiny.
1. Go to a product
2. Tap in prices
3. Tap everywhere inside the regular price cell or inside the sale price cell. You will see the text field which becomes the first responder.
4. Do the same with the Shipping fields.
5. Do the same with the SKU field in Inventory.
> Products: tapping on row begin editing of the text field

- WooCommerce/Classes/Extensions/Array+IndexPath.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventorySettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Purchase Note/ProductPurchaseNoteViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Slug/ProductSlugViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Extensions/ArrayIndexPathTests.swift
Fixes #2161 
In various points of the app, we need to get a cell at a particular IndexPath. We used the `getIndexPathForRow()` method, to get the index path of a cell, and get the text field inside that cell to make it the first responder.
Since the method `getIndexPathForRow()` started to become duplicated (until now in 3 different view controllers), to avoid duplication @jaclync suggested implementing an utility extension, where a Section need to conform to `RowIterable`.
1. Open a product detail
2. Navigate to the product slug screen -> The keyboard should pop up.
3. Navigate to the product purchase note -> The keyboard should pop up.
4. Navigate to product inventory. Try to edit the SKU adding an invalid SKU. Try to re-edit it using a valid SKU.  -> The keyboard should close.
Update …
> Array utility to get the IndexPath of a Section that conform to RowIterable

- WooCommerce/Classes/Notifications/PushNotificationsManager.swift
- WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift
This is just a small improvement to slowly update our tests to [use `tearDown`](https://qualitycoding.org/xctestcase-teardown/). 
I also changed `PushNotificationsManager` to be `final` because it can be. I think `final` should be the default for our classes. 
The unit tests passing should be good enough. 
> Make sure PushNotificationManagerTests test objects are cleared

- WooCommerce/Classes/Model/Age.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewModel.swift
- WooCommerce/WooCommerceTests/Model/AgeTests.swift
This fixes an issue in the Order List not getting loaded if an order is **exactly 1 month to the future**. The cause was the incorrect `today` calculation I added [here](https://github.com/woocommerce/woocommerce-ios/pull/2150/files#diff-3f6b3ad11392ac895822f7be127855b7). I didn't consider that `month` should be zero too. 
Luckily, the PR where that was introduced (#2150) is still in `develop`. 
This PR fixes the problem. In addition, I also added logging for `performFetch` so we can catch issues like this in the future. 
https://github.com/woocommerce/woocommerce-ios/blob/fb1f8566b689b2e579472a7e4f1d017c7c7d90f2/WooCommerce/Classes/ViewRelated/Orders/OrdersViewModel.swift#L99-L103
1. Create a _processing_ order that is **exactly a month into the future**. For example, if today is Apr …
> Fix Age.from returning `today` instead of `upcoming`

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewModel.swift
- WooCommerce/WooCommerceTests/ViewRelated/Orders/OrdersViewModelTests.swift
⚠️ Please review #2177 first. 
Refs #927. 
This adds an automatic refresh when the app is placed in the foreground. I had thought that the `viewWillAppear` implementation in #2017 handles this. I was very wrong. I didn't realize that `viewWillAppear` doesn't get triggered when the app is placed in the foreground. 🤦 I don't know why I thought it did. 🤷 
NSNotification observations were added in the `ViewModel` to detect app activation (foreground): 
https://github.com/woocommerce/woocommerce-ios/blob/68d63689435e0fb981aabd8ad457e1ad0749c5a1/WooCommerce/Classes/ViewRelated/Orders/OrdersViewModel.swift#L105-L108
The `ViewController` waits for the `ViewModel` to notify it when to perform a re-synchronization. 
https://github.com/woocommerce/woocommerce-ios/blob/68d63689435e0fb981aabd8ad457e1ad …
> Refresh Order List on app activation

- WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/ProductImagesHeaderTableViewCell.swift
Fix images header scrolling back on image status changes: https://github.com/woocommerce/woocommerce-ios/pull/1878#discussion_r384669536 for #1713 
After looking into what triggers the images header to scroll back to the beginning, I noticed it's when we reset `collectionView.collectionViewLayout` on every table view reload. This PR added a `config` internal property so that we only reset `collectionView.collectionViewLayout` on `config` change
- Choose a few photos or take one with camera --> there should be a spinner cell after picking a photo
- Quickly tap "Done" on the edit product images screen --> the product images header view should stay at the previous scroll position …
> Product images header shouldn't scroll back on image status updates

- docs/README.md
I added a new **Coding Guidelines** section in the docs README. This is where we can add more guidelines like the storyboard vs xib files. For now, I only added the "Choosing Between Structures and Classes" section based on the discussion in https://github.com/woocommerce/woocommerce-ios/pull/2156#discussion_r411941983. 
Please feel free to comment on anything that I've written here. The guidelines are something that we have to agree about after all. 🙂 I also may have misunderstood the discussion! And if you have any suggestions, please feel free to suggest them. I feel like we can add more here but nothing comes to mind at the moment. 
You may view the full README [here](https://github.com/woocommerce/woocommerce-ios/blob/update/docs-coding-guidelines/docs/README.md).
> Docs: Add Coding Guidelines about Structs vs Classes

- RELEASE-NOTES.txt
- WooCommerce/Classes/Notifications/PushNotificationsManager.swift
- WooCommerce/Classes/ServiceLocator/ForegroundNotification.swift
- WooCommerce/Classes/ServiceLocator/PushNotesManager.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewModel.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Mockups/MockPushNotificationsManager.swift
- WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Orders/OrdersViewModelTests.swift
Closes #927. 
⚠️ This depends on #2191. Please review that first. 
This continues #2178 by making the Order List auto-refresh when receiving a new order remote notification while the Order List is visible. 
This GIF shows the list auto-refreshing as soon as a remote notification arrives.
The auto-refresh only happens if the remote notification was received:
- while the Order List is visible 
- and the app is in the foreground.  
This utilizes the `PublishSubject` added in #2191. In `PushNotifictionsManager` (`PushNotesManager` protocol), I added an exposed `foregroundNotifications` Observable:
https://github.com/woocommerce/woocommerce-ios/blob/51227df78a70dc643e26e06bc57a2d27fca38ccc/WooCommerce/Classes/ServiceLocator/PushNotesManager.swift#L6-L9
`PushNotificationsManager` emits a new …
> Order List → Refresh When Receiving a new Order Notification While in the Foreground

- WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchStarterViewController.swift
- WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchStarterViewModel.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/Search/Order/OrderSearchStarterViewModelTests.swift
Refs #2171. 
Before I tackle any changes for #2171, I'd like to first fix my horrible mistake which is [`OrderSearchStarterViewModel`](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchStarterViewModel.swift). When I created that, I wanted to find a way to hide many implementation details from the `ViewController` and take away a lot of boilerplate from working with `ResultsController`. It didn't work too well. 
Here are the mistakes from that attempt:
- The cell **view creation** is in the `ViewModel`. I should have realized this from the start. 😞 
- It was difficult to test because the methods are hidden.
This PR refactors `OrderSearchStarterViewModel` so that:
- The cell view creation is now in the `ViewController`. 
- …
> Refactor OrderSearchStarterViewModel for Testability

- WooCommerce/Classes/Tools/UnitInputFormatter/IntegerInputFormatter.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/Menu Order/ProductMenuOrderViewController.swift
- WooCommerce/WooCommerceTests/Tools/IntegerInputFormatterTests.swift
Fixes #2205 
Initially, it wasn't possible to set a negative value in Product Settings -> Menu Order, if you start typing the - sign or edit a negative value.
This PR modifies the `IntegerInputFormatter` which now allows the minus sign, and which has a new initializer which allows us to set a default value used by format() when the text is empty or the number formatter returns a nil value.
1. Open a simple product.
2. Open product settings.
3. Tap in "Menu Order" cell.
4. Try to edit the menu order value adding a negative value.
5. Press back and save the product.
6. Go to this product from wp-admin and make sure the value was saved correctly.
7. Repeat the operation, and make sure that if you add only a minus sign `-` or you left the text field empty and you press back, the previous menu …
> Product Settings: Menu Order now allow negative values

- WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.swift
- WooCommerce/Classes/Authentication/Prologue/LoginPrologueViewController.xib
Refs p91TBi-2Cm-p2#comment-563
This removes the "Jetpack" text from the Log In button. The blurb mentioning "Jetpack" above the button is currently kept because we don't have an alternative for that yet. 
Before | After | After (Dark)
--------|-------|----
1. Remove the app from the device
2. Run the app
3. Confirm the button title is showing just "Log In"
> LoginPrologue: Remove "Jetpack" text from Log In button

- Networking/Networking.xcodeproj/project.pbxproj
- Networking/Networking/Copiable/Copiable.swift
- Networking/Networking/Model/Copiable/ProductImage+Copiable.swift
- Networking/NetworkingTests/Copiable/CopiableTests.swift
- docs/README.md
I went about this the wrong way. I've been running in circles, trying to figure out how to _generate_ this. I just realized I _could_ submit this foundational code first, along with some documentation. 
This is mostly the same as what was discussed in p91TBi-2BL-p2. 
- I added the `CopiableProp` and `NullableCopiableProp` `typealiases` in [Copiable.swift](https://github.com/woocommerce/woocommerce-ios/blob/feat/copiable-framework/Networking/Networking/Copiable/Copiable.swift)
- I created a temporary [`ProductImage+Copiable`](https://github.com/woocommerce/woocommerce-ios/blob/feat/copiable-framework/Networking/Networking/Model/Copiable/ProductImage+Copiable.swift) implementation so that I can add a unit test against it. 
I'll propose how the code generation should work for this in a post. …
> Add Copiable Foundation

- WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesViewController.swift
Fixes #2072 
The goal of this PR/fix is to save users one step of tapping the "Done" button back on the edit product images screen after they add/pick any image(s) from any of the sources.
- In `ProductImagesViewController`, called `doneButtonTapped()` and disabled dismiss animation when applicable in the following scenarios:
- The user finished picking image(s) from the device picker
- The user finished picking image(s) from the WP media library picker
- The user took a photo from the camera
- Tap "Choose from device" and pick some photos from the device library --> after the selection, it should go back to the edit product main screen instead of the edit product images screen …
> Image upload UX: after adding product images, automatically commit the changes locally

- WooCommerce/Classes/ViewRelated/Keyboard/KeyboardFrameObserver.swift
- WooCommerce/WooCommerceTests/ViewRelated/Keyboard/KeyboardFrameObserverTests.swift
Fixes #2173
I needed to debug a strange and inconsistent vertical alignment issue for #2245. But it's quite confusing because I keep getting events from _supposed-to-be-dead_ `KeyboardFrameObserver` 
instances. 😅 
Before making any changes to `KeyboardFrameObserver`, I added a **failing test** (dbb69be) to prove what we're trying to do here: we want to remove the observer from `NSNotificationCenter` when `KeyboardFrameObserver` is deallocated. 
And then I converted it to a `final class` in 94fec86. I used the selector-based `NSNotificationCenter` observation so we don't need any extra code to remove observers in `deinit`. 
Please test for possible regressions. 
1. Navigate to Orders → Search. 
2. Enter a search text that will return lots of Orders. 
3. Confirm that the table's content …
> Convert KeyboardFrameObserver to class

- .circleci/config.yml
- Gemfile.lock
- fastlane/Fastfile
- fastlane/Pluginfile
This PR sets up UI test runs on CircleCI and updates unit test runs to use Fastlane with the [test_center plugin](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center). Failed tests will be retried (up to 3 test runs) before reporting failures.
Unit test runs are the same as before except they are now run with Fastlane to enable retries on failure.
UI test runs are set up as follows:
* UI tests are run automatically on commits to `develop` and `release/*` branches. Failures are reported to the `#mobile-woo` Slack channel.
* UI tests can be run optionally on any PR, with results reported back to the PR.
I am adding Woo iOS developers and Platform9 team members as reviewers. Only one review is needed to ensure the changes work as expected, but it would be great to get at least …
> Testing: Add UI test setup on CI with Fastlane

- Podfile
- Podfile.lock
Ref. #2003 
Ref. https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/271
This PR removes the `.showLoginMethods` segue from `Login.storyboard` and presents the "3 button" view programmatically.
Note: although this view is not currently presented in Woo, we are keeping it up-to-date in case you'll need it when presenting SIWA as a login option. I realize the Login flows are currently being redesigned and this code may be obsolete soon.
1. Check out this branch
2. In `AuthenticatorManager`, add a new param: `showLoginOptionsFromSiteAddress: true` to the configuration.
3. `rake dependencies`
4. Build and run (run on a device if you wish to view the "Sign in with Apple" button)
5. Log out if logged in
6. Log In > Enter the site address... > choose a WP.com hosted site with Woo …
> UL&S: Remove .showLoginMethods segue from Site Address VC

- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Fixes #2232 
In `ProductFormViewController`, passed the `UIBarButtonItem` sender to the `presentMoreOptionsActionSheet` handler, and used the sender to set the action sheet's `popoverPresentationController`'s `barButtonItem`.
- Build the app on a tablet
- Open the Products tab
- Tap on a simple product (same from tapping a simple product in an order in the Orders tab order Top Performers)
- Tap on the "..." in the navigation bar and try rotating --> the popover should be fully visible
\ | before | after
-- | -- | --
modal - landscape | ![Simulator Screen Shot - iPad Air 2 - 2020-05-04 at 16 13 24](https://user-images.githubusercontent.com/1945542/80947675-3b69a400-8e23-11ea-80d8-a32899e123ad.png) | ![Simulator Screen Shot - iPad Air 2 - 2020-05-04 at 16 14 …
> Edit Products: fix "..." more menu popover appearance

- WooCommerce/Classes/ViewRelated/Products/Media/CameraCaptureCoordinator.swift
Fixes #2257
[Apple docs](https://developer.apple.com/documentation/photokit/phphotolibrary/1620736-requestauthorization?language=objc) say this:
> Photos may call your handler block on an arbitrary serial queue. If your handler needs to interact with user interface elements, dispatch such work to the main queue.
The crash was happening because we call the `completion` block right away (on a serial queue) and somewhere along the line we present a `UIAlertController`, which causes the crash. 
1. Delete the app from the device
2. Run the app
3. Navigate to Product → Photos → Add Photo → Pick from Library
4. Deny the permission request
5. Re-run the app
6. Navigate to Product → Photos → Add Photo → Camera
7. Confirm that there is no crash and you see this alert instead:
Only 1 reviewer is …
> CameraCaptureCoordinator: Call completion block on main thread

- WooCommerce/Classes/Extensions/UITableView+HeaderFooterHelpers.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformersViewController.swift
Hopefully fixes #1711.
Looking at the crash events of #1711, I'm betting that it is because we're using Ghost on the same `UITableView` used for showing real data in `TopPerformerDataViewController`. We've discovered a few months ago that this can cause race conditions (https://github.com/wordpress-mobile/WordPress-iOS/pull/12974) and crash the app. 
This PR adds a new [`GhostTableViewController`](https://github.com/woocommerce/woocommerce-ios/blob/d24dd81ee131cdc7331c6a1d29f56f32ca9903ec/WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift#L322) that serves as the ghost view of `TopPerformerDataViewController`. It is added and removed as a child ViewController:
https://github.com/woocommerce/woocommerce-ios/blob/d24dd81ee131cdc7331c6a1d29f56f32ca9903ec/Wo …
> Use a Separate Ghost VC for TopPerformerDataViewController

- Networking/Networking.xcodeproj/project.pbxproj
- Networking/Networking/Extensions/Result+Extensions.swift
- Networking/Networking/Network/AlamofireNetwork.swift
- Networking/Networking/Network/MockupNetwork.swift
- Networking/Networking/Network/Network.swift
- Networking/Networking/Network/NullNetwork.swift
- Networking/Networking/Remote/OrdersRemote.swift
- Networking/Networking/Remote/Remote.swift
- Networking/NetworkingTests/Remote/OrdersRemoteTests.swift
- Networking/NetworkingTests/Remote/RemoteTests.swift
- Networking/NetworkingTests/Testing/XCTestCase+Wait.swift
- Yosemite/Yosemite/Stores/OrderStore.swift
Closes #1926
I have a possibly huge `Action` incoming with multiple API requests for fixing #2254. I foresee it being hairy and the lack of `Result` would just make it hairier. 😄  
This adds `Result` callbacks for:
1. `Network`:
https://github.com/woocommerce/woocommerce-ios/blob/43ecd3e2eaa59def81751da3fa718aadf12f8088/Networking/Networking/Network/Network.swift#L43-L44
2. `AlamofireNetwork`:
https://github.com/woocommerce/woocommerce-ios/blob/43ecd3e2eaa59def81751da3fa718aadf12f8088/Networking/Networking/Network/AlamofireNetwork.swift#L59-L65
3. `Remote.enqueue`:
https://github.com/woocommerce/woocommerce-ios/blob/43ecd3e2eaa59def81751da3fa718aadf12f8088/Networking/Networking/Remote/Remote.swift#L96-L97
As a guinea pig, I changed `OrdersRemote.loadAllOrders` to now return a `Result` …
> Support Result<> Type

- WooCommerce/Classes/ViewRelated/BottomSheet/ListSelector/BottomSheetListSelectorPresenter.swift
- WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Wrapper for presenting a bottom sheet (discussion: https://github.com/woocommerce/woocommerce-ios/pull/2155#discussion_r412303534) for #2054 
From [a previous discussion in a PR on bottom sheet list selector](https://github.com/woocommerce/woocommerce-ios/pull/2155#discussion_r412303534) with @shiki, we thought adding a wrapper for presenting the bottom sheet list selector would abstract how the dismissal works for future changes/improvements. This PR created `BottomSheetListSelectorPresenter` as the wrapper that presents a bottom sheet list selector, so that its caller (`ProductsViewController`) doesn't have to know how `BottomSheetViewController` works with the child view controller and how the dismissal is implemented.
Just a check for regression:
- Tap on the …
> Create a wrapper to present `BottomSheetListSelectorPresenter`

- WooCommerce/Classes/ViewRelated/BottomSheet/ListSelector/BottomSheetListSelectorViewController.swift
iPad improvements to fit to height for #2054 
Configured `BottomSheetListSelectorViewController`'s `preferredContentSize` so that the popover fits to the content height 
- Launch the app on a tablet
- Tap on the "Sort by" CTA --> the popover should fit to the content height
device | before | after
-- | -- | --
iPad Air 2 (Dark) | ![Simulator Screen Shot - iPad Air 2 - 2020-05-12 at 14 07 16](https://user-images.githubusercontent.com/1945542/81644748-eb11c800-945a-11ea-91bd-88b5f8eaf099.png) | ![Simulator Screen Shot - iPad Air 2 - 2020-05-12 at 14 09 24](https://user-images.githubusercontent.com/1945542/81644762-f107a900-945a-11ea-8e5f-f1d6b648f311.png)
iPad Air 2 (Light) | ![Simulator Screen Shot - iPad Air 2 - 2020-05-12 at 14 07 …
> Update bottom sheet list selector to fit to content height

- WooCommerce/Classes/ViewRelated/Filters/FilterListViewController.swift
Update bottom CTA container background color so that it looks right in Light mode for #2037 
Update filter list screen background color to match the filter action container on devices with a notch
- Launch the app in a simulator/device with a notch (e.g. iPhone X series)
- Tap on the "Filter" CTA --> the background color covering the notch should match the color of the bottom CTA container in both Dark and Light modes
Note the difference at the notch area in Light mode!
mode | before | after
-- | -- | --
Light | ![Simulator Screen Shot - iPhone 11 - 2020-05-12 at 13 26 35](https://user-images.githubusercontent.com/1945542/81642305-a9325300-9455-11ea-974a-66076b15a8cd.png) | ![Simulator Screen Shot - iPhone 11 - 2020-05-12 at 13 32 …
> Update filter list screen background color to match the bottom CTA container

- WooCommerce/Classes/System/DefaultFeatureFlagService.swift
- WooCommerce/Classes/System/FeatureFlag.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
- WooCommerce/WooCommerceTests/Mockups/MockFeatureFlagService.swift
Fixes #1897 
This PR removes the unused `productList` feature flag, which is now obsolete after the Products Milestone 1 release.
> Removed productList feature flag

- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
CocoaPods was complaining about this XIB still being in the build phase. Xcode didn't show it at all so I removed it from the XML directly.
> [!] `<PBXResourcesBuildPhase UUID=`B56DB3C42049BFAA00D4AA8E`>` attempted to initialize an object with an unknown UUID. `0290E270238E3CE400B5C466` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
1. Before switching to this branch, perform a `bundle exec pod install`. Notice the warning.
2. Switch to this branch and do the same command. Notice no warning.
> Removes extraneous old XIB from build (not visible in Xcode)

- WooCommerce/Classes/ViewRelated/Filters/FilterListViewController.swift
- WooCommerce/Classes/ViewRelated/Filters/FilterListViewController.xib
Show discard changes action sheet when dismissing with outstanding changes on the filters for #2037 
In `FilterListViewController`, kept track of the original filtering criteria (now conforming to `Equatable`) from the view model, and used it to compare with the latest criteria when the user taps to dismiss the filter list UI
- Tap on the "Filter" CTA
- Tap on the "Dismiss" CTA --> it should go back to the Products tab without any prompt
- Tap on the "Filter" CTA again
- Tap into a row, select a different value, then tap "<" to go back to the filter list screen
- Tap on the "Dismiss" CTA --> a discard changes action sheet should show up
- Tap outside of the action sheet to go back to the filter list screen
- Tap on the "Clear all" CTA
- Tap on the "Dismiss" CTA …
> Show discard changes prompt when dismissing filter products screen with filter changes

- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Fixes #2284 
For all the possible actions in the product form more details bottom sheet, `editCategories` is now excluded when the Products M3 feature flag is off
Prerequisite: prepare a simple product that has non-empty data for all the M1/M2 features (inventory, shipping, short description), but no categories (M3 feature).
- Turn off M3 feature flag (e.g. in `DefaultFeatureFlagService`)
- Open the simple product as in the prerequisite --> there should be no "Add more details" CTA at the bottom; on `develop`, the CTA is shown and tapping on it brings up an empty action sheet / popover
before | after
-- | --
> Fix the potential empty more details bottom sheet when Products M3 feature flag is off

- WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewModel.swift
Fixes #2287 
- Added `numberOfLinesForDetails: Int` to `ProductFormSection.SettingsRow.ViewModel` with default value 0 (any number of lines since most of the settings rows have multiline details)
- Set `numberOfLinesForDetails` to 1 for the brief/short description row
- Tap on a simple product with multiline short description --> the short description row should show only one line 
before | after
-- | --
> Product short description row should show maximum one line

- WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
Fixes #2291
Super minor changes (just 1 line of code!) for adding an 8px padding between the "Limited editing available" banner and the first product
| Compact             |  Expanded |
> Added 8px padding between the "Limited editing available" banner and the first product

- WooCommerce/Classes/ViewModels/ProductDetailsViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/ProductDetailsFactory.swift
Fixes #2240 
If the product form is navigated from an order (e.g. from refund details or order details) we incorrectly use the order's currency which can be different from the site's currency.
Now in products, we use the site currency in all cases to be consistent with the price settings.
1) Open an order that uses a currency different from the one used by default on the website.
2) Open a product -> Make sure that the price showed uses the site currency
> Products: now we use always the site currency instead of order currency

- WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
Fixes #2295 
- Updated the copy when we show the stock status from `Stock status: \(stockStatus)` to just the stock status
- Additionally, I noticed a bug where we still show the stock quantity when stock management is disabled (`manageStock == false`). The logic to show the stock info:
- If stock management is enabled, we show the **stock quantity** if it's available
- Otherwise (stock management is disabled), we show the **stock status**
- Tap on a simple product
- Tap on the inventory settings row if available, or tap "Add more details" at the bottom to go to inventory settings
- Turn off the "Manage stock" switch and set the stock status
- Tap "Done" to go back to the product form --> the stock status selected in the previous step should be shown in the …
> Edit Product: update inventory row details text

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Products/ProductsTopBannerFactory.swift
- WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
- WooCommerce/Classes/ViewRelated/Top Banner/TopBannerView.swift
- WooCommerce/Classes/ViewRelated/Top Banner/TopBannerViewModel.swift
Fixes #2042 
- Added `isExpanded` to `TopBannerViewModel` and `ProductsTopBannerFactory` so that the initial expanded state can be customized
- Opened up `isExpanded` in `TopBannerView` to be readonly
- In `ProductsViewController`, kept a reference of the top banner view and initialized its expanded state to `false` by default and then the current expanded state when updating the top banner
- Go to the Products tab --> the WIP banner should be collapsed by default
- Go to "My store" tab, and flip the Products switch under Settings > Experimental Features
- Go back to the Products tab --> the WIP banner should stay in the collapsed state with a different message
- Tap on the "🔽" button in the WIP banner to expand
- Go to "My store" tab, and flip the Products switch under …
> Collapse the Products tab WIP banner by default

- RELEASE-NOTES.txt
This fixes the incorrectly placed release notes in https://github.com/woocommerce/woocommerce-ios/pull/2306. 
I merged that PR in `develop` today without checking if `release/4.3` has been cut. 🤦 I meant that PR to be in 4.4 but since `release/4.3` branch hasn't been cut yet, it's fine if #2306 is included in 4.3. 
> Move 4.4 release notes to 4.3

- WooCommerce/Classes/ViewRelated/Products/Edit Product/BottomSheetListSelector/ProductFormBottomSheetActionsFactory.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/BottomSheetListSelector/ProductFormBottomSheetListSelectorCommand.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/Products/BottomSheetListSelector/ProductFormBottomSheetActionsFactoryTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/BottomSheetListSelector/ProductFormBottomSheetListSelectorCommandTests.swift
Fixes #2302
- Since there 2 places that require the knowledge of the visible actions on the product form bottom sheet (the CTA visibility + bottom sheet list selector data), the duplicated actions logic from `ProductFormViewController` and `ProductFormBottomSheetListSelectorCommand` were now shared in `ProductFormBottomSheetActionsFactory`
- Updated `ProductFormViewController` to get the bottom sheet actions from `ProductFormBottomSheetActionsFactory` and passing them to `ProductFormBottomSheetListSelectorCommand`
- Updated unit tests
Prerequisite: prepare a simple product that is not virtual/downloadable (so that it has shipping settings) and its shipping data are all empty
- Go to Settings > Experimental Features, and turn off the Products feature switch
- Tap …
> Fix certain M1 settings aren't accessible if the data are empty when M2 feature switch is off

- WooCommerce/Classes/ViewRelated/Products/Edit Product/Shipping Settings/ProductShippingSettingsViewController.swift
Fixes #2263 
In `ProductShippingSettingsViewController`, kept track of the product's original shipping class which could be retrieved asynchronously later on. When the user navigates away from the shipping settings, compared the latest shipping class against the original shipping class instead of the product's shipping class, which could be `nil` if the relationship wasn't linked beforehand
Prerequisite: prepare a simple product with a shipping class
- Launch the app in a simulator/device that is not iOS 13.4 (due to an Apple bug https://github.com/woocommerce/woocommerce-ios/issues/2089 🤦🏻‍♀️)
- Log out and in to a store if you have loaded the shipping classes before
- Tap on the Product in the prerequisite
- Tap on the shipping settings row --> note the shipping …
> Products > shipping settings: fix unexpected discard changes prompt from shipping class retrieved later

- WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/BasicTableViewCell.swift
- WooCommerce/WooCommerceUITests/Screens/Login/LoginPasswordScreen.swift
Fixes #2253 
The UI tests were failing on local test runs, at least on some devices such as iPhone 6/8, due to two identified issues:
* cannot paste the password on the login screen (inconsistent failure)
* cannot log out (consistent failure due to multiple matches for the logout button)
The inconsistent nature of the password pasting issue makes it a little tricky to be confident about the fix, but I noticed that we had two unnecessary steps while entering the password:
1. We were checking for the existence of the password field twice. (Shouldn't affect the test results but it was making the test take longer than needed.)
2. We were tapping in the password field even though it already has focus. I removed this so we go immediately to a long tap to bring up the contextual menu with the …
> Testing: Fix local UI test runs

- docs/README.md
- docs/UI-TESTS.md
Based on @shiki's [feedback](https://github.com/woocommerce/woocommerce-ios/pull/2266#issuecomment-627561110) this moves the UI testing documentation into `docs/`. I made some small updates to that documentation and added links in the README to that doc and our instructions for joining the iOS beta program for beta testing.
This also sets us up to add the unit testing documentation described in https://github.com/woocommerce/woocommerce-ios/issues/2224.
Please confirm that the documentation is clear and all links still work.
Only 1 review is needed. @shiki I've added you as a reviewer since you had the original feedback about the location of the docs. I'm also open to any other suggested improvements!
> Move testing documentation to the docs directory

- Storage/Storage/Protocols/FileStorage.swift
- Storage/Storage/Tools/PListFileStorage.swift
- Storage/StorageTests/Tools/FileStorageTests.swift
- Yosemite/Yosemite/Stores/AppSettingsStore.swift
- Yosemite/YosemiteTests/Mockups/MockInMemoryStorage.swift
- Yosemite/YosemiteTests/Stores/AppSettingsStoreTests.swift
Prerequisite for #1388 
Currently, we have a `FileStorage` protocol for reading/writing data from/to local storage usually for some lightweight data (similar to the usage of `UserDefaults`). So far, our `AppSettingsStore`/`AppSettingsAction` uses a `FileStorage` implementation to read/write app settings - custom shipment provider under Order Details, and the switches under Settings > Experimental Features. We use a PList implementation `PListFileStorage` to persist the app settings, and a mock in unit tests. However, before this PR, `PListFileStorage` didn't actually have any PList logic - all it used to do was to read/write data from/to a file at a URL locally without the knowledge of PList file type. Instead, the PList logic used to be in `AppSettingsStore`. This PR moves the PList …
> Update PList storage implementation

- Networking/Networking/Model/MetaContainer.swift
- Networking/Networking/Remote/NotificationsRemote.swift
- Networking/Networking/Remote/ProductReviewsRemote.swift
- Networking/Networking/Remote/ProductsRemote.swift
- Yosemite/Yosemite.xcodeproj/project.pbxproj
- Yosemite/YosemiteTests/Mockups/Networking/Model/MockNote.swift
- Yosemite/YosemiteTests/Mockups/Networking/Model/MockProductReview.swift
- Yosemite/YosemiteTests/Mockups/Networking/Remote/MockNotificationsRemote.swift
- Yosemite/YosemiteTests/Mockups/Networking/Remote/MockProductReviewsRemote.swift
- Yosemite/YosemiteTests/Mockups/Networking/Remote/MockProductsRemote.swift
Still chugging away at #2254. It seems that we could use a lot of testing utilities. 😅 
I wanted to send this as a separate PR to control the size. My solution for #2254 including the contents of this PR was already at 650 lines and I was not even done writing unit tests. 😱 
The problem is that these are all testing utilities and are useless on their own. Let me know if that's not okay! 
I added mocks for some of the `Remote` classes that I needed to use in a test:
- [MockNotificationsRemote](https://github.com/woocommerce/woocommerce-ios/blob/issue/2254-add-remote-mocks/Yosemite/YosemiteTests/Mockups/Networking/Remote/MockNotificationsRemote.swift)
- [MockProductReviewsRemote](https://github.com/woocommerce/woocommerce-ios/blob/issue/2254-add-remote-mocks/Yosemite/YosemiteTests/Mockups/Ne …
> Add Mocks and Test Data

- WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/ProductImagesCollectionViewDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/ProductImagesHeaderTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/ProductImagesHeaderViewModel.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Fixes #1905 
- Per the description #1905, `ProductImagesViewModel` sounds quite generic and this PR renamed it to `ProductImagesHeaderViewModel` to match its usage in the header
The code changes were from a pass of straightforward renaming, just CI!
> Rename `ProductImagesViewModel` to `ProductImagesHeaderViewModel` to match `ProductImagesHeaderTableViewCell`

- WooCommerce/Classes/ViewRelated/Filters/FilterListViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Filters/FilterProductListViewModel.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/Products/Filters/FilterProductListViewModelProductListFilterTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Filters/FilterProductListViewModelTests.swift
Fixes #2037 
Most of the logic and nested structs are private in `FilterListViewController`, please lemme know if you think of any ways to test the view controller interactions!
- Added unit tests for `FilterTypeViewModel` creation from `FilterProductListViewModel.ProductListFilter` in `FilterProductListViewModelProductListFilterTests`
- Added unit tests for `FilterProductListViewModel`'s criteria calculation in `FilterProductListViewModelTests`
no user-facing changes, just CI!
> Add unit tests for filter product list view model

- Networking/Networking/Network/AlamofireNetwork.swift
Fixes #2337 
From the stack trace and crash reason (`Task created in a session that has been invalidated`), it seems related to the background session `backgroundSessionManager: Alamofire.SessionManager` in `AlamofireNetwork`. Since we initialize a background session manager on every login, and each login request [triggers the `AuthenticatedState` init](https://github.com/woocommerce/woocommerce-ios/blob/84b1a8cfd99043c410e7c24fc345637328fe130d/WooCommerce/Classes/Yosemite/DefaultStoresManager.swift#L90) twice, and we are assigning the same identifier to the session, the session gets invalidated and results in a crash when it's trying to make a network request on the invalidated background session.
I'm not super sure why each login action triggers `AuthenticatedState` init twice, there …
> Fix crash when uploading product images after logging in

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Keyboard/KeyboardScrollable.swift
Fixes #2334
- In product form (product details), the table view has `contentInsetAdjustmentBehavior` manually set to `never` because it's in a vertical stack view and the safe area adjustment should be handled by the constraint on the stack view (pinning the stack view bottom anchor to the safe area's bottom anchor). However, in the default implementation of `KeyboardScrollable` where we adjust the bottom inset for a scroll view from keyboard height changes, we used to always account for the safe area's bottom inset while there should be no adjustment when the keyboard is dismissed (keyboard height `0`). This PR made a special case for this specific scenario when the bottom inset should not include the safe area. When the keyboard is up, we still want to account for the safe area bottom …
> Fix product details screen cannot be scrolled to the bottom in landscape after keyboard is dismissed

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Fixes #2339 
- Set the product name to the navigation bar title on initialization and product updates
- Tap on a simple product --> the product name should be shown in the navigation bar
- Edit the product name --> the navigation bar title should change as you type that matches the product name text field
before | after
-- | --
> Edit Products: show product name in the navigation bar

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/ProductImagesHeaderTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/ProductImagesHeaderViewModel.swift
Fixes #2338 
On image status updates, the images collection view is scrolled to the beginning if there are any images that are still pending upload so that they are visible to the user
- Choose a photo or take one with camera --> it should go back to the product form and the selected photo should be visible with a spinner overlay
before | after
-- | --
> Edit Products: scroll to the beginning of product images if any are pending upload

- RELEASE-NOTES.txt
- WooCommerce/Classes/Extensions/UINavigationController+Woo.swift
Fixes #2333 
- When handling swipe back gesture in a view controller as a `UIGestureRecognizerDelegate`, this PR added a check on whether the view controller is the top view controller in the navigation back so that only the top view controller handles the swipe back gesture
- Enable the Products M2 features in Settings > Experimental Features if the switch was off before
- Go to the ellipsis menu > Product Settings
- Under "More Options" select Slug
- Edit the slug and swipe back to the main Product Settings screen --> it should go back to the Product Settings screen without the "Discard Changes" prompt
- Swipe back the Product Settings screen --> the "Discard Changes" prompt should now appear from the slug changes
- Repeat the above two …
> Product Settings: fix "Discard changes" prompt erroneously shown when swiping back from slug, purchase note, and menu order

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
Ref #https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/282
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/286
This uses the Auth branch to utilize the Google login refactor.  To note, there should be _no_ functional or visible changes. Testing is to verify nothing is broken.
To test:
---
**Test Case 1: Login with Google account**
1. Have an account that was created via the Google path (i.e so it is flagged as a social account).
2. Go to `Log In` > `Log in with Google`.
3. Walk through the Google account authentication.
4. Verify the Login Epilogue is displayed. (or whatever it looks like with a valid Woo account. 😄 )
---
**Test Case 2: Login with Google account that has 2FA enabled on the WP account**
1. Have the same kind of account as in …
> Update Auth to use Google login refactor.

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesViewController.swift
Fixes #2354 
Before this PR, we display the "Discard changes" prompt whenever there are any images pending upload or the product's images have changed. However, the user could still come back to the Edit Product Images screen after selecting a few photos for upload with the current UX. It doesn't make sense to show the "Discard changes" prompt in this case.
Since the only action that the user could change the product images on the Edit Product Images screen is the delete action (tapping on an image and then tapping the trash icon), this PR only shows the "Discard changes" prompt when the user has deleted any images.
- Tap on the "+" cell in the images header, then tap "Add Photos"
- Choose a photo or take one with camera --> it should go …
> Edit Product Images: "Discard changes" prompt now only appears when any images have been deleted

- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModel+ChangesTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModel+ObservablesTests.swift
- Yosemite/Yosemite/Model/Updaters/ProductUpdater.swift
Fixes #1985
Apology for the bigger PR than I expected! ~340 diffs are on the unit tests that have some boilerplates. `ProductFormViewController` didn't get significantly shorter from this PR (there are a bunch of unsaved changes logic that we can extract from the VC to a different class separately), but now the product/password states can be tested. Please feel free to suggest anything!
As we add more functionalities to Edit Products, the states in `ProductFormViewController` have got complicated (e.g. the two `password` properties that it manages from product settings). This PR extracted the editable data from `ProductFormViewController` to 
a new class `ProductFormViewModel` that provides UI data for `ProductFormViewController`.
- In `ProductFormViewController`, moved `originalProduct`, …
> Edit Product: extract view data logic from view controller to view model

- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
Fixes `develop` 🙇🏻‍♀️
There was a merge conflict in `ProductFormViewController` that I reminded myself when I code reviewed yesterday, but I forgot to make this change [in the PR](https://github.com/woocommerce/woocommerce-ios/pull/2348) before I merged it today. Next time I will add a checkmark in the PR that needs changes!
Since `originalProduct` state was moved from `ProductFormViewController` to `ProductFormViewModel` in https://github.com/woocommerce/woocommerce-ios/pull/2348, this PR added a function for this visibility check in `ProductFormViewModel`.
Just CI is good, but feel free to also test the visibility of "View product in store" action in the ellipsis menu in product details.
> Fix `develop` from merge conflicts

- WooCommerce/WooCommerceTests/Mockups/MockupTableView.swift
- WooCommerce/WooCommerceTests/Tools/ResultsControllerUIKitTests.swift
This just adds an additional test in `ResultsControllerUIKitTests`. I was using this to find the cause of #1543. I thought it would be a good permanent addition.  
I changed the `MockupTableView` so that it will always call `super` instead of just absorbing everything. This makes it closer to production behavior.
I also updated the `ResultsControllerUIKitTests` so it is a `UITableViewDataSource`. Again, this is to simulate how things work in production. 
The build passing should be good enough. 
> Add Additional Tests for ResultsController

- RELEASE-NOTES.txt
- Yosemite/Yosemite/Tools/ResultsController.swift
- Yosemite/YosemiteTests/Tools/ResultsControllerTests.swift
This is just an attempt in fixing #1543. 
We currently use `objects.count` when determining the number of rows in the section. 
https://github.com/woocommerce/woocommerce-ios/blob/9420a214faa675cd5eb5d36de1a4f6ac509f8cfa/Yosemite/Yosemite/Tools/ResultsController.swift#L266-L270
I found from these resources that `objects.count` can sometimes have a different value compared to [`numberOfObjects`](https://developer.apple.com/documentation/coredata/nsfetchedresultssectioninfo/1622289-numberofobjects):
- http://mikeabdullah.net/nsfetchedresultscontroller.html
- https://stackoverflow.com/a/39232007
- https://stackoverflow.com/q/3967895
Sadly, I have not been able to prove that this is the cause of the crash. 😞 
The [official Apple doc](https://developer.apple.com/documentation/coredata/nsfetched …
> Use NSFetchedResultsSectionInfo.numberOfObjects Instead of objects.count

- Podfile
- Podfile.lock
This PR updates the Pods from the `beta` release to the stable version in order to prepare for `4.4` code freeze.
> Update pods for release

- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Testing/XCTestCase+Assertions.swift
- WooCommerce/WooCommerceTests/Tools/ResultsControllerUIKitTests.swift
I added more test cases based on some of our assumptions.
https://github.com/woocommerce/woocommerce-ios/blob/5dd0dc967c7e5042dfd442496325ff4f0dae0262/WooCommerce/WooCommerceTests/Tools/ResultsControllerUIKitTests.swift#L259-L264
https://github.com/woocommerce/woocommerce-ios/blob/5dd0dc967c7e5042dfd442496325ff4f0dae0262/WooCommerce/WooCommerceTests/Tools/ResultsControllerUIKitTests.swift#L317-L333
I added `UIWindow` creations in the test cases. Without it, the `UITableView` will not actually crash if it ends up with an inconsistent state. The `UITableView` checks whether it is visible before doing any cell change. 
https://github.com/woocommerce/woocommerce-ios/blob/5dd0dc967c7e5042dfd442496325ff4f0dae0262/WooCommerce/WooCommerceTests/Tools/ResultsControllerUIKitTests.swift#L337-L338
The …
> Add More ResultsController+UIKit Tests

- Storage/Storage.xcodeproj/project.pbxproj
- Storage/Storage/CoreData/CoreDataManager.swift
- Storage/Storage/Protocols/CrashLogger.swift
- Storage/StorageTests/CoreData/CoreDataManagerTests.swift
- Storage/StorageTests/Mocks/MockCrashLogger.swift
- WooCommerce/Classes/ServiceLocator/ServiceLocator.swift
- WooCommerce/Classes/Tools/Logging/DefaultCrashLogger.swift
- WooCommerce/Classes/Tools/Logging/Dictionary+Logging.swift
- WooCommerce/Classes/Tools/Logging/SentryCrashLogger.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Tools/Logging/Dictionary+LoggingTests.swift
- Yosemite/Yosemite.xcodeproj/project.pbxproj
- Yosemite/YosemiteTests/Mockups/MockCrashLogger.swift
- Yosemite/YosemiteTests/Tools/ShippingSettings/StorageShippingSettingsServiceTests.swift
Fixes #2364 
Since only `WooCommerce` framework knows about `AutomatticTracks` framework and thus the `CrashLogging` helper is only accessible within `WooCommerce`. However, there are also cases we'd like to log crashes/messages in frameworks other than `WooCommerce` like Storage and Yosemite frameworks for any potential crashes (ref p91TBi-2PM-p2). This PR created a protocol for `WooCommerce` to implement with `AutomatticTracks`'s `CrashLogging` via Sentry, and pass this implementation to `CoreDataManager` as a start.
- Created a `CrashLogger` protocol in the Storage framework that allows logging a message of any severity level
- The naming is just following the implementation `CrashLogging` in `AutomatticTracks`, please lemme know if you think some other name would be more clear
- Added …
> Log messages/crashes in `CoreDataManager` in Storage framework

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift
- WooCommerce/Classes/ViewModels/Order Details/Refund Details/RefundDetailsViewModel.swift
- WooCommerce/Classes/ViewModels/Order Details/Refunded Products/RefundedProductsDataSource.swift
- WooCommerce/Classes/ViewModels/ProductDetailsCellViewModel.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/ProductDetailsTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/ProductDetailsTableViewCell.xib
- WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/OrderDetailsDataSourceTests.swift
⚠️ Requires #2381 to be merged first.
Refs #2281. 
This swaps the quantity shown on the right side with the item total. The header also now just says “Products” instead of “Product” and “QTY” on the right. According to #2281, the header should be using a white background. I'll get to that in a follow-up PR. 
There are no changes in the layout. 
@Garance91540 Should the font sizes of the SKU and "Quantity x Price" be bigger? I couldn't find an existing style of that in the app so I wasn't sure. 
Before | After 
After (Dark) | After (Large)
Since the Refunded Products view is using the same components as the Order Details, it is also affected by the changes too. 
Before | After 
@Garance91540 Please let me know if this is okay or not. 
1. …
> Order Details → Show Item Total on the Right Instead of Quantity

- Networking/Networking.xcodeproj/project.pbxproj
- Networking/Networking/Mapper/ProductCategoryMapper.swift
- Networking/Networking/Remote/ProductCategoriesRemote.swift
- Networking/NetworkingTests/Mapper/ProductCategoryMapperTests.swift
- Networking/NetworkingTests/Remote/ProductCategoriesRemoteTests.swift
- Networking/NetworkingTests/Responses/category.json
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Categories/ProductCategoryListViewModelTests.swift
- Yosemite/Yosemite/Actions/ProductCategoryAction.swift
- Yosemite/Yosemite/Stores/ProductCategoryStore.swift
- Yosemite/YosemiteTests/Stores/ProductCategoryStoreTests.swift
Part of #2000
In order to build the add product category screen, I need to do some groundwork first adding the network request for adding a new product category.
- Added the new `ProductCategoryMapper` + tests
- Added the new method “createProductCategory` in `ProductCategoriesRemote` + tests
- Added a new mock json `category.json`
- Added `addProductCategory` action in `ProductCategoryAction` and `ProductCategoryStore` + tests
- CI
> Product Categories: updated Network/Yosemite layers with create new ProductCategory request

- Storage/Storage.xcodeproj/project.pbxproj
- Storage/Storage/Model/MIGRATIONS.md
- Storage/Storage/Model/Product+CoreDataProperties.swift
- Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 28.xcdatamodel/contents
Storage layer change for #2200 
- Created a new model version 28 based on 27, and set v28 to the current model version
- Added `buttonText: String` for external products that corresponds to the `button_text` field in the [API response](https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties) (for non-external products, this field is empty)
Other than CI, it'd be nice to test migration from the previous model version:
- Launch the app from `develop` in logged in state
- Launch the app from the PR branch and sanity check as everything should work as before
> Storage schema update: add `buttonText` to `Product`

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewModels/Order Details/OrderDetailsViewModel.swift
- WooCommerce/Classes/ViewModels/Order Details/Refund Details/RefundDetailsViewModel.swift
- WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/Fulfillment/FulfillViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Product List Section/Product Details/ProductListViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/ProductLoaderViewController.swift
Fixes #2388 
When a product form is contained in `ProductLoaderViewController` (e.g. when opening a simple product from outside of the Products tab), the container VC's [navigation bar right items are set up to update to the latest value correctly in `viewDidLoad`](https://github.com/woocommerce/woocommerce-ios/blob/09741efe783fb6aacabba6036fe6fcdcfd5e0d54/WooCommerce/Classes/ViewRelated/Products/Edit%20Product/ProductFormViewController.swift#L99). However, after we add `ProductFormViewController` as a child VC in `ProductLoaderViewController`, it also assigns its title and right bar button items immediately after:
https://github.com/woocommerce/woocommerce-ios/blob/09741efe783fb6aacabba6036fe6fcdcfd5e0d54/WooCommerce/Classes/ViewRelated/Products/ProductLoaderViewController.swift#L177-L178 …
> Products: fix navigation bar not showing product name and ellipsis menu from outside of Products tab

- WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift
Requires #2389 to be merged first. Closes #2281. 
This changes the products section header title to use the plural term only if there is more than one product. 
More Than One | One Product Only
1. Navigate to an order containing one product. 
2. Confirm that the header shows “Product”. 
1. Navigate to an order containing more than one product. 
2. Confirm that the header shows “Products”. 
> Order Details → Use singular or plural "Products" section title

- WooCommerce/Classes/System/WooConstants.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/About/AboutViewController.swift
- fastlane/appstoreres/metadata/source/description.txt
Closes #2411 
Adds a simple link to the Automattic Privacy Policy section specific to CCPA for California users. I also added a link to the policy with some copy in the App Store description. I wish we could exclude this from all regions except the US, but it is what it is. Technically it's not for California residents but for people existing in California.
@loremattei and/or @jkmassel can you make sure I'm not doing something terrible here with the descriptions that'll break our translations?
1. Launch the app.
2. Log into the app.
3. Tap on Settings in My Store.
4. Tap on WooCommerce under ABOUT THE APP.
5. Verify each of the three links function as expected.
Known Issue: Safari on iOS isn't scrolling to the proper location on the page for the anchor.
> Adds a link to the California Privacy Policy for CCPA compliance.

- Storage/Storage/CoreData/CoreDataIterativeMigrator.swift
- Storage/Storage/CoreData/CoreDataManager.swift
- Storage/StorageTests/CoreData/CoreDataIterativeMigratorTests.swift
Logging for crash investigation for #2371 
The current logging for the Core Data init crash doesn't get us very far to understand how it went during the migration process before we call `loadPersistentStores` on a `NSPersistentContainer`. This PR aims to add more logging to the Core Data init crash logging for us to know more about the migration before the crash.
- In `CoreDataIterativeMigrator`, returns a tuple with an array of debug messages in addition to the success boolean
- In `CoreDataManager`, gathered debug messages from `migrateDataModelIfNecessary` including the call to `CoreDataIterativeMigrator` and included these debug messages under `"migrationMessages"` key in the "Additional data" logging ([example Sentry event](https://sentry.io/organizations/a8c/issues/1720861484/events/ …
> Add more logging for Core Data migration for crash investigation

- RELEASE-NOTES.txt
- WooCommerce/Classes/System/DefaultFeatureFlagService.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/Beta features/BetaFeaturesViewController.swift
- WooCommerce/Classes/ViewRelated/Products/ProductDetailsFactory.swift
- WooCommerce/Classes/ViewRelated/Products/ProductsTopBannerFactory.swift
Resolves #2420 
We [decided](https://a8c.slack.com/archives/CGPNUU63E/p1591881834062300) to enable for everyone from the next release all the functionalities under the Products Milestone 2. I updated the banner message showed in the product list, and I did all the changes to enable these new functionalities of the products and for hiding the product switch in the Experimental Features screen.
1. Run a build from `develop`, and enable the product switch under the "Experimental Features" screen.
2. Switch to this branch and run the app -> Make sure that you can update product images, product settings, viewing, and sharing a product.
3. Erase all contents and settings from your iOS simulator
4. Run the app from this branch
5. Make sure that the product switch under the "Experimental …
> Enabled Products Milestone 2 by default

- Gemfile.lock
- fastlane/Fastfile
- fastlane/Pluginfile
This PR updates the `code_freeze` lane to align it with the new flow we've been using lately where the beta pods are updated in the release branch. 
The changes reflects what we've done on WPiOS here: https://github.com/wordpress-mobile/WordPress-iOS/pull/14107.
To test: 
The hard way is described in the PR above, but since the only new action is `ios_check_beta_deps`, a good enough test would be to verify that it's correctly configured. 
In order to do this: 
- comment out all the stuff in `code_freeze` other than the last line.
- run `bundle exec fastlane code_freeze` and verify that it succeeds and that the list of the beta pods is printed out. 
> Update release tooling

- docs/README.md
Continuation of #2405. Ref p91TBi-2TB-p2. 
View the documentation [here](https://github.com/woocommerce/woocommerce-ios/tree/update/docs-for-copiable/docs)
> Add Documentation for Copiable Code Generation

- WooCommerce/Classes/ViewRelated/Top Banner/TopBannerView.swift
Part of #2410 
- Updated the top banner content stack view's trailing edge spacing from 10px to 16px
- Launch the app with stats v4 disabled (if not, you can turn off stats v4 in Settings > Experimental Features) --> the top banner should look good, and the "X" button is tappable
- Go to the Products tab --> the top banner should look good, and the chevron up/down button is tappable
(Please note the CTA position on the right of the top banner!)
tab | before | after
-- | -- | --
Products top banner | ![Simulator Screen Shot - iPhone 11 - 2020-06-15 at 11 06 40](https://user-images.githubusercontent.com/1945542/84614884-0492ad80-aefa-11ea-9a1d-fc58a9eab4df.png) | ![Simulator Screen Shot - iPhone 11 - 2020-06-15 at 11 07 32](https://user-images.githubusercontent.com/1945542/84614897-0b212500- …
> Update top banner trailing edge spacing from 10px to 16px

- .circleci/config.yml
This PR adds a Slack notification that posts the results of the release build. 
> Add slack notification to release builds

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
Fixes #2434 
Fixes #2443 
- In `DefaultProductFormTableViewModel`, removed the check on `product.price` where we still show the price details if the `price` is non-empty. Since `product.price` is readonly and only set by the server (the current price that could be either the regular or sale price), its value could be outdated when the product has unsaved changes in the app (issue #2443)
- When the price details are empty, "Add Price" title is shown instead
- Tap on a simple product with a price --> should see the price row with the regular price
- Tap on the price row
- Remove regular and sale price, and tap "Done" --> the price row now should show "Add Price"
product has a price | product has no price
-- | --
> Edit Products: update price row when price details are empty

- WooCommerce/Classes/ViewRelated/ListSelector/PaginatedListSelectorViewController.swift
- WooCommerce/Classes/ViewRelated/Notifications/DefaultReviewsDataSource.swift
- WooCommerce/Classes/ViewRelated/Notifications/ReviewsViewModel.swift
- WooCommerce/Classes/ViewRelated/Orders/Order Details/Order Summary Section/Edit Order Status/OrderStatusListViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
- WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
- WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchStarterViewController.swift
- WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift
Related: https://github.com/woocommerce/woocommerce-ios/issues/1543
For the past 7 months(or more!) users have been [experiencing a crash](https://github.com/woocommerce/woocommerce-ios/issues/1543) where a table view ended with an inconsistent state after updating/deleting rows.
After much experimentation, @shiki have been able to reproduce a [scenario](https://gist.github.com/shiki/9c5627b23eed8085c297cf6aeae45a62) where this crash happens. 
Our hypothesis is that the table has the wrong `ResultsController` state initially and then receiving new events from FRC makes it inconsistent and crash.
In order to prevent this from happening we need to make sure that the table view is in sync with the `ResultsController` immediately after a `performFetch` is executed.
So after all `performFetch` …
> Call reloadData after performFetch executions

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewModels/ProductDetailsViewModel.swift
Fixes #2450 
- Removed the `totalOrders` row and its related logic from `ProductDetailsViewModel`, since we aren't showing the total orders on the editable product form in the long term either
- Tap on a variable product --> the total orders row shouldn't be visible anymore
(Note that the total orders row is gone!)
before | after
-- | --
> Remove total orders row from readonly product details

- Storage/Storage/CoreData/CoreDataIterativeMigrator.swift
Logging improvement for #2371 for release 4.5
I took a look at the [log events for the Core Data crash from release 4.5 beta build](https://sentry.io/organizations/a8c/issues/1711092978/events/?project=1458804&query=release%3A4.5.0.0&statsPeriod=14d) where we started logging the migration process, and noticed that the app was migrating first from model v0 (the first version) to model v1:
```
⚠️ [CoreDataManager] Migration required for persistent store
⚠️ Attempting migration from Model to Model 2
☠️ [CoreDataManager] Unable to migrate store.
```
It's quite unlikely that the app was first on model v0, and I saw that we were using the index from the array of **models to migrate** (model versions between the source and destination models) for the array of all model names.
This PR fixed the …
> Fix the model name in debug messages for Core Data crash investigation

- Networking/Networking/Model/Product/Product.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit External Link/ProductExternalLinkViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Error Handling/TitleAndTextFieldTableViewCell.ViewModel+State.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/Product+InventorySettingsViewModels.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/TextFieldContentAlignment.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/TextFieldTextAlignment.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/TitleAndTextFieldTableViewCell.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModel+UpdatesTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/ReusableViews/TextFieldTextAlignmentTests.swift
"editable product link" for #2200 
- Encoded `externalURL` and `buttonText` for updating an external product
- Added a function to update `externalURL` and `buttonText` in `ProductFormViewModel` + test case
- Created `ProductExternalLinkViewController` that enabled editing the external URL and button text fields for an external product
- Created an enum `TextFieldContentAlignment` for different ways of text field content alignment for the text and placeholder (I was debating between this name and `TextFieldTextAlignment`, lemme know if you think another name would sound more clear!)
- Because `NSTextAlignment` only has `left`/`right` instead of `leading`/`trailing` that takes LTR/RTL layout into account, this enum is mapped to `NSTextAlignment` based on the app layout
- Added …
> External products: external link & button text

- Rakefile
If CocoaPods' local specs repo out-of-date, `pod install` might not find some of the specified pods and fail.
The `--repo-update` flag make CocoaPods always update its local specs repo, so that that kind of failure won't happen.
This does add a few seconds to the task, but I feel it is time well spent because it will save a lot more time troubleshooting a failure in `rake dependencies` which might not be obvious to someone not used to dealing with CocoaPods.
First, you'll need to modify the `Podfile` or `Podfile.lock` otherwise the `dependencies` task won't run `pod install` in the first place.
When running `pod install`, you should see it being called with the `--repo-update` option.
---
> Use --repo-update flag when running pod install from Rake

- Networking/Networking/Network/NetworkError.swift
- Storage/Storage/Protocols/StorageType.swift
- Yosemite/Yosemite.xcodeproj/project.pbxproj
- Yosemite/Yosemite/Actions/ProductReviewAction.swift
- Yosemite/Yosemite/Stores/ProductReview/RetrieveProductReviewFromNoteUseCase.swift
- Yosemite/Yosemite/Stores/ProductReviewStore.swift
- Yosemite/YosemiteTests/Mockups/Networking/Remote/MockNotificationsRemote.swift
- Yosemite/YosemiteTests/Mockups/Networking/Remote/MockProductReviewsRemote.swift
- Yosemite/YosemiteTests/Mockups/Networking/Remote/MockProductsRemote.swift
- Yosemite/YosemiteTests/Stores/ProductReview/RetrieveProductReviewFromNoteUseCaseTests.swift
Refs #2254. This continues #2326. When the UI part of this (up next) is done, instances of #1907 should no longer be happening for push notifications. 
The crash log in #2326 suggests that the app was presenting a push notification while the `syncingCoordinator.delegate` was not set. This means that the view was not loaded yet. It's particularly odd because the view **should** have been loaded already since we [switch to the Reviews tab](https://github.com/woocommerce/woocommerce-ios/blob/a60d39bca5e065db153a0f38379eb3a73e176adf/WooCommerce/Classes/ViewRelated/MainTabBarController.swift#L306-L310) before doing any presentation. iOS disagrees. 
I also found that when presenting a review push notification, this flow happens:
In my opinion, this is very inefficient and has quite a few points …
> Add ProductReviewAction.retrieveProductReviewFromNote

- Storage/Storage.xcodeproj/project.pbxproj
- Storage/StorageTests/CoreData/CoreDataIterativeMigratorTests.swift
- Storage/StorageTests/Testing/XCTestCase+Wait.swift
Migration from model version 26 to 27 and attempted improvement for #2371 
Our Sentry crash logs indicated that most of the crashes were migrating from model version 26 to 27 (*). While inspecting the [Core Data v26 to v27 mapping model](https://github.com/woocommerce/woocommerce-ios/blob/9e605417971a9dda9333b8f63c8b00d83b2de598/Storage/Storage/Model/WooCommerceModelV26toV27.xcmappingmodel/xcmapping.xml), I noticed that `ProductCategory` is still in the XML even though it was removed in Xcode. The `ProductCategory` entry had the same `mappingnumber` value at 24 (the position in the mapping entity list) as `Account`, and I just had a slight suspicion that the duplicate entry in the XML might cause some issues in the migration process for certain devices.
- This PR removed `ProductCategory` …
> Remove `ProductCategory` entry from model 26 to 27 mapping model XML with a test case

- WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsVersionStateCoordinator.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/Beta features/BetaFeaturesViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Top Banner/TopBannerView.swift
- Yosemite/Yosemite/Actions/AppSettingsAction.swift
- Yosemite/Yosemite/Stores/AppSettingsStore.swift
- Yosemite/YosemiteTests/Stores/AppSettingsStoreTests+StatsVersion.swift
closes #2452 
As a result of #2467 there is not need to keep the "Improved Stats" feature toggle switch as well as the "Experimental Features"  row on settings since there isn't any on-going experiment.
- Remove the `stats` sections on the `configureSections` method of `BetaFeaturesViewController`
- Return `false` on `couldShowBetaFeaturesRow` method of `SettingsViewController`
- Removed dead code as a result of those deletions.
- Load the app and see that the "Experimental Features" row on sections is hidden.
> Remove stats experiment switch

- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 20.xcdatamodel/contents
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 21.xcdatamodel/contents
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 22.xcdatamodel/contents
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 23.xcdatamodel/contents
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 24.xcdatamodel/contents
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 25.xcdatamodel/contents
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 26.xcdatamodel/contents
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 27.xcdatamodel/contents
- Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 28.xcdatamodel/contents
- Storage/StorageTests/CoreData/CoreDataIterativeMigratorTests.swift
Fixes #1372 
Set the transformer to `NSSecureUnarchiveFromData` for `Transformable` attributes for model versions 20-28. For model versions below 20, the diffs are crazy large probably due to different Xcode versions so I didn't 
- Property ‘options’ on Entity ‘ProductAttribute’
- Property ‘crossSellIDs’ on Entity ‘Product’
- Property ‘groupedProducts’ on Entity ‘Product’
- Property ‘relatedIDs’ on Entity ‘Product’
- Property ‘upsellIDs’ on Entity ‘Product’
- Property ‘variations’ on Entity ‘Product’
Please test migration from an earlier model version on an iOS 13 simulator/device, the earlier the better but not earlier than release 2.8.0.0 (model version 20), and make sure no warnings show up in the console about the transformer like in #1372. However, I saw a separate warning that I …
> Set transformer to `NSSecureUnarchiveFromData` for model versions 20-28 to fix warnings on iOS 13

- Storage/Storage/CoreData/CoreDataIterativeMigrator.swift
- Storage/Storage/CoreData/CoreDataManager.swift
Part of #2371 
Since we really see a flood of crashes on Sentry and mentions on App Store reviews, I think removing the `fatalError` when the app fails to back up the store (removing and copying the pre-existing store) would be a good first step. After checking the [crash events from release 4.5](https://sentry.io/organizations/a8c/issues/1711092978/events/?project=1458804&query=release%3A4.5%2A&statsPeriod=14d), it seems like the crashes weren't only migrating from model version 26 to 27 but also from 27 to 28. Now that we know lots of users couldn't get past the backup step, I think it'd be great to know whether the [retry of persistent store loading](https://github.com/woocommerce/woocommerce-ios/blob/8a982eb73f30057aa1fa55c2c0f6f6003f6b8d97/Storage/Storage/CoreData/CoreDataManager.swif …
> Remove `fatalError` in case of persistent store backup failure and add more logging to store migration

- WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersPeriodViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift
- WooCommerce/WooCommerceScreenshots/WooCommerceScreenshots.swift
- WooCommerce/WooCommerceUITests/Screens/MyStore/PeriodStatsTable.swift
- WooCommerce/WooCommerceUITests/Screens/Settings/SettingsScreen.swift
Today, after merging #2467 and #2452 we noticed that some UITests began to fail. This happened because we forgot to update the UITests to reflect the new behavior of the project.
- We removed code that was trying to open the beta features screen in tests. In `WooCommerceScreenshots` and `SettingsScreen`
- Updated `StoreStatsAndTopPerformersPeriodViewController` to asign the correct `accesibilityIdentifier` property to be found by UITests.
- Run UITests
PS: ScreenshotTests currently compile and run but fail around the product screenshots.
> Fixes UITests around stats and beta features

- WooCommerce/Classes/Extensions/UIViewController+Helpers.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Categories/Add Category/AddProductCategoryViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Categories/Add Category/AddProductCategoryViewController.xib
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Categories/Add Category/ProductParentCategoriesViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Categories/Add Category/ProductParentCategoriesViewController.xib
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Categories/ProductCategoryListViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Categories/ProductCategoryListViewController.xib
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Categories/ProductCategoryListViewModel.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/TextFieldTableViewCell.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Categories/ProductCategoryListViewModelTests.swift
Resolves #2000 
This PR implements the last part for completing the management of Product Categories (part of Products Milestone 3). In particular, in this PR it's possible to create a new product category and to select a parent category.
- The `addCloseNavigationBarButton:` method helper now accept also a custom title.
- Implemented the `AddProductCategoryViewController`
- Implemented the `ProductParentCategoriesViewController`
- `ProductCategoryListViewController` now contains the new “Add Button” on top of the view.
- Implemented a new method `addAndSelectedNewCategory:` in `ProductCategoryListViewModel`
- `TextFieldTableViewCell` now contains a new method `resignFirstResponder:`
1. Open a product with or without product categories
2. Open the Product Categories screen
3. Tap "Add …
> Products (M3): Add a new Product Category

- WooCommerce/Classes/ViewRelated/Products/ProductsTopBannerFactory.swift
Fixes #2495 
Updated the copy for the Products banner to match the design for Milestone 2 release. There's a chance that this won't get translated in time for the release in a week.
cc: @loremattei @jkmassel @oguzkocer We'll need to do another beta release with this change.
> Update the product banner to match M2 designs

- Storage/StorageTests/CoreData/CoreDataIterativeMigratorTests.swift
On `develop` branch, we have a failing test on `CoreDataIterativeMigrator` after that I merged [this PR](https://github.com/woocommerce/woocommerce-ios/pull/2486). Something changed before the PR was merged, so I need to update how the `iterativeMigrate:` method works.
- CI
> Fix: failing test on `develop` about CoreDataIterativeMigrator

- WooCommerce/Classes/ViewRelated/Dashboard/Factories/DashboardTopBannerFactory.swift
- WooCommerce/Classes/ViewRelated/Products/ProductsTopBannerFactory.swift
- WooCommerce/Classes/ViewRelated/Top Banner/TopBannerView.swift
- WooCommerce/Classes/ViewRelated/Top Banner/TopBannerViewModel.swift
Refers to https://github.com/woocommerce/woocommerce-ios/issues/2464
The new deprecated stats banner is supposed to be expandable and actionable which is something our current `TopBannerView` does not support.
This PR aims to add such functionality to be able to dismiss the banner.
The implementation of that feature can be found [here](https://github.com/woocommerce/woocommerce-ios/pull/2503)
1. Add a new enum to `TopBannerViewModel` to indicate which type of button we want with it's respective handler.
```swift
enum TopButtonType {
case chevron(handler: (() -> Void)?)
case dismiss(handler: (() -> Void)?)
}
```
This allows us to remove the previous `onDismiss` and `onExpandedStateChange` parameters on `TopBannerViewModel`
2. Reorganize the internal view layout to be able to hide the …
> Update TopBannerView to be expandable and actionable

- WooCommerce/Classes/ViewRelated/Dashboard/Factories/DashboardTopBannerFactory.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Factories/DashboardUIFactory.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Stats v3/DashboardStatsV3ViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift
Depends on https://github.com/woocommerce/woocommerce-ios/pull/2502
Fixes https://github.com/woocommerce/woocommerce-ios/issues/2464
Users should be able to dismiss the deprecated stats banner and be reminded about it in the next app launch.
- Leverage on the changes made on #2502 to be able to have an actionable and expandable stats banner
- Track the "remind me later" state in a simple in-memory variable `preventStatsBannerToBeShown` in `DashboardStatsV3ViewController.swift`. Since that VC would be removed soon (After Sept 1st) I decided that this simpler approach is good enough. But let me know if you think there is a better/robust way to handle this.
- Launch the app with an old woo commerce store or by [disabling the wc-admin …
> Allow stats banner to be dismissed

- WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersViewModel.swift
- WooCommerce/WooCommerceTests/ViewRelated/Orders/OrdersViewModelTests.swift
- Yosemite/Yosemite/Tools/ResultsController.swift
- Yosemite/YosemiteTests/Tools/ResultsControllerTests.swift
Fixes #2241. 
My attempts at fixing #2241 didn't work. Even though [we're calling `performFetch` on `viewDidLoad`](https://github.com/woocommerce/woocommerce-ios/blob/10eb6cf847c11da1179dab35fb04f7854610271a/WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift#L118), the crash log still indicate that somehow, the user is able to _select_ something before `performFetch` is called.
I could not reproduce the crash but we can pinpoint that the crash happens when [`NSFetchedResultsController.object(at:)` is accessed](https://github.com/woocommerce/woocommerce-ios/blob/10eb6cf847c11da1179dab35fb04f7854610271a/Yosemite/Yosemite/Tools/ResultsController.swift#L129).
https://github.com/woocommerce/woocommerce-ios/blob/10eb6cf847c11da1179dab35fb04f7854610271a/Yosemite/Yosemite/Tools/Resu …
> Add ResultsController.safeObject(at:)

- WooCommerce/Classes/Extensions/UIImage+Woo.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/BottomSheetListSelector/ProductFormActionsFactory.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/BottomSheetListSelector/ProductFormBottomSheetAction.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Product+ProductForm.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormSection+ReusableTableRow.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
- WooCommerce/WooCommerceTests/Extensions/IconsTests.swift
- WooCommerce/WooCommerceTests/Mockups/MockProduct.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/BottomSheetListSelector/ProductFormActionsFactory+NonEmptyBottomSheetActionsTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormActionsFactory+EditProductsM3Tests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModel+ChangesTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModel+ObservablesTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModel+UpdatesTests.swift
Part of #2081 
In this PR, I handled the logic for showing/hiding the Tags cell in the Edit Product screen, and the logic for showing the "Tags" cell in the bottom action sheet. No actions are supported at the moment.
- Modified `ProductFormActionsFactory` to support tags
- Modified `ProductFormBottomSheetAction` to support edit tags
- Modified `DefaultProductFormTableViewModel` to support tags
- Implemented a utility method `tagsDescription:` that returns a comma-separated string with each tag names, used in the Product Tags cell.
- Makes all the changed to show Tags in the Edit Product Screen
- Implemented `updatedProductTags:` method in `ProductFormViewModel` which returns a copy of the product with tags updated.
- `MockProduct` now accepts tags.
- Updated test cases with the support …
> Edit Product: Tags Cell and appearance logic

- docs/README.md
A couple of months ago, we agreed that it is acceptable to use `*Protocol` in protocol names. This documents that agreement. I'm sorry it's a little bit late though. 😅 
Ref: CGPNUU63E-p1590167145050700-slack
😱 Sorry for the other line changes. VS Code automatically removed the extra spaces. Only the **Naming Convention** should be new. 
Review the documentation [here](https://github.com/woocommerce/woocommerce-ios/tree/docs/add-protocol-naming/docs#naming-conventions). Please let me know if I missed anything. 
> Document Protocol Naming Convention

- Networking/Networking/Remote/NotificationsRemote.swift
- Networking/Networking/Remote/ProductReviewsRemote.swift
- Networking/Networking/Remote/ProductsRemote.swift
- Yosemite/Yosemite/Stores/ProductReview/RetrieveProductReviewFromNoteUseCase.swift
- Yosemite/Yosemite/Stores/ProductStore.swift
- Yosemite/YosemiteTests/Mockups/Networking/Remote/MockNotificationsRemote.swift
- Yosemite/YosemiteTests/Mockups/Networking/Remote/MockProductReviewsRemote.swift
- Yosemite/YosemiteTests/Mockups/Networking/Remote/MockProductsRemote.swift
Following up on the protocol naming convention described in #2524, I'm renaming these silly `*EndpointsProviding` protocols that I created to just `*RemoteProtocol`. 
I thought I'd name these right away to prevent ourselves from copying that name in the future. "Endpoints Providing" really doesn't mean anything. I just invented that phrase. 😁 
There are no functional changes. Confirming that the build passes should be good enough. 
> Fix Remote Protocols Naming

- WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift
- WooCommerce/Classes/Authentication/Epilogue/SwitchStoreNoticePresenter.swift
- WooCommerce/Classes/ViewRelated/MainTabBarController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Authentication/Epilogue/SwitchStoreNoticePresenterTests.swift
- WooCommerce/WooCommerceTests/Mockups/MockNoticePresenter.swift
- WooCommerce/WooCommerceTests/Testing/XCTestCase+Assertions.swift
Ref #2254. 
I needed to use `SwitchStoreUseCase` and `SwitchStoreNoticePresenter` for my [WIP branch](https://github.com/woocommerce/woocommerce-ios/compare/issue/2254-fix-review-push-navigation?expand=1) for #2254. I wanted to write a unit test involving `SwitchStoreNoticePresenter` but I needed to be able to inject `NoticePresenter`. This can be tricky because it's using `ServiceLocator` **inline** instead of injection. 
https://github.com/woocommerce/woocommerce-ios/blob/02d00261738596044f92c91b84d6d9a18873adc6/WooCommerce/Classes/Authentication/Epilogue/SwitchStoreNoticePresenter.swift#L20
It's always better to inject it directly without relying on another third-party (ServiceLocator). 
This PR refactors `SwitchStoreNoticePresenter` a bit so that:
- Dependencies can be injected
- …
> Allow Injection of Dependencies for SwitchStoreNoticePresenter

- .circleci/config.yml
Closes #2471. 
I attempted to upgrade the Xcode version in #2190 but we decided that we have to get #2138 resolved first. After some deliberation, we decided that we should just push through with the upgrade since:
- #2138 only happens on iOS 12.
- We're dropping iOS 12 very soon anyway.
- We weren't sure if it's really a problem because we're having trouble reproducing it. 
Ref: C70PAM3RA-p1594949432474000-slack
Please see the description in https://github.com/woocommerce/woocommerce-ios/pull/2190 for why we would like to upgrade the Xcode version.
This PR upgrades the Xcode version in CircleCI to 11.5.0. At this time, it's a GM version which I think should be fine? I also upgraded the iOS simulator to 13.5. 
I believe checking if the build passed is good enough. Unit tests and UI tests …
> CircleCI: Update Xcode to 11.5.0

- Networking/Networking/Model/Copiable/Models+Copiable.generated.swift
- Networking/Networking/Model/Product/Product.swift
- Networking/Networking/Model/Product/ProductVariation.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/Product+InventorySettingsViewModels.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventoryEditableData.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventorySettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
- WooCommerce/WooCommerceTests/Mockups/MockProduct.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModel+UpdatesTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/ProductsTabProductViewModelTests.swift
- Yosemite/Yosemite/Model/Storage/Product+ReadOnlyConvertible.swift
- Yosemite/YosemiteTests/Mockups/MockProduct.swift
- Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Prerequisite for #2085 
- In Networking layer:
- Updated `ProductVariation` to conform to `GeneratedCopiable`
- Updated `Product.stockQuantity` from `Int?` to `Int64?` and updated its current usage in Networking & Yosemite layers
- The reason for this change: I'm planning to create a data model protocol (temporarily called `ProductFormDataModel`) that both `Product` and `ProductVariation` conform to so that `ProductFormViewController` and its view model can support both product model types. However, before this PR `ProductVariation.stockQuantity` is `Int64?` while `Product.stockQuantity` is `Int?`. `Int` is `Int64` underneath but they are considered different types in Swift, so I updated `Product.stockQuantity` to use `Int64` as in `ProductVariation.stockQuantity` to be more explicit.
- …
> Copiable `ProductVariation` and update `Product.stockQuantity` type from `Int?` to `Int64?`

- Networking/Networking/Model/Product/Product.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsRows.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsSections.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormViewModel+UpdatesTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Settings/ProductSettingsSectionsTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Settings/ProductSettingsViewModelTests.swift
- Yosemite/Yosemite/Model/Products/ProductSettings.swift
Fixes #2514 
As part of Milestone 3, we want to give to users the ability to update a simple product from physical to virtual and viceversa. In this PR I added a new cell under the section "Publish Settings" in Product Settings, which allows the user to change the virtual status of the product.
1. Lunch the app, and navigate to a simple product's detail.
2. Open product settings, and edit the "Virtual Product" flag.
3. Save the product, and make sure the changes are applied correctly, also on the web.
1. Lunch the app, and navigate to a NON-simple product's detail (for example, a grouped product).
2. Open product settings, and make sure that the "Virtual Product" cell is not shown.
3. Edit a setting on this product, and make sure that the changes are applied correctly, also on the web.
1. …
> Product Settings: switch to update whether a simple product is physical/virtual

- .circleci/config.yml
This PR fixes a small issue with the new XCode 11.5 CircleCI image where the release builds fail because Python 2 has been removed (according to https://discuss.circleci.com/t/xcode-11-5-gm-released/36029)
We didn't use it anyway, but the unlink step now fails and makes the build fail. The fix is as simple as remove the unlink step. 
1. Checkout a new branch from this one. 
2. Update the app version, making sure to use a version older than 4.6 and to only update the build number. Please make sure you're not using any version number we may need in production because the build will be uploaded to TestFlight. 
3. Commit your changes and push the branch.
4. Tag your version with a beta tag (4 numbers) and push the tag.
5. Check on CircleCI that the release builds succeeds. 
6. **Cleanup**: …
> Fix release builds on XCode 11.5 image

- Networking/Networking/Remote/ProductsRemote.swift
- Networking/NetworkingTests/Remote/ProductsRemoteTests.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
- Yosemite/Yosemite/Actions/ProductAction.swift
- Yosemite/Yosemite/Stores/ProductStore.swift
- Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Prerequisite for #2085
- Updated `updateProduct` completion block to return a `Result<Product, Error>` in Networking layer, and `Result<Product, ProductUpdateError>` in Yosemite layer. Updated related tests
- Moved `updateProduct` action from `ProductFormViewController` to `ProductFormViewModel` so that `func updateProductRemotely` can be in a protocol implemented with both `Product` and `ProductVariation`
Please sanity check on updating a product remotely:
- Tap on a simple product
- Try updating any supported fields (e.g. name, images, description, price, inventory, shipping)
- Tap "Update" --> the product should be updated remotely
> Refactoring on `updateProduct` in preparation for sharing product form logic with `ProductVariation`

- WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Stats v3/DeprecatedStatsDashboardViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersMasterViewController.swift
- WooCommerce/Classes/ViewRelated/ReusableViews/EmptyStateViewController/EmptyStateViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Testing/MockZendeskManager.swift
- WooCommerce/WooCommerceTests/ViewRelated/ReusableViews/EmptyStateViewController/EmptyStateViewControllerTests.swift
Closes #2535. 
In https://github.com/woocommerce/woocommerce-ios/pull/2521, Ernesto implemented the empty state shown if the user is still using WC < 4.0. The empty state implemented in that PR currently opens a URL about WCiOS. This PR changes that so that the Zendesk Contact Us page is shown instead.
I added a new `Config` option, [`withSupportRequest`](https://github.com/woocommerce/woocommerce-ios/blob/80f94af5719219b361f77ae94e41a733eb0875e6/WooCommerce/Classes/ViewRelated/ReusableViews/EmptyStateViewController/EmptyStateViewController.swift#L276-L280). When used, this option: 
- Shows all the UI elements
- Shows a text-style button (like the one implemented in #2521)
- Shows the Zendesk “Contact us” page when the button is tapped. 
I contemplated allowing consumers to specify a …
> Stats: Show Contact Us Page When "Contact Us" Button is Tapped

- Networking/Networking.xcodeproj/project.pbxproj
- Networking/Networking/Mapper/ProductVariationMapper.swift
- Networking/Networking/Model/Product/ProductVariation.swift
- Networking/Networking/Remote/ProductVariationsRemote.swift
- Networking/NetworkingTests/Mapper/ProductVariationMapperTests.swift
- Networking/NetworkingTests/Remote/ProductVariationsRemoteTests.swift
- Networking/NetworkingTests/Responses/product-variation-update.json
- Yosemite/Yosemite.xcodeproj/project.pbxproj
- Yosemite/Yosemite/Actions/ProductVariationAction.swift
- Yosemite/Yosemite/Stores/ProductVariationStore.swift
- Yosemite/YosemiteTests/Mockups/MockProductVariation.swift
- Yosemite/YosemiteTests/Mockups/Networking/Remote/MockProductVariationsRemote.swift
- Yosemite/YosemiteTests/Stores/ProductVariationStoreTests.swift
Yosemite/Networking changes for #2085 
Note: a bunch of diffs are from JSON and sample `ProductVariation` response!
- Networking layer:
- Created `ProductVariationMapper` that maps a response to a single `ProductVariation` with unit tests
- Updated `ProductVariation` to be `Codable` that encodes in a similar way to `Product`
- In `ProductVariationsRemote`, added `updateProductVariation` for updating a product variation. Also, created a protocol `ProductVariationsRemoteProtocol` that `ProductVariationsRemote` conforms to for unit tests
- Yosemite layer:
- Added `ProductVariationAction.updateProductVariation`
- In `ProductVariationStore`, implemented `updateProductVariation`
- Created `MockProductVariation` and `MockProductVariationsRemote` for unit tests
This PR doesn't affect existing …
> Yosemite/Networking: add `updateProductVariation` action

- Networking/Networking/Remote/ProductsRemote.swift
- WooCommerce/Classes/ViewRelated/ListSelector/PaginatedListSelectorViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Grouped Products/ProductListMultiSelectorDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Grouped Products/ProductListMultiSelectorSearchUICommand.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Grouped Products/ProductListSelectorViewController.swift
- WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchUICommand.swift
- WooCommerce/Classes/ViewRelated/Search/SearchUICommand.swift
- WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/ListSelector/ProductListMultiSelectorDataSourceTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Search/Product/ProductListMultiSelectorSearchUICommandTests.swift
- Yosemite/Yosemite/Actions/ProductAction.swift
- Yosemite/Yosemite/Stores/ProductStore.swift
Search product list selector for grouped product's linked products #2199
This PR implements the highlighted screen in the flow to search and select linked products for a grouped product:
Note: I understand that there are a bunch of changes to make the UI sync with the selected product IDs from multiple sources (search UI and product list selector). Happy to explain any changes further, and feel free to suggest a better way for these UI components to interact with each other!
- In `PaginatedListSelectorViewController` (the child view controller of the screen that presents search UI), added `reloadData` function to allow the paginated list selector to reload data in case of data changes not from selecting from the list
- In `ProductListMultiSelectorDataSource` (the data source for the …
> Edit Grouped Products: edit linked products (Part 3/3) - search product list selector

- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewModel.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductPriceSettingsViewModelTests.swift
Prerequisite for #2085
As part of the UI differences for editing a product variation in p91TBi-33Q-p2, we want to hide the tax status row in price settings for a product variation. This PR prepares the price settings view controller and view model to allow hiding the tax status row when the price settings supports a product variation (after https://github.com/woocommerce/woocommerce-ios/pull/2552).
- Moved `datePickerSaleFromVisible` and `datePickerSaleToVisible` states and handling from `ProductPriceSettingsViewController` to `ProductPriceSettingsViewModel` with these two action functions in `ProductPriceSettingsViewModelOutput` protocol:
- `func didTapScheduleSaleFromRow()`
- `func didTapScheduleSaleToRow()`
- Moved the logic to calculate the visible sections from …
> Refactoring on price settings: move sections and date picker states from view controller to view model

- WooCommerce/Classes/ViewRelated/Editor/EditorFactory.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/BottomSheetListSelector/ProductFormActionsFactory.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/BottomSheetListSelector/ProductFormActionsFactoryProtocol.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Price/ProductPriceSettingsViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/List Selector Data Source/PaginatedProductShippingClassListSelectorDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Product+ProductForm.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormDataModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Shipping Settings/ProductShippingSettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Media/Product+Media.swift
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImageActionHandler.swift
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Extensions/Product+ShippingTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Product+ProductFormTests.swift
- Yosemite/Yosemite.xcodeproj/project.pbxproj
- Yosemite/Yosemite/Actions/TaxClassAction.swift
- Yosemite/Yosemite/Model/Extensions/Product+Settings.swift
- Yosemite/Yosemite/Stores/TaxClassStore.swift
Prerequisite for #2085 
This PR abstracts parts of concrete usage with protocol in the product form and its related classes, so that `ProductVariation` can be supported for these classes in a future subtask. These changes should be pretty straightforward. I left the more complicated protocol that abstracts the current `ProductFormViewModel` for a future subtask. In addition, I left the `Product` protocol replacement in price and inventory settings for later since these 2 screens have UI changes between `Product` and `ProductVariation` (p91TBi-33Q-p2).
- Created `ProductFormActionsFactoryProtocol` protocol that the existing `ProductFormActionsFactory` conforms to, and updated its existing usage
- Created `ProductFormDataModel` protocol that abstracts the `Product` usage in product form. It …
> Replace concrete usage with protocol: `ProductFormDataModel`, `ProductFormActionsFactoryProtocol`, and `TaxClassRequestable`

- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
Fixes #2402
When clicking on a product image on the product details screen, now we open the "Photos" screen, like in Android. I fire also the event `product_detail_add_image_tapped` since the behavior is the same of adding a new photo.
1. Open a Product with some images.
2. Tap an image.
3. The "Photos" screen will be presented.
4. Try to upload a photo, press done, and while is uploading, try to tap the image. In this case, nothing has to happen.
> Edit Product: open "Photos" when tapping on Product image

- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/Settings/ProductSettingsRowsTests.swift
Fixes #2526 
I added some unit tests for two specific cases of `ProductSettingsRows`, in particular the one related to VirtualProduct and ReviewsAllowed rows, since only in these two rows we handle the value of settings inside the cell (the value change inside it because we use a `SwitchTableViewCell` that contains a switch). 
The other rows do not seem to need testing, as the updated value always comes from the outside (other view controllers), but if you have any suggestion, feel free to suggest it 😃 
- CI
> Unit tests for ProductSettingsRows

- WooCommerce/Classes/System/WooConstants.swift
- WooCommerce/Classes/ViewRelated/Survey/SurveyViewController.swift
- WooCommerce/Classes/ViewRelated/Survey/SurveyViewController.xib
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/Survey/SurveyViewControllerTests.swift
Relates to #2544 
For the in-app feedback project, we have decided to render the survey in a web view to speed up development times as this module is not a core part of our product.
This PR adapts [part of the work](https://github.com/woocommerce/woocommerce-ios/compare/spike/web-view-survey?expand=1) done by the great @jaclync and introduces `SurveyViewController` into the project, which is configured with a `SurveySource` internal enum.
The idea to have an internal enum rather than exposing a public link is to have total control over what kind of web page/survey we support.
- Added survey URL in `WooConstants.swift`
- Configure view from `SurveySource` enum
- Copy navigation handling work from [spike branch](https://github.com/woocommerce/woocommerce-ios/compare/spike/web-view-survey?exp …
> Adds SurveyViewController

- Storage/Storage.xcodeproj/project.pbxproj
- Storage/Storage/Model/GeneralAppSettings.swift
- Yosemite/Yosemite/Actions/AppSettingsAction.swift
- Yosemite/Yosemite/Stores/AppSettingsStore.swift
- Yosemite/YosemiteTests/Stores/AppSettingsStoreTests.swift
Part of #2537. 
This adds `AppSettingsActions` to persist information to support checking the conditions for #2537:
Condition | New `AppSettingAction`
Users who’ve installed the app at least 3 months ago | `setInstallationDateIfNecessary`
Once every 6 months | `setLastFeedbackDate`
As far as I can tell, we do not currently track the _installation date_ but please let me know if we do! 
The actions eventually lead to persisting a new `struct`, [`GeneralAppSettings`](https://github.com/woocommerce/woocommerce-ios/blob/issue/2537-add-app-settings/Storage/Storage/Model/GeneralAppSettings.swift). I pondered about this for a while. We save **a lot** of files in `AppSettingsStore`. And I think because of these, we now have so many boilerplate. It felt quite cumbersome to save …
> Add AppSettingsAction for In-app Feedback

- WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersPeriodViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift
- WooCommerce/Classes/ViewRelated/InAppFeedback/InAppFeedbackCardViewController.swift
- WooCommerce/Classes/ViewRelated/InAppFeedback/InAppFeedbackCardViewController.xib
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Part of #2537. 
This adds the in-app feedback card in the Today tab for Stats V4. The card currently does not do anything. This is mostly just a UI implementation. This should unblock the other In-app Feedback tasks like #2544 and #2543.  
Large Font | Light  | Dark
--------|-------|-
We'll ask Garance for a design review when she's back. 
The card has to be added as a child of `StoreStatsAndTopPerformersPeriodViewController` so I created it as a `UIViewController`, [`InAppFeedbackCardViewController`](https://github.com/woocommerce/woocommerce-ios/blob/issue/2537-add-in-app-feedback-card/WooCommerce/Classes/ViewRelated/InAppFeedback/InAppFeedbackCardViewController.swift).
The card is only shown when:
- The `inAppFeedback` feature flag is turned on
- If the …
> Add In-app Feedback Card

- WooCommerce/Classes/Authentication/AuthenticationManager.swift
- WooCommerce/Classes/System/WooConstants.swift
- WooCommerce/Classes/Tools/Zendesk/ZendeskManager.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/About/AboutViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/Privacy/PrivacySettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Orders/OrdersMasterViewController.swift
- WooCommerce/Classes/ViewRelated/Survey/SurveyViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/System/WooConstantsTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/ReusableViews/EmptyStateViewController/EmptyStateViewControllerTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Survey/SurveyViewControllerTests.swift
While working on #2570 I had to add a new URL to `WooConstants. I noticed that we use a function called `trustedURL` to return a non-optional URL. If the URL is malformed the app will crash. While the regular procedure is that we test that the URLs are correctly formed I think there is still a chance(human error) that some error could go unnoticed, especially during PRs with big changes.
To mitigate this I've moved these URLs out to an enum that conforms to `CaseIterable` where we can test that all URLs are correct.
**NOTE:** Feel free to tell me if you think that I may be worrying too much and this is not that necessary.
- CI Passes
- Do a quick smoke test in the app to see that the correct URLs are being launched.
> Add tests to WooConstant

- WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventoryEditableData.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventorySettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
Inventory settings for a variation - part of #2085
- Updated `ProductInventorySettingsViewController` to take in `ProductFormDataModel` protocol instead of concrete `Product`, so that it works for both `Product` and `ProductVariation`
- Since `soldIndividually` is only available/editable in `Product`, I had to switch on the product model's type for this field in some instances. If you have better ideas on handling this difference, please lemme know!
- It'd be nice if this view controller has a view model to be unit tested, but that would involve a bunch of other changes. I reopened this issue https://github.com/woocommerce/woocommerce-ios/issues/1985 to track this since these screens support two data models now.
- Updated `soldIndividually` in `ProductInventoryEditableData` to be …
> Update product inventory settings to take in `ProductFormDataModel` protocol to allow `Product` and `ProductVariation`

- WooCommerce/Classes/Notifications/PushNotificationsManager.swift
- WooCommerce/Classes/ServiceLocator/PushNotesManager.swift
- WooCommerce/WooCommerceTests/Mockups/MockPushNotificationsManager.swift
- WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift
Ref #2254. 
This will be used as part of #2254. I'm submitting it earlier since the [WIP branch](https://github.com/woocommerce/woocommerce-ios/compare/develop...issue/2254-fix-review-push-navigation?expand=1) is almost 500 lines and I have not even removed the old code yet. 😱 
This adds a new `inactiveNotifications` `Observable`, similar to the existing `foregroundNotifications`.
https://github.com/woocommerce/woocommerce-ios/blob/98f4369f151c3154eb282b88c79870312491e609/WooCommerce/Classes/Notifications/PushNotificationsManager.swift#L26-L33
Please test that you can still receive new order push notifications and tapping on them will open the order details.
> Add PushNotesManager.inactiveNotifications Observable

- WooCommerce/Classes/ViewRelated/Products/Edit Product/BottomSheetListSelector/ProductVariationFormActionsFactory.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductVariationFormActionsFactoryTests.swift
Product form actions factory for a variation - part of #2085
- Created `ProductVariationFormActionsFactory` that conforms to `ProductFormActionsFactoryProtocol`
- Added tests for `ProductVariationFormActionsFactory`
Since the changes don't affect the app behavior yet, just CI!
> Create a product form actions factory for a product variation

- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductVariationFormViewModel.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Mockups/MockProductVariationStoresManager.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductVariationFormViewModel+ChangesTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductVariationFormViewModel+ObservablesTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductVariationFormViewModel+UpdatesTests.swift
Product form view model for a variation - part of #2085
Note: sorry about the PR size, this PR only contains one class (~215 diffs) and the rest of the code are on unit tests with a mock stores manager.
- Created `ProductVariationFormViewModel` that conforms to `ProductFormViewModelProtocol` with unit tests
- Unfortunately, the difference in the editable fields between `Product` and `ProductVariation` results in a few no-op functions and variables in `ProductVariationFormViewModel`. I'm open to any other ideas to make the form work for both product models that allow customizations in the actions!
Since the changes don't affect the app behavior yet, just CI!
> Create a product form view model for a product variation 

- Networking/Networking.xcodeproj/project.pbxproj
- Networking/Networking/Model/Product/ProductVariation.swift
- Networking/NetworkingTests/Mapper/ProductVariationListMapperTests.swift
- Networking/NetworkingTests/Mapper/ProductVariationMapperTests.swift
- Networking/NetworkingTests/Remote/ProductVariationsRemoteTests.swift
- Networking/NetworkingTests/Responses/product-variations-load-all-manage-stock-two-states.json
- WooCommerce/Classes/ViewModels/ProductDetailsViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventorySettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormSection+ReusableTableRow.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModelProtocol.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Shipping Settings/ProductShippingSettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
Variation form - part of #2085 
This PR includes various changes and fixes to make a product variation editable on the basic fields - description, price, shipping, and inventory.
Please see the differences between a product and variation form in the description of https://github.com/woocommerce/woocommerce-ios/issues/2085, this PR includes all the changes except for the product images!
- Networking layer - a few fixes were made to `ProductVariation` to allow editing inventory and saving a product variation without an image:
- Updated the logic on how `manageStock` is decoded from the API response: there are two states, whether a variation has its stock management enabled at variation level (`manage_stock` is `true` in the API) or it follows its parent product's stock status …
> Product variations are now editable - description, price, shipping, and inventory

- Yosemite/Yosemite/Model/Enums/StatsTimeRangeV4.swift
- Yosemite/Yosemite/Stores/StatsStoreV4.swift
[An error was reported](https://github.com/woocommerce/woocommerce-ios/issues/2583) where stats were not being properly rendered on the weekly leaderboard in contrast with that is shown on the web dashboard.
I couldn't reproduce the reported bug but after comparing the URLs requested by the web-dashboard and by the WC-app I noticed that we were sending the wrong "unit" parameter. We were sending `day` instead of `week`.
- Added a new `leaderboardsGranularity` method to return the correct `StatsGranularityV4` for the leaderboards API.
- Make sure you have some orders this week at your store.
- On the web, go to your store's WooCommerce > Dashboard (wc-admin).
- Under "Date Range" select "Week to Date" and then "Update." 
- Notice the data displayed under "Top Products - Items Sold" on that …
> Fix wrong parameter in leaderboards remote when requesting weekly leaderboards

- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormDataModel.swift
- WooCommerce/Classes/ViewRelated/Products/Media/DeviceMediaLibraryPicker.swift
- WooCommerce/Classes/ViewRelated/Products/Media/MediaPickingCoordinator.swift
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImageViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesCollectionViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Media/WordPressMediaLibraryImagePickerViewController.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Product+ProductFormTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/ProductVariation+ProductFormTests.swift
Fixes #2085
This completes the last part of #2085, with changes in product images UX since a variation can only have up to one image and there is an API issue #2576 that prevents an image to be removed from a variation. 
- Added `allowsMultipleImages() -> Bool` and `isImageDeletionEnabled() -> Bool` to `ProductFormDataModel` protocol, and returned `true` for both of a `Product` and `false` of a `ProductVariation`.
- In `ProductImagesViewController` (top-level view controller that has a child view controller `ProductImagesCollectionViewController`), added `allowsMultipleImages` check for updating the CTA title and passed `allowsMultipleImages` to `MediaPickingCoordinator`. Also, if only one image is allowed, deleted the existing image before committing the image upload action.
- In …
> Update product image upload UX to support product variation

- Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Fixes #2199 
(This is the last subtask of #2199)
- Added a missing test case that verifies that `ProductAction.retrieveProducts` makes a network request that includes the corresponding params for page number and page size
Just CI!
> Add a missing test case for `ProductAction.retrieveProducts` with a page number and page size

- WooCommerce/Classes/ViewRelated/Survey/SurveyLoadingView.swift
- WooCommerce/Classes/ViewRelated/Survey/SurveyViewController.swift
- WooCommerce/Classes/ViewRelated/Survey/SurveyViewController.xib
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/Survey/SurveyViewControllerTests.swift
fixes #2571 
Prior to this PR, the user was left staring at an empty screen while the in-app survey loads. Since the survey can take a couple of seconds to load, we have decided to add a loading indicator view.
- Creates a new `SuveryLoadingView` to hold the loading indicator
- Present the loading view when the request to load the survey is fired
- Hide the loading view when the survey has finished loading
PS: I've also updated some tests to use the new method name case.
- Add the following code in `InAppFeedbackCardViewController`, `configureDidNotLikeButton()` method
```swift
didNotLikeButton.on(.touchUpInside) { [weak self] _  in
let vc = SurveyViewController(survey: .inAppFeedback, onCompletion: { })
let nav = WooNavigationController(rootViewController: vc)
self?.present(nav, …
```
> Adds in-app Survey loading view

- WooCommerce/Classes/Tools/Observables/BehaviorSubject.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Tools/Observables/BehaviorSubjectTests.swift
- WooCommerce/WooCommerceTests/Tools/Observables/PublishSubjectTests.swift
I'm hoping to use this when implementing #2537. I could not use [`PublishSubject`](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/Tools/Observables/PublishSubject.swift) because I needed this behavior provided by Combine's [`CurrentValueSubject`](https://developer.apple.com/documentation/combine/currentvaluesubject) or ReactiveX's [`BehaviorSubject`](http://reactivex.io/documentation/subject.html):
> maintains a buffer of the most recently published element.
This PR only adds [`BehaviorSubject`](https://github.com/woocommerce/woocommerce-ios/blob/issue/2537-add-behavior-subject/WooCommerce/Classes/Tools/Observables/BehaviorSubject.swift). It is a simple version of one of the Observables/Publishers that Combine supports — …
> Add BehaviorSubject observable

- WooCommerce/Classes/ViewRelated/InAppFeedback/InAppFeedbackCardViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/inAppFeedback/InAppFeedbackCardViewControllerTests.swift
closes #2543 
This is a simple PR that presents the system in-app store review form.
- Call `SKStoreReviewController.requestReview()` method to present the in-app review form.
- Hide `SKStoreReviewController.requestReview()`behind a protocol so we can mock it and add tests to this.
- Launch the app and take on the "I Like it" button from the in-app feedback card.
- See that the in-app store review form appears.
**Note that in debug builds you won't be able to submit the review**
> Shows in-app review from Feedback card

- WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventorySettingsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Inventory Settings/ProductInventorySettingsViewModel.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductInventorySettingsViewModel+VariationTests.swift
Fixes #2596 
More context for the change in #2596 (there's a p2 link).
- In `ProductInventorySettingsViewController`, removed the `viewModel.isStockStatusEnabled` condition to configure the stock status cell's accessory type differently now that the cell is only shown when `viewModel.isStockStatusEnabled` is `true`
- In `ProductInventorySettingsViewModel`'s sections setup, updated to hide the stock status row when `isStockStatusEnabled` is `false` (if the model is a variation)
- Updated a test case on a variation's inventory settings section
- Tap on a variable product
- Tap on the variations row
- Tap on a variation
- Tap on the inventory row (or from the bottom sheet)
- Turn off the "Manage stock" switch --> the stock status row should not be visible
- Go to the …
> Product Variation > Inventory: hide stock status row when stock management is disabled

- WooCommerce/Classes/ViewRelated/Products/Edit Product/EditableProductVariationModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductVariationFormViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/EditableProductVariationModelTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductVariationFormViewModel+ChangesTests.swift
Fixes #2599 
Thanks @pmusolino for discovering this issue first! This issue prevents the user from updating a variation if the variation doesn't have its own SKU and its parent product has a non-empty SKU (this could be a pretty common case). I noticed that Android doesn't have this issue, I'm guessing they only encode a property of a model if it's changed in an update request. I haven't thought of an easy way for us to implement this optional encoding yet, so this PR is a workaround and I'll research about the encoding.
- In `EditableProductVariationModel`, passed a variation's parent product's SKU `parentProductSKU: String?` to its initializer and set the variation's SKU to `nil` if it has the same SKU as its parent product.
- DI'ed `parentProductSKU: String?` to …
> Product Variation: update a variation's SKU to be nil if it's the same as its parent product to fix variation remote update

- Yosemite/Yosemite.xcodeproj/project.pbxproj
- Yosemite/Yosemite/Actions/AppSettingsAction.swift
- Yosemite/Yosemite/Stores/AppSettings/InAppFeedbackCardVisibilityUseCase.swift
- Yosemite/Yosemite/Stores/AppSettingsStore.swift
- Yosemite/YosemiteTests/Mockups/MockupFileManager.swift
- Yosemite/YosemiteTests/Stores/AppSettings/InAppFeedbackCardVisibilityUseCaseTests.swift
- Yosemite/YosemiteTests/Stores/AppSettingsStoreTests.swift
Ref #2537
This adds `AppSettingsAction.loadInAppFeedbackCardVisibility`, which determines whether the in-app feedback card should be displayed to the user. 
The result is only `true` if these conditions are met:
- The known installation date is more than 3 months ago
- The user has not given feedback for more than 6 months ago.
These values are based on the actions created in https://github.com/woocommerce/woocommerce-ios/pull/2556. 
In https://github.com/woocommerce/woocommerce-ios/pull/2556, we added actions to set the `GeneralAppSettings.installationDate`. However, if we simply just use this value, then that will mean that even old users will not be able to see the in-app feedback card **until 3 months** after we've released the in-app feedback feature. 
So we can show the in-app …
> Add AppSettingsAction.loadInAppFeedbackCardVisibility

- WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersPeriodViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersPeriodViewModel.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersViewController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Mockups/MockFeatureFlagService.swift
- WooCommerce/WooCommerceTests/Mockups/MockupStoresManager.swift
- WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Stats V4/StoreStatsAndTopPerformersPeriodViewModelTests.swift
Closes #2537. 
This depends on #2623 which has been reviewed and approved but hasn't been merged yet. I'll merge it after the release cut.
This PR integrates the action [`AppSettingsAction.loadInAppFeedbackCardVisibility`](https://github.com/woocommerce/woocommerce-ios/blob/fd208e19dee798df19578b636ba03a4a075dd5a7/Yosemite/Yosemite/Actions/AppSettingsAction.swift#L83-L90) (#2623) to the card UI. The UI will now only show up in these conditions:
1. Users who’ve installed the app at least 3 months ago.
2. Once every 6 months. (this will have to be tested later)
ℹ️  The buttons' functionalities will be integrated later with #2626 and #2605. 
I moved the `canDisplayInAppFeedbackCard` logic into a new ViewModel, [`StoreStatsAndTopPerformersPeriodViewModel`](https://github.com/woocommerce/woocom …
> Integrate In-app Feedback Card Conditions for Displaying

- Networking/Networking/Model/Product/Product.swift
- RELEASE-NOTES.txt
- Yosemite/YosemiteTests/Stores/ProductStoreTests.swift
Fixes #2637 
- Removed custom `Equatable` implementation in `Product` and used the default one so that we don't skip the `salePrice`
- it was intentionally skipped before, but I don't think the alternative types matter when comparing two `Product`s with fixed types https://github.com/woocommerce/woocommerce-ios/blob/faee100732aeb94752aa66e8f06fd786042cd336/Networking/Networking/Model/Product/Product.swift#L595
1. Edit a simple product
2. Navigate to Price
3. Change the Sale Price only
4. Tap Done --> "Update" CTA should be shown and the sale price in the product details should be the one entered previously
5. Tap Update --> the sale price of the product should be updated remotely
> Fix updating a price with only sale price change doesn't trigger update

- WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersPeriodViewController.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersPeriodViewModel.swift
- WooCommerce/Classes/ViewRelated/InAppFeedback/InAppFeedbackCardViewController.swift
- WooCommerce/Classes/ViewRelated/Survey/SurveyCoordinatingController.swift
- WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Stats V4/StoreStatsAndTopPerformersPeriodViewModelTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/inAppFeedback/InAppFeedbackCardViewControllerTests.swift
closes #2629
This PR hides the in-App feedback card in the dashboard after the user taps on any call to action. Which could be the "I like it" button which will trigger the app store review or the "Could be Better" button which will trigger the survey flow.
- Expose closure on `InAppFeedbackCardViewController` to inform it's parent controller when the feedback has been given.
- Adds a new method `onInAppFeedbackCardAction` on `StoreStatsAndTopPerformersPeriodViewModel` which sets the `lastFeedbackDate` and recalculates the `inAppFeedbackCard` visibility.
- Delete the app on the device.
- Run the app and log in.
- Time travel to at least 90 days from now.
- Navigate to the Orders tab and navigate back to My Store.
- Confirm that the in-app feedback card is now visible.
- Tap on any call to …
> Hide inApp feedback card after CTAs

- README.md
I promised to do this more than 2 months ago during a discussion with Platform. 😅 It's pretty common to have Ruby issues and the usual solution is to use rbenv. The built-in macOS Ruby is so easy to break. This PR updates the `README.md` to mention that we prefer rbenv when installing Ruby. I also made the Ruby requirement as the second step. 
Please view the updated `README.md` [here](https://github.com/woocommerce/woocommerce-ios/blob/update/docs-rbenv/README.md).
> Docs: Mention rbenv Preference

- WooCommerce/Classes/Authentication/AuthenticationManager.swift
This PR brings the latest changes in `release/4.7` (disable Google Sign In) into `4.8`.
> Merge release 4.8 into 4.7

- WooCommerce/Classes/ViewModels/ProductDetailsViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/EditableProductModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/EditableProductVariationModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormActionsFactory.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormDataModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormSection+ReusableTableRow.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/BottomSheetListSelector/ProductFormActionsFactory+NonEmptyBottomSheetActionsTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormActionsFactory+EditProductsM3Tests.swift
Closes #2262 
In this PR, I handled the logic for showing the Product Type cell in the Edit Product screen.
The Product Type cell can show these Product types:
- Physical (type is simple, the virtual field is off)
- Virtual (type is simple, the virtual field is on)
- Variable (type is variable)
- Grouped (type is grouped)
- External (type is external)
- A custom product type sent through the API (supported as it comes for free, but there doesn't seem to be any way to use a custom product type).
No actions are supported at the moment, will be part of another PR (here the [related issue](https://github.com/woocommerce/woocommerce-ios/issues/2198)).
1. Navigate to different products (simple physical, simple virtual, variable, grouped, external).
2. For each product, make sure that the cell …
> Edit Product: the product screen now shows the "Product type" row

- Podfile
- Podfile.lock
This PR updates Wormholy from version 1.6.0 to version 1.6.2.
This last version introduces the dark mode, and the requests body is now present again. It was removed wrongly in release 1.6.0.
- Try to open Wormholy from the Settings screen running the app in `debug`.
> Updated Wormholy from v1.6.0 to v1.6.2

- WooCommerce/Classes/System/WooConstants.swift
- WooCommerce/Classes/ViewRelated/Survey/SurveyCoordinatingController.swift
- WooCommerce/Classes/ViewRelated/Survey/SurveyViewController.swift
- WooCommerce/WooCommerceTests/ViewRelated/Survey/SurveyCoordinatorControllerTests.swift
- WooCommerce/WooCommerceTests/ViewRelated/Survey/SurveyViewControllerTests.swift
fixes #2655 
Prior to this PR the `SurveyViewController` didn't take survey errors into consideration before navigating the user to the survey completion screen.
After looking at how the survey behaves I came to the conclusion the at the user is redirected to the survey URL with a special parameter(`msg=done`) when the user has successfully completed a survey. I couldn't find official documentation for this but it was confirmed in p1597419047017800-slack-crowdsignal
- Add the following code in `DashboardViewController`
```swift
let button = UIBarButtonItem(image: .productReviewsImage, style: .plain, target: self, action: #selector(showSurvey))
navigationItem.setLeftBarButton(button, animated: false)
@objc private func showSurvey() {
let coordinator = SurveyCoordinatingController(survey: …
```
> Handle General inApp Feedback Survey Errors

- Yosemite/Yosemite/Stores/ProductReview/RetrieveProductReviewFromNoteUseCase.swift
- Yosemite/YosemiteTests/Stores/ProductReview/RetrieveProductReviewFromNoteUseCaseTests.swift
Ref #2254. 
I'm almost done with fixing #2254. I found that handling push notifications using [`RetrieveProductReviewFromNoteUseCase`](https://github.com/woocommerce/woocommerce-ios/blob/develop/Yosemite/Yosemite/Stores/ProductReview/RetrieveProductReviewFromNoteUseCase.swift) can be slow. It would take a while for the Review Details ViewController to be presented. The current implementation makes use of existing records in Core Data so I copied the same strategy here. 
The `RetrieveProductReviewFromNoteUseCase` will now use any existing `Note`, `ProductReview`, or `Product` in Core Data and will only fetch them if they do not exist locally yet. 
https://github.com/woocommerce/woocommerce-ios/blob/d1e95de346c6d50287985feeccabfa00ce2795d4/Yosemite/Yosemite/Stores/ProductReview/RetrieveProdu …
> RetrieveProductReviewFromNoteUseCase: Use Storage if Possible

- Storage/Storage.xcodeproj/project.pbxproj
- Storage/Storage/Model/FeedbackSettings.swift
- Storage/Storage/Model/FeedbackType.swift
- Storage/Storage/Model/GeneralAppSettings.swift
- Storage/StorageTests/Model/AppSettings/GeneralAppSettingsTests.swift
- WooCommerce/Classes/ViewRelated/Dashboard/Stats v4/StoreStatsAndTopPerformersPeriodViewModel.swift
- WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Stats V4/StoreStatsAndTopPerformersPeriodViewModelTests.swift
- Yosemite/Yosemite/Actions/AppSettingsAction.swift
- Yosemite/Yosemite/Stores/AppSettings/InAppFeedbackCardVisibilityUseCase.swift
- Yosemite/Yosemite/Stores/AppSettingsStore.swift
- Yosemite/YosemiteTests/Stores/AppSettings/InAppFeedbackCardVisibilityUseCaseTests.swift
- Yosemite/YosemiteTests/Stores/AppSettingsStoreTests.swift
relates to https://github.com/woocommerce/woocommerce-ios/issues/2647
The app should support multiple feedback requests. At the time of this writing, a general feedback is requested and we are close to asking feedback for the [product feature](https://github.com/woocommerce/woocommerce-ios/issues/2648).
This PR aims to extend the `GeneralAppSettings` type to save multiple feedback states, one for each feedback.
- Defined a new `FeedbackSettings` type that stores a particular feedback state. Our current options for that state are `pending`, `dismissed` or `given`.
- Modify `GeneralAppSettings` to include this new feedback type
- Modify `AppSettingsStore` to save the `last feedback date` using the new `FeedbackSettings` type.
- See that unit tests pass
And
- Delete the app on the device.
- …
> Add support for storing multiple feedback states

- WooCommerce/Classes/ViewModels/MainTabViewModel.swift
- WooCommerce/Classes/ViewRelated/MainTabBarController.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/Internal/SessionManager+Internal.swift
- WooCommerce/WooCommerceTests/ViewModels/MainTabViewModelTests.swift
Closes #2632. 
This got complicated than expected. At first, I thought that I could just simply dispatch the [`AppSettingsAction.setInstallationDateIfNecessary`](https://github.com/woocommerce/woocommerce-ios/blob/74d9f5b92b55fc9fa51336e4d72e1d3c0831bcf7/Yosemite/Yosemite/Actions/AppSettingsAction.swift#L69-L76) in `AppDelegate`. And then I found out that calling that action has no effect if the user is not logged in because `DeauthenticatedState` doesn't handle any actions. 
https://github.com/woocommerce/woocommerce-ios/blob/74d9f5b92b55fc9fa51336e4d72e1d3c0831bcf7/WooCommerce/Classes/Yosemite/DeauthenticatedState.swift#L20-L22
So, I guess we can't really save the installation date until the user is logged in. This is fine because we currently have no need for the installation date to …
> Save the Installation Date 

- Storage/Storage/Model/FeedbackType.swift
- Yosemite/Yosemite/Stores/AppSettings/InAppFeedbackCardVisibilityUseCase.swift
- Yosemite/YosemiteTests/Stores/AppSettings/InAppFeedbackCardVisibilityUseCaseTests.swift
- Yosemite/YosemiteTests/Stores/AppSettingsStoreTests.swift
closes https://github.com/woocommerce/woocommerce-ios/issues/2647
Prior to this PR, there was no way to reference any other feedback than the general one. This PR adds support to productsM3 feedback.
- Add `productsM3` case to `FeedbackType` enum
- Update `InAppFeedbackCardVisibilityUseCase` to differentiate for feedback type when computing the `shouldBeVisible` method.
- Updates and adds tests.
This PR does not involve any user-facing changes. So running the tests should be enough 😇 
> Add state support to ProductsM3 feedback survey

- docs/README.md
Ref C6H8C3G23/p1597741848003400-slack
- Added documentation on `Localization` nested enum for string constants
No user-facing changes, just CI is good!
> Add documentation on naming convention for nested enum for string constants

- RELEASE-NOTES.txt
- WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsTopBannerFactory.swift
- WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift
- WooCommerce/Classes/ViewRelated/Top Banner/TopBannerView.swift
- WooCommerce/Classes/ViewRelated/Top Banner/TopBannerViewModel.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Fixes #2594 
- Created `ProductVariationsTopBannerFactory` that generates the top banner view when some variations are missing a price, the copy mostly following the [Android PR](https://github.com/woocommerce/woocommerce-android/pull/2717)
- Updated `TopBannerView` and `TopBannerViewModel` to allow no top button and support normal/warning banner type
- In `ProductVariationsViewController`, showed/hid the warning top banner based on whether the latest variations have any missing a price.
- Showing/hiding the top banner dynamically took me 2ish hours 😰 I've tried setting `tableView.tableHeaderView` to `nil`/`topBannerView` whenever the variations change, but it either leaves a gap after hiding the banner or covering the top cells after showing the banner. I also tried showing the banner as …
> Add a warning banner on top of the variation list when any variations are missing a price

- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormActionsFactory.swift
- WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/ProductFormActionsFactory+EditProductsM3Tests.swift
Fixes #2676 
As part of Milestone 3, as suggested by @Garance91540, I moved the Product Type cell for being the last cell of the list in a Product Detail.
1. Open different product types (simple, grouped, external, variable)
2. Make sure that for every product the Product Type cell is the last one in the product detail.
> Edit Product: moved the Product Type cell at the bottom of the list

- WooCommerce/Classes/Styles/UIColor+SemanticColors.swift
Fixes #2678 
As part of the discussion started here p91TBi-39Q, some of the colors implemented in UIColor+SemanticColors.swift are no longer used, so in this PR I removed all them.
- Run the app (if one of the colors is used, you will encounter a compile error)
- CI
> Removed unused colors from UIColor+SemanticColors

- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit External Link/ProductExternalLinkViewController.swift
Fixes #2609 
As part of Milestone 3, in this PR there are two enhancements on External product type. 
In particular:
- Local validation for external URL. If the URL is not valid, an error is shown.
- Auto-fill button text with "Buy product" if the external URL field is empty in the beginning. This will come in handy after that [this PR](https://github.com/woocommerce/woocommerce-ios/pull/2665) will be merged.
1. Open an External product.
2. Tap the cell 
3. If the Button Text in the API is empty, "Buy Product" will be shown as text.
4. Try to edit the Product URL adding a non-valid URL. An error will be shown.
5. Try to re-edit the Product URL using a valid URL. The error should disappear. 
| Valid URL             |  Valid URL (dark mode enabled) |  Non-Valid URL |  Non-Valid URL (dark …
> Edit Product: enhancements to external product URL & link button

- WooCommerce/Classes/ViewRelated/Dashboard/Factories/DashboardTopBannerFactory.swift
- WooCommerce/Classes/ViewRelated/Top Banner/TopBannerView.swift
- WooCommerce/Classes/ViewRelated/Top Banner/TopBannerViewModel.swift
- WooCommerce/WooCommerce.xcodeproj/project.pbxproj
- WooCommerce/WooCommerceTests/ViewRelated/TopBanner/TopBannerViewTests.swift
closes #2646 
For the new products feedback survey, we need to modify the products top banner. Prior this PR the `TopBannerView` class only supported one action button.
- Adds a new `ActionButton` struct inside `TopBannerViewModel` that will represent an action button.
- Update `TopBannerView` to build its view hierarchy based on the new `actionButtons` property from `TopBannerViewModel`.
- Adds some tests.
This is not in the app, but is only to show you how it would look.
Make sure that the current banners(Products and Stats) keep looking as they used to.
* To show the stats banner you may need to replace line 45 of `StatsVersionCoordinator` with
```swift
let nextVersion: StatsVersion = .v3
```
> Add multiple button support to TopBannerView

- WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
- WooCommerce/Classes/ViewModels/ProductDetailsViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Categories/Add Category/AddProductCategoryViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Categories/ProductCategoryListViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Categories/ProductCategoryListViewModel.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit External Link/ProductExternalLinkViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Grouped Products/GroupedProductListSelectorDataSource.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Grouped Products/GroupedProductsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Edit Tags/ProductTagsViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Product Settings/ProductSettingsRows.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift
- WooCommerce/Classes/ViewRelated/Products/Edit Product/Reviews/ProductReviewsViewModel.swift
- Yosemite/Yosemite/Actions/ProductCategoryAction.swift
- Yosemite/Yosemite/Actions/ProductTagAction.swift
Part 1/2 of #2509 
Since the variation events are a bit more involved, I grouped the more straightforward events in this PR and the next PR would include the events for editing a product variation.
- Added 26 new events to `WooAnalyticsStat`
- Implemented logging for the 26 new events - for "done" events from product tags/categories, I started logging in the view controllers instead of the already giant `ProductFormViewController` like price/inventory/shipping settings. also, I noticed that we weren't logging tap events from product form bottom sheet so I added logging for all actions including some of the new events.
- Tap on any core product
- Tap on the categories row or from the bottom sheet --> should see `🔵 Tracked product_detail_view_categories_tapped` in …
> Edit Products M3: analytics (part 1/2)
