woocommerce/woocommerce-ios

RELEASE-NOTES.txt, WooCommerce/Resources/Info.plist, WooCommerce/Resources/en.lproj/Localizable.strings, WooCommerce/Resources/release_notes.txt
Merge Release/1.1 into develop
=> Merge Release/1.1 into develop

WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
Fixes #638.
Go to the [spreadsheet](https://docs.google.com/spreadsheets/d/17cKoFpHQpUMNo-stHSIyEyHbOZ30AIikTHWf9GKVwI0/edit#gid=86001244). In the `Data/Action Events` tab, scroll to the bottom and note two events added: `*_support_new_request_file_attached` and `*_support_new_request_file_attachment_failed`. Go to the `View Events` tab and scroll to the bottom. 10 new events for Support should be listed there.
Updated code to use the correct string value for the FAQ enum.
=> Change Tracks string value to match spreadsheet

WooCommerce/Classes/Model/OrderStats+Woo.swift, WooCommerce/Classes/ViewRelated/Dashboard/MyStore/PeriodDataViewController.swift, WooCommerce/Resources/Info.plist, WooCommerce/Resources/en.lproj/Localizable.strings
This PR updates `develop` with the latest fixes in `release/1.1`.
I got some merge conflicts, so I'm asking for a  review to make sure I correctly understood what's going on :-)  
=> Merge release 1.1 into develop

RELEASE-NOTES.txt, WooCommerce/Resources/en.lproj/Localizable.strings, config/Version.Public.xcconfig
Merge Release/1.2 into develop
=> Merge Release/1.2 into develop

WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift
Fixes #715 
To Test:
- check out this branch
- run on sim
- log out
- expectation: log out successfully, no crash
=> Fix threading issue causing crash

WooCommerce/Resources/AppStoreStrings.pot, WooCommerce/Resources/release_notes.txt
Merge Release/1.3 into develop
=> Merge Release/1.3 into develop

WooCommerce/Classes/ViewRelated/Orders/FulfillViewController.swift
=> Fulfill Order: Shipping address is blank

WooCommerce/Resources/AppStoreStrings.pot, config/Version.Public.xcconfig
Merge Release/1.4 into develop
=> Merge Release/1.4 into develop

WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift
This PR updates a comment for the translators (follow up to a translation issue found during the beta testing).
=> Update comment for translators

.configure
This PR updates .configure to the latest version of the credential files.
1. Run `bundle exec fastlane run configure_validate` and verify that it's ok.
=> Update configure to the latest version of the credential files

WooCommerce/Resources/AppStoreStrings.pot, WooCommerce/Resources/release_notes.txt
Merge Release/1.5 into develop
=> Merge Release/1.5 into develop

WooCommerce/Resources/AppStoreStrings.pot, WooCommerce/Resources/release_notes.txt
=> Merge Release/1.6 into develop

WooCommerce/Classes/Analytics/WooAnalyticsStat.swift
Fixes #871. 
While validating events, I found some names were not consistent with the names in the spreadsheet. They are marked with yellow backgrounds in the sheet.
=> Tracks: Fix tracks events that are not consistent with WCAndroid + Spreadsheet

WooCommerce/Resources/AppStoreStrings.pot, WooCommerce/Resources/release_notes.txt
Includes the release notes updates.
=> Merge Release/1.8 into develop

WooCommerce/Resources/AppStoreStrings.pot, WooCommerce/Resources/release_notes.txt
Merging releases notes from `release/2.0` back to `develop`.
=> Release notes for 2.0

WooCommerce/Resources/AppStoreStrings.pot, WooCommerce/Resources/release_notes.txt
Includes edited release notes.
=> Merge Release/2.1 into develop

README.md
Fixes #1075 
A quick PR to update the Swift mentioned in the project README from 4.2 to 5
=> Update reference to Swift version in project README

README.md
Fixes #758 
* Added more details about setup and linting
* Added Security, Getting Help, Resources, and License sections
=> Update README.md with more detailed information

docs/NETWORKING.md, docs/YOSEMITE.md
Fixes #1117 
A very quick and short PR to update the documentation, adding mentions to the new remote and store/action added to support the V4 stats.
- Check if the additions make sense and actually clarify anything.
- No testing required
=> Add mentions to the entities added to support stats V4

WooCommerce/Classes/System/FeatureFlag.swift
Fixes #1063 
Add a feature flag for stats
- Just checkout the branch and check that tests still pass. Which CI should do for us, so... 🤷‍♂
=> Add a feature flag for stats

WooCommerce/Resources/AppStoreStrings.pot, WooCommerce/Resources/release_notes.txt
=> Merge Release/2.4 into develop

WooCommerce/Resources/AppStoreStrings.pot, WooCommerce/Resources/release_notes.txt
=> Update release notes for 2.5

Podfile, Podfile.lock
This PR updates Pods references from beta to final.
=> Update pods to released version.

Storage/Storage.xcodeproj/project.pbxproj, Storage/Storage/Model/MIGRATIONS.md, Storage/Storage/Model/Product+CoreDataProperties.swift, Storage/Storage/Model/ProductSearchResults+CoreDataClass.swift, Storage/Storage/Model/ProductSearchResults+CoreDataProperties.swift, Storage/Storage/Model/WooCommerce.xcdatamodeld/.xccurrentversion, Storage/Storage/Model/WooCommerce.xcdatamodeld/Model 20.xcdatamodel/contents
Fixes #1286 
- Core Data schema change for model version 20
- Added `ProductSearchResults` entity with `keyword: String` attribute and `products` relaitonship
- Added `Product.searchResults` relationship
- Generated/regenerated Core Data subclass files
- Updated `MIGRATIONS.md`
- Build app from `develop`, launch the app
- Build app from PR branch, launch the app, go to Products tab --> should work normally without crashing on Core Data migration
=> Product List: search results model (schema update in Storage layer)

Networking/Networking.xcodeproj/project.pbxproj, Networking/Networking/Remote/ProductsRemote.swift, Networking/NetworkingTests/Remote/ProductsRemoteTests.swift, Networking/NetworkingTests/Responses/products-search-photo.json
Networking layer for #1264 
- Added `searchProducts` to `ProductsRemote` with basic tests
CI, since the new search function is not used yet
=> Product List: search - Networking layer

RELEASE-NOTES.txt, WooCommerce/Classes/System/DefaultFeatureFlagService.swift, WooCommerce/Classes/ViewRelated/Dashboard/Settings/SettingsViewController.swift, WooCommerce/Resources/AppStoreStrings.pot, WooCommerce/Resources/release_notes.txt, config/Version.Public.xcconfig
Merge release 2.7 into develop
=> Merge release 2.7 into develop

WooCommerce/Classes/ViewRelated/Text View Screen/TextViewViewController.swift, WooCommerce/Classes/ViewRelated/Text View Screen/TextViewViewController.xib, WooCommerce/WooCommerce.xcodeproj/project.pbxproj
Fixes #1471 
- Created `TextViewViewController` with a `UITextView` and a placeholder `UILabel`
This new screen hasn't been used yet! Just CI
I tried it with Product title:
placeholder | non-empty title
-- | --
=> Create a screen with an editable text view

fastlane/env/user.env.example
=> Add the AppCenter API Token to the example file

WooCommerce/WooCommerceUITests/README.md
This documentation covers the basics of our UI tests:
* What user flows the UI tests cover
* How to run the UI tests locally
* How to add or update UI tests
=> Add UI test documentation

WooCommerce/Resources/AppStoreStrings.pot, WooCommerce/Resources/release_notes.txt, config/Version.Public.xcconfig
Merges the beta fix in #2342 to develop.
=> Merge 4.3.0.1 to develop

Podfile, Podfile.lock
Refs https://github.com/woocommerce/woocommerce-ios/issues/2371 and https://github.com/woocommerce/woocommerce-ios/issues/1543.
Please see https://github.com/Automattic/Automattic-Tracks-iOS/pull/132 for the full details of this PR and testing instructions.
=> Add UIApplication.State tag to Submitted Sentry Events

config/Version.Public.xcconfig
Merge releaser/4.4 back into develop
=> Merge releaser/4.4 back into develop

WooCommerce/Classes/System/DefaultFeatureFlagService.swift, WooCommerce/Classes/System/FeatureFlag.swift
Closes #2538
This just adds a feature flag. I also tried to improve `DefaultFeatureFlagService` a little bit.
There are no functional changes. Please just confirm that the build passes. 🙂
=> Add Feature Flag for In-app Feedback Project

WooCommerce/Resources/AppStoreStrings.pot, WooCommerce/Resources/release_notes.txt
Copies release notes to `develop` to be sent for translation.
=> Merge 4.7 release notes into develop

WooCommerce/WooCommerceTests/Authentication/Epilogue/SwitchStoreNoticePresenterTests.swift, WooCommerce/WooCommerceTests/Model/AgeTests.swift, WooCommerce/WooCommerceTests/Model/NoteWooTests.swift, WooCommerce/WooCommerceTests/Model/OrderNoteWooTests.swift, WooCommerce/WooCommerceTests/Model/ProductVisibilityTests.swift, WooCommerce/WooCommerceTests/ViewRelated/ListSelector/PaginatedProductShippingClassListSelectorDataSourceTests.swift, WooCommerce/WooCommerceTests/ViewRelated/ListSelector/ProductBackordersSettingListSelectorCommandTests.swift, WooCommerce/WooCommerceTests/ViewRelated/ListSelector/ProductListMultiSelectorDataSourceTests.swift, WooCommerce/WooCommerceTests/ViewRelated/ListSelector/ProductStatusSettingListSelectorCommandTests.swift, WooCommerce/WooCommerceTests/ViewRelated/ListSelector/ProductStockStatusListSelectorCommandTests.swift, WooCommerce/WooCommerceTests/ViewRelated/ListSelector/ProductTaxClassListSelectorDataSourceTests.swift, WooCommerce/WooCommerceTests/ViewRelated/ListSelector/ProductTaxStatusListSelectorCommandTests.swift, WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/Order Summary Section/SummaryTableViewCell/SummaryTableViewCellTests.swift, WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/Order Summary Section/SummaryTableViewCell/SummaryTableViewCellViewModelTests.swift, WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/OrderDetailsDataSourceTests.swift, WooCommerce/WooCommerceTests/ViewRelated/Orders/OrdersViewModelTests.swift, WooCommerce/WooCommerceTests/ViewRelated/ReusableViews/EmptyStateViewController/EmptyStateViewControllerTests.swift, WooCommerce/WooCommerceTests/ViewRelated/ReusableViews/TextFieldTextAlignmentTests.swift
Ref p91TBi-35M-p2
This changes **some** of the test names to snake-case. It doesn't seem too bad to change all of them. I'm just sending this initial set of files for us to see how it looks like. 
Let me know if we shouldn't proceed with this style. 😄 
No functional changes.
=> Use Snake Case for Some Test Method Names

WooCommerce/Resources/AppStoreStrings.pot, WooCommerce/Resources/release_notes.txt
Merge Release/4.8 into develop in order to make the new release notes available for translation.
=> Merge Release/4.8 into develop

.configure
Ref paaHJt-13T-p2. 
After deleting `master` and replacing it `main`, I ran a text search for "master" in the code and this seems to be the only file that would probably be concerned about. 
Admittedly, I have no idea what this file does. 😅 So please let me know how it should be tested!
=> Use main branch in .configure
